// Generated by mtek 0.1.0-dev for language 0.1. Do not edit.
import * as rt from "./runtime.75e25692ce38d7a0.js";
export { mountMtek } from "./runtime.75e25692ce38d7a0.js";
const fr = Math.fround;

export const abi = 1;
export const baseUrl = new URL("./", import.meta.url);
export const manifestUrl = new URL("./program.manifest.json", import.meta.url);

// Generated from layout builtin:frame (size 288). Do not edit.
function w_builtin_MtekFrame_view_proj(m, base, v) {
  const w = base >>> 2;
  m.f32[w + 0] = v[0]; m.f32[w + 1] = v[1]; m.f32[w + 2] = v[2]; m.f32[w + 3] = v[3];
  m.f32[w + 4] = v[4]; m.f32[w + 5] = v[5]; m.f32[w + 6] = v[6]; m.f32[w + 7] = v[7];
  m.f32[w + 8] = v[8]; m.f32[w + 9] = v[9]; m.f32[w + 10] = v[10]; m.f32[w + 11] = v[11];
  m.f32[w + 12] = v[12]; m.f32[w + 13] = v[13]; m.f32[w + 14] = v[14]; m.f32[w + 15] = v[15];
}
function w_builtin_MtekFrame_camera_position(m, base, v) {
  const w = base >>> 2;
  m.f32[w + 16] = v.x; m.f32[w + 17] = v.y; m.f32[w + 18] = v.z;
}
function w_builtin_MtekFrame_light_count(m, base, v) {
  m.u32[(base >>> 2) + 19] = v;
}
function w_builtin_MtekFrame_ambient(m, base, v) {
  const w = base >>> 2;
  m.f32[w + 20] = v.x; m.f32[w + 21] = v.y; m.f32[w + 22] = v.z;
}
function w_builtin_MtekFrame_reserved0(m, base, v) {
  m.f32[(base >>> 2) + 23] = v;
}
function w_builtin_MtekFrame_lights(m, base, v) {
  const w = base >>> 2;
  m.f32[w + 24] = v[0].color.x; m.f32[w + 25] = v[0].color.y; m.f32[w + 26] = v[0].color.z;
  m.u32[w + 27] = v[0].kind;
  m.f32[w + 28] = v[0].position.x; m.f32[w + 29] = v[0].position.y; m.f32[w + 30] = v[0].position.z;
  m.f32[w + 31] = v[0].range;
  m.f32[w + 32] = v[0].direction.x; m.f32[w + 33] = v[0].direction.y; m.f32[w + 34] = v[0].direction.z;
  m.f32[w + 35] = v[0].reserved;
  m.f32[w + 36] = v[1].color.x; m.f32[w + 37] = v[1].color.y; m.f32[w + 38] = v[1].color.z;
  m.u32[w + 39] = v[1].kind;
  m.f32[w + 40] = v[1].position.x; m.f32[w + 41] = v[1].position.y; m.f32[w + 42] = v[1].position.z;
  m.f32[w + 43] = v[1].range;
  m.f32[w + 44] = v[1].direction.x; m.f32[w + 45] = v[1].direction.y; m.f32[w + 46] = v[1].direction.z;
  m.f32[w + 47] = v[1].reserved;
  m.f32[w + 48] = v[2].color.x; m.f32[w + 49] = v[2].color.y; m.f32[w + 50] = v[2].color.z;
  m.u32[w + 51] = v[2].kind;
  m.f32[w + 52] = v[2].position.x; m.f32[w + 53] = v[2].position.y; m.f32[w + 54] = v[2].position.z;
  m.f32[w + 55] = v[2].range;
  m.f32[w + 56] = v[2].direction.x; m.f32[w + 57] = v[2].direction.y; m.f32[w + 58] = v[2].direction.z;
  m.f32[w + 59] = v[2].reserved;
  m.f32[w + 60] = v[3].color.x; m.f32[w + 61] = v[3].color.y; m.f32[w + 62] = v[3].color.z;
  m.u32[w + 63] = v[3].kind;
  m.f32[w + 64] = v[3].position.x; m.f32[w + 65] = v[3].position.y; m.f32[w + 66] = v[3].position.z;
  m.f32[w + 67] = v[3].range;
  m.f32[w + 68] = v[3].direction.x; m.f32[w + 69] = v[3].direction.y; m.f32[w + 70] = v[3].direction.z;
  m.f32[w + 71] = v[3].reserved;
}
function w_builtin_MtekFrame(m, base, v) {
  w_builtin_MtekFrame_view_proj(m, base, v.view_proj);
  w_builtin_MtekFrame_camera_position(m, base, v.camera_position);
  w_builtin_MtekFrame_light_count(m, base, v.light_count);
  w_builtin_MtekFrame_ambient(m, base, v.ambient);
  w_builtin_MtekFrame_reserved0(m, base, v.reserved0);
  w_builtin_MtekFrame_lights(m, base, v.lights);
}

// Generated from layout builtin:object (size 128). Do not edit.
function w_builtin_MtekObject_model(m, base, v) {
  const w = base >>> 2;
  m.f32[w + 0] = v[0]; m.f32[w + 1] = v[1]; m.f32[w + 2] = v[2]; m.f32[w + 3] = v[3];
  m.f32[w + 4] = v[4]; m.f32[w + 5] = v[5]; m.f32[w + 6] = v[6]; m.f32[w + 7] = v[7];
  m.f32[w + 8] = v[8]; m.f32[w + 9] = v[9]; m.f32[w + 10] = v[10]; m.f32[w + 11] = v[11];
  m.f32[w + 12] = v[12]; m.f32[w + 13] = v[13]; m.f32[w + 14] = v[14]; m.f32[w + 15] = v[15];
}
function w_builtin_MtekObject_normal_matrix(m, base, v) {
  const w = base >>> 2;
  m.f32[w + 16] = v[0]; m.f32[w + 17] = v[1]; m.f32[w + 18] = v[2]; m.f32[w + 19] = v[3];
  m.f32[w + 20] = v[4]; m.f32[w + 21] = v[5]; m.f32[w + 22] = v[6]; m.f32[w + 23] = v[7];
  m.f32[w + 24] = v[8]; m.f32[w + 25] = v[9]; m.f32[w + 26] = v[10]; m.f32[w + 27] = v[11];
  m.f32[w + 28] = v[12]; m.f32[w + 29] = v[13]; m.f32[w + 30] = v[14]; m.f32[w + 31] = v[15];
}
function w_builtin_MtekObject(m, base, v) {
  w_builtin_MtekObject_model(m, base, v.model);
  w_builtin_MtekObject_normal_matrix(m, base, v.normal_matrix);
}

export const writers = {
  "builtin:frame": { all: w_builtin_MtekFrame, fields: { view_proj: w_builtin_MtekFrame_view_proj, camera_position: w_builtin_MtekFrame_camera_position, light_count: w_builtin_MtekFrame_light_count, ambient: w_builtin_MtekFrame_ambient, reserved0: w_builtin_MtekFrame_reserved0, lights: w_builtin_MtekFrame_lights } },
  "builtin:object": { all: w_builtin_MtekObject, fields: { model: w_builtin_MtekObject_model, normal_matrix: w_builtin_MtekObject_normal_matrix } },
};

// fn add_f32_f32(a: f32, b: f32) -> f32 (src/main.mtek::add_f32_f32)
function f_e2cab98b_add_f32_f32(ctx, a_a, a_b) {
  return fr(a_a + a_b);
}

// fn sub_f32_f32(a: f32, b: f32) -> f32 (src/main.mtek::sub_f32_f32)
function f_e2cab98b_sub_f32_f32(ctx, a_a, a_b) {
  return fr(a_a - a_b);
}

// fn mul_f32_f32(a: f32, b: f32) -> f32 (src/main.mtek::mul_f32_f32)
function f_e2cab98b_mul_f32_f32(ctx, a_a, a_b) {
  return fr(a_a * a_b);
}

// fn div_f32_f32(a: f32, b: f32) -> f32 (src/main.mtek::div_f32_f32)
function f_e2cab98b_div_f32_f32(ctx, a_a, a_b) {
  return fr(a_a / a_b);
}

// fn rem_f32_f32(a: f32, b: f32) -> f32 (src/main.mtek::rem_f32_f32)
function f_e2cab98b_rem_f32_f32(ctx, a_a, a_b) {
  return fr(a_a % a_b);
}

// fn neg_f32(a: f32) -> f32 (src/main.mtek::neg_f32)
function f_e2cab98b_neg_f32(ctx, a_a) {
  return -a_a;
}

// fn lt_f32_f32(a: f32, b: f32) -> bool (src/main.mtek::lt_f32_f32)
function f_e2cab98b_lt_f32_f32(ctx, a_a, a_b) {
  return a_a < a_b;
}

// fn lt_i32_i32(a: i32, b: i32) -> bool (src/main.mtek::lt_i32_i32)
function f_e2cab98b_lt_i32_i32(ctx, a_a, a_b) {
  return a_a < a_b;
}

// fn lt_u32_u32(a: u32, b: u32) -> bool (src/main.mtek::lt_u32_u32)
function f_e2cab98b_lt_u32_u32(ctx, a_a, a_b) {
  return a_a < a_b;
}

// fn le_f32_f32(a: f32, b: f32) -> bool (src/main.mtek::le_f32_f32)
function f_e2cab98b_le_f32_f32(ctx, a_a, a_b) {
  return a_a <= a_b;
}

// fn le_i32_i32(a: i32, b: i32) -> bool (src/main.mtek::le_i32_i32)
function f_e2cab98b_le_i32_i32(ctx, a_a, a_b) {
  return a_a <= a_b;
}

// fn le_u32_u32(a: u32, b: u32) -> bool (src/main.mtek::le_u32_u32)
function f_e2cab98b_le_u32_u32(ctx, a_a, a_b) {
  return a_a <= a_b;
}

// fn gt_f32_f32(a: f32, b: f32) -> bool (src/main.mtek::gt_f32_f32)
function f_e2cab98b_gt_f32_f32(ctx, a_a, a_b) {
  return a_a > a_b;
}

// fn gt_i32_i32(a: i32, b: i32) -> bool (src/main.mtek::gt_i32_i32)
function f_e2cab98b_gt_i32_i32(ctx, a_a, a_b) {
  return a_a > a_b;
}

// fn gt_u32_u32(a: u32, b: u32) -> bool (src/main.mtek::gt_u32_u32)
function f_e2cab98b_gt_u32_u32(ctx, a_a, a_b) {
  return a_a > a_b;
}

// fn ge_f32_f32(a: f32, b: f32) -> bool (src/main.mtek::ge_f32_f32)
function f_e2cab98b_ge_f32_f32(ctx, a_a, a_b) {
  return a_a >= a_b;
}

// fn ge_i32_i32(a: i32, b: i32) -> bool (src/main.mtek::ge_i32_i32)
function f_e2cab98b_ge_i32_i32(ctx, a_a, a_b) {
  return a_a >= a_b;
}

// fn ge_u32_u32(a: u32, b: u32) -> bool (src/main.mtek::ge_u32_u32)
function f_e2cab98b_ge_u32_u32(ctx, a_a, a_b) {
  return a_a >= a_b;
}

// fn eq_f32_f32(a: f32, b: f32) -> bool (src/main.mtek::eq_f32_f32)
function f_e2cab98b_eq_f32_f32(ctx, a_a, a_b) {
  return a_a === a_b;
}

// fn eq_i32_i32(a: i32, b: i32) -> bool (src/main.mtek::eq_i32_i32)
function f_e2cab98b_eq_i32_i32(ctx, a_a, a_b) {
  return a_a === a_b;
}

// fn eq_u32_u32(a: u32, b: u32) -> bool (src/main.mtek::eq_u32_u32)
function f_e2cab98b_eq_u32_u32(ctx, a_a, a_b) {
  return a_a === a_b;
}

// fn ne_f32_f32(a: f32, b: f32) -> bool (src/main.mtek::ne_f32_f32)
function f_e2cab98b_ne_f32_f32(ctx, a_a, a_b) {
  return a_a !== a_b;
}

// fn ne_i32_i32(a: i32, b: i32) -> bool (src/main.mtek::ne_i32_i32)
function f_e2cab98b_ne_i32_i32(ctx, a_a, a_b) {
  return a_a !== a_b;
}

// fn ne_u32_u32(a: u32, b: u32) -> bool (src/main.mtek::ne_u32_u32)
function f_e2cab98b_ne_u32_u32(ctx, a_a, a_b) {
  return a_a !== a_b;
}

// fn add_i32_i32(a: i32, b: i32) -> i32 (src/main.mtek::add_i32_i32)
function f_e2cab98b_add_i32_i32(ctx, a_a, a_b) {
  return (a_a + a_b) | 0;
}

// fn sub_i32_i32(a: i32, b: i32) -> i32 (src/main.mtek::sub_i32_i32)
function f_e2cab98b_sub_i32_i32(ctx, a_a, a_b) {
  return (a_a - a_b) | 0;
}

// fn mul_i32_i32(a: i32, b: i32) -> i32 (src/main.mtek::mul_i32_i32)
function f_e2cab98b_mul_i32_i32(ctx, a_a, a_b) {
  return Math.imul(a_a, a_b);
}

// fn div_i32_i32(a: i32, b: i32) -> i32 (src/main.mtek::div_i32_i32)
function f_e2cab98b_div_i32_i32(ctx, a_a, a_b) {
  return rt.idiv(a_a, a_b);
}

// fn rem_i32_i32(a: i32, b: i32) -> i32 (src/main.mtek::rem_i32_i32)
function f_e2cab98b_rem_i32_i32(ctx, a_a, a_b) {
  return rt.irem(a_a, a_b);
}

// fn neg_i32(a: i32) -> i32 (src/main.mtek::neg_i32)
function f_e2cab98b_neg_i32(ctx, a_a) {
  return -a_a | 0;
}

// fn add_u32_u32(a: u32, b: u32) -> u32 (src/main.mtek::add_u32_u32)
function f_e2cab98b_add_u32_u32(ctx, a_a, a_b) {
  return (a_a + a_b) >>> 0;
}

// fn sub_u32_u32(a: u32, b: u32) -> u32 (src/main.mtek::sub_u32_u32)
function f_e2cab98b_sub_u32_u32(ctx, a_a, a_b) {
  return (a_a - a_b) >>> 0;
}

// fn mul_u32_u32(a: u32, b: u32) -> u32 (src/main.mtek::mul_u32_u32)
function f_e2cab98b_mul_u32_u32(ctx, a_a, a_b) {
  return Math.imul(a_a, a_b) >>> 0;
}

// fn div_u32_u32(a: u32, b: u32) -> u32 (src/main.mtek::div_u32_u32)
function f_e2cab98b_div_u32_u32(ctx, a_a, a_b) {
  return rt.udiv(a_a, a_b);
}

// fn rem_u32_u32(a: u32, b: u32) -> u32 (src/main.mtek::rem_u32_u32)
function f_e2cab98b_rem_u32_u32(ctx, a_a, a_b) {
  return rt.urem(a_a, a_b);
}

// fn to_i32_f32(a: f32) -> i32 (src/main.mtek::to_i32_f32)
function f_e2cab98b_to_i32_f32(ctx, a_a) {
  return rt.f2i(a_a);
}

// fn to_u32_f32(a: f32) -> u32 (src/main.mtek::to_u32_f32)
function f_e2cab98b_to_u32_f32(ctx, a_a) {
  return rt.f2u(a_a);
}

// fn to_f32_i32(a: i32) -> f32 (src/main.mtek::to_f32_i32)
function f_e2cab98b_to_f32_i32(ctx, a_a) {
  return fr(a_a);
}

// fn to_f32_u32(a: u32) -> f32 (src/main.mtek::to_f32_u32)
function f_e2cab98b_to_f32_u32(ctx, a_a) {
  return fr(a_a);
}

// fn to_i32_u32(a: u32) -> i32 (src/main.mtek::to_i32_u32)
function f_e2cab98b_to_i32_u32(ctx, a_a) {
  return a_a | 0;
}

// fn to_u32_i32(a: i32) -> u32 (src/main.mtek::to_u32_i32)
function f_e2cab98b_to_u32_i32(ctx, a_a) {
  return a_a >>> 0;
}

// fn abs_f32(a: f32) -> f32 (src/main.mtek::abs_f32)
function f_e2cab98b_abs_f32(ctx, a_a) {
  return rt.abs(a_a);
}

// fn saturate_f32(a: f32) -> f32 (src/main.mtek::saturate_f32)
function f_e2cab98b_saturate_f32(ctx, a_a) {
  return rt.saturate(a_a);
}

// fn sqrt_f32(a: f32) -> f32 (src/main.mtek::sqrt_f32)
function f_e2cab98b_sqrt_f32(ctx, a_a) {
  return rt.sqrt(a_a);
}

// fn inverse_sqrt_f32(a: f32) -> f32 (src/main.mtek::inverse_sqrt_f32)
function f_e2cab98b_inverse_sqrt_f32(ctx, a_a) {
  return rt.inverseSqrt(a_a);
}

// fn exp_f32(a: f32) -> f32 (src/main.mtek::exp_f32)
function f_e2cab98b_exp_f32(ctx, a_a) {
  return rt.exp(a_a);
}

// fn exp2_f32(a: f32) -> f32 (src/main.mtek::exp2_f32)
function f_e2cab98b_exp2_f32(ctx, a_a) {
  return rt.exp2(a_a);
}

// fn log_f32(a: f32) -> f32 (src/main.mtek::log_f32)
function f_e2cab98b_log_f32(ctx, a_a) {
  return rt.log(a_a);
}

// fn log2_f32(a: f32) -> f32 (src/main.mtek::log2_f32)
function f_e2cab98b_log2_f32(ctx, a_a) {
  return rt.log2(a_a);
}

// fn sin_f32(a: f32) -> f32 (src/main.mtek::sin_f32)
function f_e2cab98b_sin_f32(ctx, a_a) {
  return rt.sin(a_a);
}

// fn cos_f32(a: f32) -> f32 (src/main.mtek::cos_f32)
function f_e2cab98b_cos_f32(ctx, a_a) {
  return rt.cos(a_a);
}

// fn tan_f32(a: f32) -> f32 (src/main.mtek::tan_f32)
function f_e2cab98b_tan_f32(ctx, a_a) {
  return rt.tan(a_a);
}

// fn asin_f32(a: f32) -> f32 (src/main.mtek::asin_f32)
function f_e2cab98b_asin_f32(ctx, a_a) {
  return rt.asin(a_a);
}

// fn acos_f32(a: f32) -> f32 (src/main.mtek::acos_f32)
function f_e2cab98b_acos_f32(ctx, a_a) {
  return rt.acos(a_a);
}

// fn atan_f32(a: f32) -> f32 (src/main.mtek::atan_f32)
function f_e2cab98b_atan_f32(ctx, a_a) {
  return rt.atan(a_a);
}

// fn floor_f32(a: f32) -> f32 (src/main.mtek::floor_f32)
function f_e2cab98b_floor_f32(ctx, a_a) {
  return rt.floor(a_a);
}

// fn ceil_f32(a: f32) -> f32 (src/main.mtek::ceil_f32)
function f_e2cab98b_ceil_f32(ctx, a_a) {
  return rt.ceil(a_a);
}

// fn trunc_f32(a: f32) -> f32 (src/main.mtek::trunc_f32)
function f_e2cab98b_trunc_f32(ctx, a_a) {
  return rt.trunc(a_a);
}

// fn fract_f32(a: f32) -> f32 (src/main.mtek::fract_f32)
function f_e2cab98b_fract_f32(ctx, a_a) {
  return rt.fract(a_a);
}

// fn sign_f32(a: f32) -> f32 (src/main.mtek::sign_f32)
function f_e2cab98b_sign_f32(ctx, a_a) {
  return rt.sign(a_a);
}

// fn round_f32(a: f32) -> f32 (src/main.mtek::round_f32)
function f_e2cab98b_round_f32(ctx, a_a) {
  return rt.round(a_a);
}

// fn radians_f32(a: f32) -> f32 (src/main.mtek::radians_f32)
function f_e2cab98b_radians_f32(ctx, a_a) {
  return rt.radians(a_a);
}

// fn degrees_f32(a: f32) -> f32 (src/main.mtek::degrees_f32)
function f_e2cab98b_degrees_f32(ctx, a_a) {
  return rt.degrees(a_a);
}

// fn length_f32(a: f32) -> f32 (src/main.mtek::length_f32)
function f_e2cab98b_length_f32(ctx, a_a) {
  return rt.length(a_a);
}

// fn distance_f32_f32(a: f32, b: f32) -> f32 (src/main.mtek::distance_f32_f32)
function f_e2cab98b_distance_f32_f32(ctx, a_a, a_b) {
  return rt.distance(a_a, a_b);
}

// fn min_f32_f32(a: f32, b: f32) -> f32 (src/main.mtek::min_f32_f32)
function f_e2cab98b_min_f32_f32(ctx, a_a, a_b) {
  return rt.min(a_a, a_b);
}

// fn max_f32_f32(a: f32, b: f32) -> f32 (src/main.mtek::max_f32_f32)
function f_e2cab98b_max_f32_f32(ctx, a_a, a_b) {
  return rt.max(a_a, a_b);
}

// fn pow_f32_f32(a: f32, b: f32) -> f32 (src/main.mtek::pow_f32_f32)
function f_e2cab98b_pow_f32_f32(ctx, a_a, a_b) {
  return rt.pow(a_a, a_b);
}

// fn atan2_f32_f32(a: f32, b: f32) -> f32 (src/main.mtek::atan2_f32_f32)
function f_e2cab98b_atan2_f32_f32(ctx, a_a, a_b) {
  return rt.atan2(a_a, a_b);
}

// fn step_f32_f32(a: f32, b: f32) -> f32 (src/main.mtek::step_f32_f32)
function f_e2cab98b_step_f32_f32(ctx, a_a, a_b) {
  return rt.step(a_a, a_b);
}

// fn clamp_f32_f32_f32(a: f32, b: f32, c: f32) -> f32 (src/main.mtek::clamp_f32_f32_f32)
function f_e2cab98b_clamp_f32_f32_f32(ctx, a_a, a_b, a_c) {
  return rt.clamp(a_a, a_b, a_c);
}

// fn mix_f32_f32_f32(a: f32, b: f32, c: f32) -> f32 (src/main.mtek::mix_f32_f32_f32)
function f_e2cab98b_mix_f32_f32_f32(ctx, a_a, a_b, a_c) {
  return rt.mix(a_a, a_b, a_c);
}

// fn smoothstep_f32_f32_f32(a: f32, b: f32, c: f32) -> f32 (src/main.mtek::smoothstep_f32_f32_f32)
function f_e2cab98b_smoothstep_f32_f32_f32(ctx, a_a, a_b, a_c) {
  return rt.smoothstep(a_a, a_b, a_c);
}

// fn abs_i32(a: i32) -> i32 (src/main.mtek::abs_i32)
function f_e2cab98b_abs_i32(ctx, a_a) {
  return rt.iabs(a_a);
}

// fn abs_u32(a: u32) -> u32 (src/main.mtek::abs_u32)
function f_e2cab98b_abs_u32(ctx, a_a) {
  return rt.uabs(a_a);
}

// fn min_i32_i32(a: i32, b: i32) -> i32 (src/main.mtek::min_i32_i32)
function f_e2cab98b_min_i32_i32(ctx, a_a, a_b) {
  return rt.imin(a_a, a_b);
}

// fn max_i32_i32(a: i32, b: i32) -> i32 (src/main.mtek::max_i32_i32)
function f_e2cab98b_max_i32_i32(ctx, a_a, a_b) {
  return rt.imax(a_a, a_b);
}

// fn min_u32_u32(a: u32, b: u32) -> u32 (src/main.mtek::min_u32_u32)
function f_e2cab98b_min_u32_u32(ctx, a_a, a_b) {
  return rt.umin(a_a, a_b);
}

// fn max_u32_u32(a: u32, b: u32) -> u32 (src/main.mtek::max_u32_u32)
function f_e2cab98b_max_u32_u32(ctx, a_a, a_b) {
  return rt.umax(a_a, a_b);
}

// fn clamp_i32_i32_i32(a: i32, b: i32, c: i32) -> i32 (src/main.mtek::clamp_i32_i32_i32)
function f_e2cab98b_clamp_i32_i32_i32(ctx, a_a, a_b, a_c) {
  return rt.iclamp(a_a, a_b, a_c);
}

// fn clamp_u32_u32_u32(a: u32, b: u32, c: u32) -> u32 (src/main.mtek::clamp_u32_u32_u32)
function f_e2cab98b_clamp_u32_u32_u32(ctx, a_a, a_b, a_c) {
  return rt.uclamp(a_a, a_b, a_c);
}

// fn abs_vec2(a: vec2) -> vec2 (src/main.mtek::abs_vec2)
function f_e2cab98b_abs_vec2(ctx, a_a) {
  return rt.v2abs(a_a);
}

// fn abs_vec3(a: vec3) -> vec3 (src/main.mtek::abs_vec3)
function f_e2cab98b_abs_vec3(ctx, a_a) {
  return rt.v3abs(a_a);
}

// fn abs_vec4(a: vec4) -> vec4 (src/main.mtek::abs_vec4)
function f_e2cab98b_abs_vec4(ctx, a_a) {
  return rt.v4abs(a_a);
}

// fn saturate_vec2(a: vec2) -> vec2 (src/main.mtek::saturate_vec2)
function f_e2cab98b_saturate_vec2(ctx, a_a) {
  return rt.v2saturate(a_a);
}

// fn saturate_vec3(a: vec3) -> vec3 (src/main.mtek::saturate_vec3)
function f_e2cab98b_saturate_vec3(ctx, a_a) {
  return rt.v3saturate(a_a);
}

// fn saturate_vec4(a: vec4) -> vec4 (src/main.mtek::saturate_vec4)
function f_e2cab98b_saturate_vec4(ctx, a_a) {
  return rt.v4saturate(a_a);
}

// fn sqrt_vec2(a: vec2) -> vec2 (src/main.mtek::sqrt_vec2)
function f_e2cab98b_sqrt_vec2(ctx, a_a) {
  return rt.v2sqrt(a_a);
}

// fn sqrt_vec3(a: vec3) -> vec3 (src/main.mtek::sqrt_vec3)
function f_e2cab98b_sqrt_vec3(ctx, a_a) {
  return rt.v3sqrt(a_a);
}

// fn sqrt_vec4(a: vec4) -> vec4 (src/main.mtek::sqrt_vec4)
function f_e2cab98b_sqrt_vec4(ctx, a_a) {
  return rt.v4sqrt(a_a);
}

// fn inverse_sqrt_vec2(a: vec2) -> vec2 (src/main.mtek::inverse_sqrt_vec2)
function f_e2cab98b_inverse_sqrt_vec2(ctx, a_a) {
  return rt.v2inverseSqrt(a_a);
}

// fn inverse_sqrt_vec3(a: vec3) -> vec3 (src/main.mtek::inverse_sqrt_vec3)
function f_e2cab98b_inverse_sqrt_vec3(ctx, a_a) {
  return rt.v3inverseSqrt(a_a);
}

// fn inverse_sqrt_vec4(a: vec4) -> vec4 (src/main.mtek::inverse_sqrt_vec4)
function f_e2cab98b_inverse_sqrt_vec4(ctx, a_a) {
  return rt.v4inverseSqrt(a_a);
}

// fn exp_vec2(a: vec2) -> vec2 (src/main.mtek::exp_vec2)
function f_e2cab98b_exp_vec2(ctx, a_a) {
  return rt.v2exp(a_a);
}

// fn exp_vec3(a: vec3) -> vec3 (src/main.mtek::exp_vec3)
function f_e2cab98b_exp_vec3(ctx, a_a) {
  return rt.v3exp(a_a);
}

// fn exp_vec4(a: vec4) -> vec4 (src/main.mtek::exp_vec4)
function f_e2cab98b_exp_vec4(ctx, a_a) {
  return rt.v4exp(a_a);
}

// fn exp2_vec2(a: vec2) -> vec2 (src/main.mtek::exp2_vec2)
function f_e2cab98b_exp2_vec2(ctx, a_a) {
  return rt.v2exp2(a_a);
}

// fn exp2_vec3(a: vec3) -> vec3 (src/main.mtek::exp2_vec3)
function f_e2cab98b_exp2_vec3(ctx, a_a) {
  return rt.v3exp2(a_a);
}

// fn exp2_vec4(a: vec4) -> vec4 (src/main.mtek::exp2_vec4)
function f_e2cab98b_exp2_vec4(ctx, a_a) {
  return rt.v4exp2(a_a);
}

// fn log_vec2(a: vec2) -> vec2 (src/main.mtek::log_vec2)
function f_e2cab98b_log_vec2(ctx, a_a) {
  return rt.v2log(a_a);
}

// fn log_vec3(a: vec3) -> vec3 (src/main.mtek::log_vec3)
function f_e2cab98b_log_vec3(ctx, a_a) {
  return rt.v3log(a_a);
}

// fn log_vec4(a: vec4) -> vec4 (src/main.mtek::log_vec4)
function f_e2cab98b_log_vec4(ctx, a_a) {
  return rt.v4log(a_a);
}

// fn log2_vec2(a: vec2) -> vec2 (src/main.mtek::log2_vec2)
function f_e2cab98b_log2_vec2(ctx, a_a) {
  return rt.v2log2(a_a);
}

// fn log2_vec3(a: vec3) -> vec3 (src/main.mtek::log2_vec3)
function f_e2cab98b_log2_vec3(ctx, a_a) {
  return rt.v3log2(a_a);
}

// fn log2_vec4(a: vec4) -> vec4 (src/main.mtek::log2_vec4)
function f_e2cab98b_log2_vec4(ctx, a_a) {
  return rt.v4log2(a_a);
}

// fn sin_vec2(a: vec2) -> vec2 (src/main.mtek::sin_vec2)
function f_e2cab98b_sin_vec2(ctx, a_a) {
  return rt.v2sin(a_a);
}

// fn sin_vec3(a: vec3) -> vec3 (src/main.mtek::sin_vec3)
function f_e2cab98b_sin_vec3(ctx, a_a) {
  return rt.v3sin(a_a);
}

// fn sin_vec4(a: vec4) -> vec4 (src/main.mtek::sin_vec4)
function f_e2cab98b_sin_vec4(ctx, a_a) {
  return rt.v4sin(a_a);
}

// fn cos_vec2(a: vec2) -> vec2 (src/main.mtek::cos_vec2)
function f_e2cab98b_cos_vec2(ctx, a_a) {
  return rt.v2cos(a_a);
}

// fn cos_vec3(a: vec3) -> vec3 (src/main.mtek::cos_vec3)
function f_e2cab98b_cos_vec3(ctx, a_a) {
  return rt.v3cos(a_a);
}

// fn cos_vec4(a: vec4) -> vec4 (src/main.mtek::cos_vec4)
function f_e2cab98b_cos_vec4(ctx, a_a) {
  return rt.v4cos(a_a);
}

// fn tan_vec2(a: vec2) -> vec2 (src/main.mtek::tan_vec2)
function f_e2cab98b_tan_vec2(ctx, a_a) {
  return rt.v2tan(a_a);
}

// fn tan_vec3(a: vec3) -> vec3 (src/main.mtek::tan_vec3)
function f_e2cab98b_tan_vec3(ctx, a_a) {
  return rt.v3tan(a_a);
}

// fn tan_vec4(a: vec4) -> vec4 (src/main.mtek::tan_vec4)
function f_e2cab98b_tan_vec4(ctx, a_a) {
  return rt.v4tan(a_a);
}

// fn asin_vec2(a: vec2) -> vec2 (src/main.mtek::asin_vec2)
function f_e2cab98b_asin_vec2(ctx, a_a) {
  return rt.v2asin(a_a);
}

// fn asin_vec3(a: vec3) -> vec3 (src/main.mtek::asin_vec3)
function f_e2cab98b_asin_vec3(ctx, a_a) {
  return rt.v3asin(a_a);
}

// fn asin_vec4(a: vec4) -> vec4 (src/main.mtek::asin_vec4)
function f_e2cab98b_asin_vec4(ctx, a_a) {
  return rt.v4asin(a_a);
}

// fn acos_vec2(a: vec2) -> vec2 (src/main.mtek::acos_vec2)
function f_e2cab98b_acos_vec2(ctx, a_a) {
  return rt.v2acos(a_a);
}

// fn acos_vec3(a: vec3) -> vec3 (src/main.mtek::acos_vec3)
function f_e2cab98b_acos_vec3(ctx, a_a) {
  return rt.v3acos(a_a);
}

// fn acos_vec4(a: vec4) -> vec4 (src/main.mtek::acos_vec4)
function f_e2cab98b_acos_vec4(ctx, a_a) {
  return rt.v4acos(a_a);
}

// fn atan_vec2(a: vec2) -> vec2 (src/main.mtek::atan_vec2)
function f_e2cab98b_atan_vec2(ctx, a_a) {
  return rt.v2atan(a_a);
}

// fn atan_vec3(a: vec3) -> vec3 (src/main.mtek::atan_vec3)
function f_e2cab98b_atan_vec3(ctx, a_a) {
  return rt.v3atan(a_a);
}

// fn atan_vec4(a: vec4) -> vec4 (src/main.mtek::atan_vec4)
function f_e2cab98b_atan_vec4(ctx, a_a) {
  return rt.v4atan(a_a);
}

// fn floor_vec2(a: vec2) -> vec2 (src/main.mtek::floor_vec2)
function f_e2cab98b_floor_vec2(ctx, a_a) {
  return rt.v2floor(a_a);
}

// fn floor_vec3(a: vec3) -> vec3 (src/main.mtek::floor_vec3)
function f_e2cab98b_floor_vec3(ctx, a_a) {
  return rt.v3floor(a_a);
}

// fn floor_vec4(a: vec4) -> vec4 (src/main.mtek::floor_vec4)
function f_e2cab98b_floor_vec4(ctx, a_a) {
  return rt.v4floor(a_a);
}

// fn ceil_vec2(a: vec2) -> vec2 (src/main.mtek::ceil_vec2)
function f_e2cab98b_ceil_vec2(ctx, a_a) {
  return rt.v2ceil(a_a);
}

// fn ceil_vec3(a: vec3) -> vec3 (src/main.mtek::ceil_vec3)
function f_e2cab98b_ceil_vec3(ctx, a_a) {
  return rt.v3ceil(a_a);
}

// fn ceil_vec4(a: vec4) -> vec4 (src/main.mtek::ceil_vec4)
function f_e2cab98b_ceil_vec4(ctx, a_a) {
  return rt.v4ceil(a_a);
}

// fn trunc_vec2(a: vec2) -> vec2 (src/main.mtek::trunc_vec2)
function f_e2cab98b_trunc_vec2(ctx, a_a) {
  return rt.v2trunc(a_a);
}

// fn trunc_vec3(a: vec3) -> vec3 (src/main.mtek::trunc_vec3)
function f_e2cab98b_trunc_vec3(ctx, a_a) {
  return rt.v3trunc(a_a);
}

// fn trunc_vec4(a: vec4) -> vec4 (src/main.mtek::trunc_vec4)
function f_e2cab98b_trunc_vec4(ctx, a_a) {
  return rt.v4trunc(a_a);
}

// fn fract_vec2(a: vec2) -> vec2 (src/main.mtek::fract_vec2)
function f_e2cab98b_fract_vec2(ctx, a_a) {
  return rt.v2fract(a_a);
}

// fn fract_vec3(a: vec3) -> vec3 (src/main.mtek::fract_vec3)
function f_e2cab98b_fract_vec3(ctx, a_a) {
  return rt.v3fract(a_a);
}

// fn fract_vec4(a: vec4) -> vec4 (src/main.mtek::fract_vec4)
function f_e2cab98b_fract_vec4(ctx, a_a) {
  return rt.v4fract(a_a);
}

// fn sign_vec2(a: vec2) -> vec2 (src/main.mtek::sign_vec2)
function f_e2cab98b_sign_vec2(ctx, a_a) {
  return rt.v2sign(a_a);
}

// fn sign_vec3(a: vec3) -> vec3 (src/main.mtek::sign_vec3)
function f_e2cab98b_sign_vec3(ctx, a_a) {
  return rt.v3sign(a_a);
}

// fn sign_vec4(a: vec4) -> vec4 (src/main.mtek::sign_vec4)
function f_e2cab98b_sign_vec4(ctx, a_a) {
  return rt.v4sign(a_a);
}

// fn round_vec2(a: vec2) -> vec2 (src/main.mtek::round_vec2)
function f_e2cab98b_round_vec2(ctx, a_a) {
  return rt.v2round(a_a);
}

// fn round_vec3(a: vec3) -> vec3 (src/main.mtek::round_vec3)
function f_e2cab98b_round_vec3(ctx, a_a) {
  return rt.v3round(a_a);
}

// fn round_vec4(a: vec4) -> vec4 (src/main.mtek::round_vec4)
function f_e2cab98b_round_vec4(ctx, a_a) {
  return rt.v4round(a_a);
}

// fn radians_vec2(a: vec2) -> vec2 (src/main.mtek::radians_vec2)
function f_e2cab98b_radians_vec2(ctx, a_a) {
  return rt.v2radians(a_a);
}

// fn radians_vec3(a: vec3) -> vec3 (src/main.mtek::radians_vec3)
function f_e2cab98b_radians_vec3(ctx, a_a) {
  return rt.v3radians(a_a);
}

// fn radians_vec4(a: vec4) -> vec4 (src/main.mtek::radians_vec4)
function f_e2cab98b_radians_vec4(ctx, a_a) {
  return rt.v4radians(a_a);
}

// fn degrees_vec2(a: vec2) -> vec2 (src/main.mtek::degrees_vec2)
function f_e2cab98b_degrees_vec2(ctx, a_a) {
  return rt.v2degrees(a_a);
}

// fn degrees_vec3(a: vec3) -> vec3 (src/main.mtek::degrees_vec3)
function f_e2cab98b_degrees_vec3(ctx, a_a) {
  return rt.v3degrees(a_a);
}

// fn degrees_vec4(a: vec4) -> vec4 (src/main.mtek::degrees_vec4)
function f_e2cab98b_degrees_vec4(ctx, a_a) {
  return rt.v4degrees(a_a);
}

// fn min_vec2_vec2(a: vec2, b: vec2) -> vec2 (src/main.mtek::min_vec2_vec2)
function f_e2cab98b_min_vec2_vec2(ctx, a_a, a_b) {
  return rt.v2min(a_a, a_b);
}

// fn min_vec3_vec3(a: vec3, b: vec3) -> vec3 (src/main.mtek::min_vec3_vec3)
function f_e2cab98b_min_vec3_vec3(ctx, a_a, a_b) {
  return rt.v3min(a_a, a_b);
}

// fn min_vec4_vec4(a: vec4, b: vec4) -> vec4 (src/main.mtek::min_vec4_vec4)
function f_e2cab98b_min_vec4_vec4(ctx, a_a, a_b) {
  return rt.v4min(a_a, a_b);
}

// fn max_vec2_vec2(a: vec2, b: vec2) -> vec2 (src/main.mtek::max_vec2_vec2)
function f_e2cab98b_max_vec2_vec2(ctx, a_a, a_b) {
  return rt.v2max(a_a, a_b);
}

// fn max_vec3_vec3(a: vec3, b: vec3) -> vec3 (src/main.mtek::max_vec3_vec3)
function f_e2cab98b_max_vec3_vec3(ctx, a_a, a_b) {
  return rt.v3max(a_a, a_b);
}

// fn max_vec4_vec4(a: vec4, b: vec4) -> vec4 (src/main.mtek::max_vec4_vec4)
function f_e2cab98b_max_vec4_vec4(ctx, a_a, a_b) {
  return rt.v4max(a_a, a_b);
}

// fn pow_vec2_vec2(a: vec2, b: vec2) -> vec2 (src/main.mtek::pow_vec2_vec2)
function f_e2cab98b_pow_vec2_vec2(ctx, a_a, a_b) {
  return rt.v2pow(a_a, a_b);
}

// fn pow_vec3_vec3(a: vec3, b: vec3) -> vec3 (src/main.mtek::pow_vec3_vec3)
function f_e2cab98b_pow_vec3_vec3(ctx, a_a, a_b) {
  return rt.v3pow(a_a, a_b);
}

// fn pow_vec4_vec4(a: vec4, b: vec4) -> vec4 (src/main.mtek::pow_vec4_vec4)
function f_e2cab98b_pow_vec4_vec4(ctx, a_a, a_b) {
  return rt.v4pow(a_a, a_b);
}

// fn atan2_vec2_vec2(a: vec2, b: vec2) -> vec2 (src/main.mtek::atan2_vec2_vec2)
function f_e2cab98b_atan2_vec2_vec2(ctx, a_a, a_b) {
  return rt.v2atan2(a_a, a_b);
}

// fn atan2_vec3_vec3(a: vec3, b: vec3) -> vec3 (src/main.mtek::atan2_vec3_vec3)
function f_e2cab98b_atan2_vec3_vec3(ctx, a_a, a_b) {
  return rt.v3atan2(a_a, a_b);
}

// fn atan2_vec4_vec4(a: vec4, b: vec4) -> vec4 (src/main.mtek::atan2_vec4_vec4)
function f_e2cab98b_atan2_vec4_vec4(ctx, a_a, a_b) {
  return rt.v4atan2(a_a, a_b);
}

// fn step_vec2_vec2(a: vec2, b: vec2) -> vec2 (src/main.mtek::step_vec2_vec2)
function f_e2cab98b_step_vec2_vec2(ctx, a_a, a_b) {
  return rt.v2step(a_a, a_b);
}

// fn step_vec3_vec3(a: vec3, b: vec3) -> vec3 (src/main.mtek::step_vec3_vec3)
function f_e2cab98b_step_vec3_vec3(ctx, a_a, a_b) {
  return rt.v3step(a_a, a_b);
}

// fn step_vec4_vec4(a: vec4, b: vec4) -> vec4 (src/main.mtek::step_vec4_vec4)
function f_e2cab98b_step_vec4_vec4(ctx, a_a, a_b) {
  return rt.v4step(a_a, a_b);
}

// fn clamp_vec2_vec2_vec2(a: vec2, b: vec2, c: vec2) -> vec2 (src/main.mtek::clamp_vec2_vec2_vec2)
function f_e2cab98b_clamp_vec2_vec2_vec2(ctx, a_a, a_b, a_c) {
  return rt.v2clamp(a_a, a_b, a_c);
}

// fn clamp_vec3_vec3_vec3(a: vec3, b: vec3, c: vec3) -> vec3 (src/main.mtek::clamp_vec3_vec3_vec3)
function f_e2cab98b_clamp_vec3_vec3_vec3(ctx, a_a, a_b, a_c) {
  return rt.v3clamp(a_a, a_b, a_c);
}

// fn clamp_vec4_vec4_vec4(a: vec4, b: vec4, c: vec4) -> vec4 (src/main.mtek::clamp_vec4_vec4_vec4)
function f_e2cab98b_clamp_vec4_vec4_vec4(ctx, a_a, a_b, a_c) {
  return rt.v4clamp(a_a, a_b, a_c);
}

// fn mix_vec2_vec2_vec2(a: vec2, b: vec2, c: vec2) -> vec2 (src/main.mtek::mix_vec2_vec2_vec2)
function f_e2cab98b_mix_vec2_vec2_vec2(ctx, a_a, a_b, a_c) {
  return rt.v2mix(a_a, a_b, a_c);
}

// fn mix_vec3_vec3_vec3(a: vec3, b: vec3, c: vec3) -> vec3 (src/main.mtek::mix_vec3_vec3_vec3)
function f_e2cab98b_mix_vec3_vec3_vec3(ctx, a_a, a_b, a_c) {
  return rt.v3mix(a_a, a_b, a_c);
}

// fn mix_vec4_vec4_vec4(a: vec4, b: vec4, c: vec4) -> vec4 (src/main.mtek::mix_vec4_vec4_vec4)
function f_e2cab98b_mix_vec4_vec4_vec4(ctx, a_a, a_b, a_c) {
  return rt.v4mix(a_a, a_b, a_c);
}

// fn smoothstep_vec2_vec2_vec2(a: vec2, b: vec2, c: vec2) -> vec2 (src/main.mtek::smoothstep_vec2_vec2_vec2)
function f_e2cab98b_smoothstep_vec2_vec2_vec2(ctx, a_a, a_b, a_c) {
  return rt.v2smoothstep(a_a, a_b, a_c);
}

// fn smoothstep_vec3_vec3_vec3(a: vec3, b: vec3, c: vec3) -> vec3 (src/main.mtek::smoothstep_vec3_vec3_vec3)
function f_e2cab98b_smoothstep_vec3_vec3_vec3(ctx, a_a, a_b, a_c) {
  return rt.v3smoothstep(a_a, a_b, a_c);
}

// fn smoothstep_vec4_vec4_vec4(a: vec4, b: vec4, c: vec4) -> vec4 (src/main.mtek::smoothstep_vec4_vec4_vec4)
function f_e2cab98b_smoothstep_vec4_vec4_vec4(ctx, a_a, a_b, a_c) {
  return rt.v4smoothstep(a_a, a_b, a_c);
}

// fn mix_vec2_vec2_f32(a: vec2, b: vec2, c: f32) -> vec2 (src/main.mtek::mix_vec2_vec2_f32)
function f_e2cab98b_mix_vec2_vec2_f32(ctx, a_a, a_b, a_c) {
  return rt.v2mixs(a_a, a_b, a_c);
}

// fn mix_vec3_vec3_f32(a: vec3, b: vec3, c: f32) -> vec3 (src/main.mtek::mix_vec3_vec3_f32)
function f_e2cab98b_mix_vec3_vec3_f32(ctx, a_a, a_b, a_c) {
  return rt.v3mixs(a_a, a_b, a_c);
}

// fn mix_vec4_vec4_f32(a: vec4, b: vec4, c: f32) -> vec4 (src/main.mtek::mix_vec4_vec4_f32)
function f_e2cab98b_mix_vec4_vec4_f32(ctx, a_a, a_b, a_c) {
  return rt.v4mixs(a_a, a_b, a_c);
}

// fn add_vec2_vec2(a: vec2, b: vec2) -> vec2 (src/main.mtek::add_vec2_vec2)
function f_e2cab98b_add_vec2_vec2(ctx, a_a, a_b) {
  return rt.v2add(a_a, a_b);
}

// fn sub_vec2_vec2(a: vec2, b: vec2) -> vec2 (src/main.mtek::sub_vec2_vec2)
function f_e2cab98b_sub_vec2_vec2(ctx, a_a, a_b) {
  return rt.v2sub(a_a, a_b);
}

// fn mul_vec2_vec2(a: vec2, b: vec2) -> vec2 (src/main.mtek::mul_vec2_vec2)
function f_e2cab98b_mul_vec2_vec2(ctx, a_a, a_b) {
  return rt.v2mul(a_a, a_b);
}

// fn div_vec2_vec2(a: vec2, b: vec2) -> vec2 (src/main.mtek::div_vec2_vec2)
function f_e2cab98b_div_vec2_vec2(ctx, a_a, a_b) {
  return rt.v2div(a_a, a_b);
}

// fn mul_vec2_f32(a: vec2, b: f32) -> vec2 (src/main.mtek::mul_vec2_f32)
function f_e2cab98b_mul_vec2_f32(ctx, a_a, a_b) {
  return rt.v2scale(a_a, a_b);
}

// fn mul_f32_vec2(a: f32, b: vec2) -> vec2 (src/main.mtek::mul_f32_vec2)
function f_e2cab98b_mul_f32_vec2(ctx, a_a, a_b) {
  return rt.v2smul(a_a, a_b);
}

// fn div_vec2_f32(a: vec2, b: f32) -> vec2 (src/main.mtek::div_vec2_f32)
function f_e2cab98b_div_vec2_f32(ctx, a_a, a_b) {
  return rt.v2divs(a_a, a_b);
}

// fn neg_vec2(a: vec2) -> vec2 (src/main.mtek::neg_vec2)
function f_e2cab98b_neg_vec2(ctx, a_a) {
  return rt.v2neg(a_a);
}

// fn dot_vec2_vec2(a: vec2, b: vec2) -> f32 (src/main.mtek::dot_vec2_vec2)
function f_e2cab98b_dot_vec2_vec2(ctx, a_a, a_b) {
  return rt.v2dot(a_a, a_b);
}

// fn length_vec2(a: vec2) -> f32 (src/main.mtek::length_vec2)
function f_e2cab98b_length_vec2(ctx, a_a) {
  return rt.v2length(a_a);
}

// fn distance_vec2_vec2(a: vec2, b: vec2) -> f32 (src/main.mtek::distance_vec2_vec2)
function f_e2cab98b_distance_vec2_vec2(ctx, a_a, a_b) {
  return rt.v2distance(a_a, a_b);
}

// fn normalize_vec2(a: vec2) -> vec2 (src/main.mtek::normalize_vec2)
function f_e2cab98b_normalize_vec2(ctx, a_a) {
  return rt.v2normalize(a_a);
}

// fn reflect_vec2_vec2(a: vec2, b: vec2) -> vec2 (src/main.mtek::reflect_vec2_vec2)
function f_e2cab98b_reflect_vec2_vec2(ctx, a_a, a_b) {
  return rt.v2reflect(a_a, a_b);
}

// fn add_vec3_vec3(a: vec3, b: vec3) -> vec3 (src/main.mtek::add_vec3_vec3)
function f_e2cab98b_add_vec3_vec3(ctx, a_a, a_b) {
  return rt.v3add(a_a, a_b);
}

// fn sub_vec3_vec3(a: vec3, b: vec3) -> vec3 (src/main.mtek::sub_vec3_vec3)
function f_e2cab98b_sub_vec3_vec3(ctx, a_a, a_b) {
  return rt.v3sub(a_a, a_b);
}

// fn mul_vec3_vec3(a: vec3, b: vec3) -> vec3 (src/main.mtek::mul_vec3_vec3)
function f_e2cab98b_mul_vec3_vec3(ctx, a_a, a_b) {
  return rt.v3mul(a_a, a_b);
}

// fn div_vec3_vec3(a: vec3, b: vec3) -> vec3 (src/main.mtek::div_vec3_vec3)
function f_e2cab98b_div_vec3_vec3(ctx, a_a, a_b) {
  return rt.v3div(a_a, a_b);
}

// fn mul_vec3_f32(a: vec3, b: f32) -> vec3 (src/main.mtek::mul_vec3_f32)
function f_e2cab98b_mul_vec3_f32(ctx, a_a, a_b) {
  return rt.v3scale(a_a, a_b);
}

// fn mul_f32_vec3(a: f32, b: vec3) -> vec3 (src/main.mtek::mul_f32_vec3)
function f_e2cab98b_mul_f32_vec3(ctx, a_a, a_b) {
  return rt.v3smul(a_a, a_b);
}

// fn div_vec3_f32(a: vec3, b: f32) -> vec3 (src/main.mtek::div_vec3_f32)
function f_e2cab98b_div_vec3_f32(ctx, a_a, a_b) {
  return rt.v3divs(a_a, a_b);
}

// fn neg_vec3(a: vec3) -> vec3 (src/main.mtek::neg_vec3)
function f_e2cab98b_neg_vec3(ctx, a_a) {
  return rt.v3neg(a_a);
}

// fn dot_vec3_vec3(a: vec3, b: vec3) -> f32 (src/main.mtek::dot_vec3_vec3)
function f_e2cab98b_dot_vec3_vec3(ctx, a_a, a_b) {
  return rt.v3dot(a_a, a_b);
}

// fn length_vec3(a: vec3) -> f32 (src/main.mtek::length_vec3)
function f_e2cab98b_length_vec3(ctx, a_a) {
  return rt.v3length(a_a);
}

// fn distance_vec3_vec3(a: vec3, b: vec3) -> f32 (src/main.mtek::distance_vec3_vec3)
function f_e2cab98b_distance_vec3_vec3(ctx, a_a, a_b) {
  return rt.v3distance(a_a, a_b);
}

// fn normalize_vec3(a: vec3) -> vec3 (src/main.mtek::normalize_vec3)
function f_e2cab98b_normalize_vec3(ctx, a_a) {
  return rt.v3normalize(a_a);
}

// fn reflect_vec3_vec3(a: vec3, b: vec3) -> vec3 (src/main.mtek::reflect_vec3_vec3)
function f_e2cab98b_reflect_vec3_vec3(ctx, a_a, a_b) {
  return rt.v3reflect(a_a, a_b);
}

// fn add_vec4_vec4(a: vec4, b: vec4) -> vec4 (src/main.mtek::add_vec4_vec4)
function f_e2cab98b_add_vec4_vec4(ctx, a_a, a_b) {
  return rt.v4add(a_a, a_b);
}

// fn sub_vec4_vec4(a: vec4, b: vec4) -> vec4 (src/main.mtek::sub_vec4_vec4)
function f_e2cab98b_sub_vec4_vec4(ctx, a_a, a_b) {
  return rt.v4sub(a_a, a_b);
}

// fn mul_vec4_vec4(a: vec4, b: vec4) -> vec4 (src/main.mtek::mul_vec4_vec4)
function f_e2cab98b_mul_vec4_vec4(ctx, a_a, a_b) {
  return rt.v4mul(a_a, a_b);
}

// fn div_vec4_vec4(a: vec4, b: vec4) -> vec4 (src/main.mtek::div_vec4_vec4)
function f_e2cab98b_div_vec4_vec4(ctx, a_a, a_b) {
  return rt.v4div(a_a, a_b);
}

// fn mul_vec4_f32(a: vec4, b: f32) -> vec4 (src/main.mtek::mul_vec4_f32)
function f_e2cab98b_mul_vec4_f32(ctx, a_a, a_b) {
  return rt.v4scale(a_a, a_b);
}

// fn mul_f32_vec4(a: f32, b: vec4) -> vec4 (src/main.mtek::mul_f32_vec4)
function f_e2cab98b_mul_f32_vec4(ctx, a_a, a_b) {
  return rt.v4smul(a_a, a_b);
}

// fn div_vec4_f32(a: vec4, b: f32) -> vec4 (src/main.mtek::div_vec4_f32)
function f_e2cab98b_div_vec4_f32(ctx, a_a, a_b) {
  return rt.v4divs(a_a, a_b);
}

// fn neg_vec4(a: vec4) -> vec4 (src/main.mtek::neg_vec4)
function f_e2cab98b_neg_vec4(ctx, a_a) {
  return rt.v4neg(a_a);
}

// fn dot_vec4_vec4(a: vec4, b: vec4) -> f32 (src/main.mtek::dot_vec4_vec4)
function f_e2cab98b_dot_vec4_vec4(ctx, a_a, a_b) {
  return rt.v4dot(a_a, a_b);
}

// fn length_vec4(a: vec4) -> f32 (src/main.mtek::length_vec4)
function f_e2cab98b_length_vec4(ctx, a_a) {
  return rt.v4length(a_a);
}

// fn distance_vec4_vec4(a: vec4, b: vec4) -> f32 (src/main.mtek::distance_vec4_vec4)
function f_e2cab98b_distance_vec4_vec4(ctx, a_a, a_b) {
  return rt.v4distance(a_a, a_b);
}

// fn normalize_vec4(a: vec4) -> vec4 (src/main.mtek::normalize_vec4)
function f_e2cab98b_normalize_vec4(ctx, a_a) {
  return rt.v4normalize(a_a);
}

// fn reflect_vec4_vec4(a: vec4, b: vec4) -> vec4 (src/main.mtek::reflect_vec4_vec4)
function f_e2cab98b_reflect_vec4_vec4(ctx, a_a, a_b) {
  return rt.v4reflect(a_a, a_b);
}

// fn cross_vec3_vec3(a: vec3, b: vec3) -> vec3 (src/main.mtek::cross_vec3_vec3)
function f_e2cab98b_cross_vec3_vec3(ctx, a_a, a_b) {
  return rt.v3cross(a_a, a_b);
}

// fn make_vec2_f32_f32(a: f32, b: f32) -> vec2 (src/main.mtek::make_vec2_f32_f32)
function f_e2cab98b_make_vec2_f32_f32(ctx, a_a, a_b) {
  return rt.v2(a_a, a_b);
}

// fn make_vec2_f32(a: f32) -> vec2 (src/main.mtek::make_vec2_f32)
function f_e2cab98b_make_vec2_f32(ctx, a_a) {
  return rt.v2splat(a_a);
}

// fn make_vec3_f32_f32_f32(a: f32, b: f32, c: f32) -> vec3 (src/main.mtek::make_vec3_f32_f32_f32)
function f_e2cab98b_make_vec3_f32_f32_f32(ctx, a_a, a_b, a_c) {
  return rt.v3(a_a, a_b, a_c);
}

// fn make_vec3_f32(a: f32) -> vec3 (src/main.mtek::make_vec3_f32)
function f_e2cab98b_make_vec3_f32(ctx, a_a) {
  return rt.v3splat(a_a);
}

// fn make_vec3_vec2_f32(a: vec2, b: f32) -> vec3 (src/main.mtek::make_vec3_vec2_f32)
function f_e2cab98b_make_vec3_vec2_f32(ctx, a_a, a_b) {
  return rt.v3fromV2(a_a, a_b);
}

// fn make_vec4_f32_f32_f32_f32(a: f32, b: f32, c: f32, d: f32) -> vec4 (src/main.mtek::make_vec4_f32_f32_f32_f32)
function f_e2cab98b_make_vec4_f32_f32_f32_f32(ctx, a_a, a_b, a_c, a_d) {
  return rt.v4(a_a, a_b, a_c, a_d);
}

// fn make_vec4_f32(a: f32) -> vec4 (src/main.mtek::make_vec4_f32)
function f_e2cab98b_make_vec4_f32(ctx, a_a) {
  return rt.v4splat(a_a);
}

// fn make_vec4_vec3_f32(a: vec3, b: f32) -> vec4 (src/main.mtek::make_vec4_vec3_f32)
function f_e2cab98b_make_vec4_vec3_f32(ctx, a_a, a_b) {
  return rt.v4fromV3(a_a, a_b);
}

// fn make_vec4_vec2_f32_f32(a: vec2, b: f32, c: f32) -> vec4 (src/main.mtek::make_vec4_vec2_f32_f32)
function f_e2cab98b_make_vec4_vec2_f32_f32(ctx, a_a, a_b, a_c) {
  return rt.v4fromV2(a_a, a_b, a_c);
}

// fn quat_identity() -> quat (src/main.mtek::quat_identity)
function f_e2cab98b_quat_identity(ctx) {
  return { x: 0.0, y: 0.0, z: 0.0, w: 1.0 };
}

// fn quat_axis_angle_vec3_f32(a: vec3, b: f32) -> quat (src/main.mtek::quat_axis_angle_vec3_f32)
function f_e2cab98b_quat_axis_angle_vec3_f32(ctx, a_a, a_b) {
  return rt.qaxisAngle(a_a, a_b);
}

// fn quat_euler_f32_f32_f32(a: f32, b: f32, c: f32) -> quat (src/main.mtek::quat_euler_f32_f32_f32)
function f_e2cab98b_quat_euler_f32_f32_f32(ctx, a_a, a_b, a_c) {
  return rt.qeuler(a_a, a_b, a_c);
}

// fn mul_quat_quat(a: quat, b: quat) -> quat (src/main.mtek::mul_quat_quat)
function f_e2cab98b_mul_quat_quat(ctx, a_a, a_b) {
  return rt.qmul(a_a, a_b);
}

// fn mul_quat_vec3(a: quat, b: vec3) -> vec3 (src/main.mtek::mul_quat_vec3)
function f_e2cab98b_mul_quat_vec3(ctx, a_a, a_b) {
  return rt.qrotate(a_a, a_b);
}

// fn mat4_identity() -> mat4 (src/main.mtek::mat4_identity)
function f_e2cab98b_mat4_identity(ctx) {
  return new Float32Array([1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]);
}

// fn mat4_translation_vec3(a: vec3) -> mat4 (src/main.mtek::mat4_translation_vec3)
function f_e2cab98b_mat4_translation_vec3(ctx, a_a) {
  return rt.m4translation(a_a);
}

// fn mat4_scale_vec3(a: vec3) -> mat4 (src/main.mtek::mat4_scale_vec3)
function f_e2cab98b_mat4_scale_vec3(ctx, a_a) {
  return rt.m4scale(a_a);
}

// fn mat4_rotation_quat(a: quat) -> mat4 (src/main.mtek::mat4_rotation_quat)
function f_e2cab98b_mat4_rotation_quat(ctx, a_a) {
  return rt.m4rotation(a_a);
}

// fn mat4_columns_vec4_vec4_vec4_vec4(a: vec4, b: vec4, c: vec4, d: vec4) -> mat4 (src/main.mtek::mat4_columns_vec4_vec4_vec4_vec4)
function f_e2cab98b_mat4_columns_vec4_vec4_vec4_vec4(ctx, a_a, a_b, a_c, a_d) {
  return rt.m4columns(a_a, a_b, a_c, a_d);
}

// fn mul_mat4_mat4(a: mat4, b: mat4) -> mat4 (src/main.mtek::mul_mat4_mat4)
function f_e2cab98b_mul_mat4_mat4(ctx, a_a, a_b) {
  return rt.m4mul(a_a, a_b);
}

// fn mul_mat4_vec4(a: mat4, b: vec4) -> vec4 (src/main.mtek::mul_mat4_vec4)
function f_e2cab98b_mul_mat4_vec4(ctx, a_a, a_b) {
  return rt.m4mulv(a_a, a_b);
}

// fn transpose_mat4(a: mat4) -> mat4 (src/main.mtek::transpose_mat4)
function f_e2cab98b_transpose_mat4(ctx, a_a) {
  return rt.m4transpose(a_a);
}

// fn color_linear_vec3_f32(a: vec3, b: f32) -> color (src/main.mtek::color_linear_vec3_f32)
function f_e2cab98b_color_linear_vec3_f32(ctx, a_a, a_b) {
  return rt.clinear(a_a, a_b);
}

// fn color_srgb_vec3_f32(a: vec3, b: f32) -> color (src/main.mtek::color_srgb_vec3_f32)
function f_e2cab98b_color_srgb_vec3_f32(ctx, a_a, a_b) {
  return rt.csrgb(a_a, a_b);
}

// cpu fn reach_all() (src/main.mtek::reach_all)
function f_e2cab98b_reach_all(ctx) {
  f_e2cab98b_add_f32_f32(ctx, 0.0, 0.0);
  f_e2cab98b_sub_f32_f32(ctx, 0.0, 0.0);
  f_e2cab98b_mul_f32_f32(ctx, 0.0, 0.0);
  f_e2cab98b_div_f32_f32(ctx, 0.0, 0.0);
  f_e2cab98b_rem_f32_f32(ctx, 0.0, 0.0);
  f_e2cab98b_neg_f32(ctx, 0.0);
  f_e2cab98b_lt_f32_f32(ctx, 0.0, 0.0);
  f_e2cab98b_lt_i32_i32(ctx, 0, 0);
  f_e2cab98b_lt_u32_u32(ctx, 0, 0);
  f_e2cab98b_le_f32_f32(ctx, 0.0, 0.0);
  f_e2cab98b_le_i32_i32(ctx, 0, 0);
  f_e2cab98b_le_u32_u32(ctx, 0, 0);
  f_e2cab98b_gt_f32_f32(ctx, 0.0, 0.0);
  f_e2cab98b_gt_i32_i32(ctx, 0, 0);
  f_e2cab98b_gt_u32_u32(ctx, 0, 0);
  f_e2cab98b_ge_f32_f32(ctx, 0.0, 0.0);
  f_e2cab98b_ge_i32_i32(ctx, 0, 0);
  f_e2cab98b_ge_u32_u32(ctx, 0, 0);
  f_e2cab98b_eq_f32_f32(ctx, 0.0, 0.0);
  f_e2cab98b_eq_i32_i32(ctx, 0, 0);
  f_e2cab98b_eq_u32_u32(ctx, 0, 0);
  f_e2cab98b_ne_f32_f32(ctx, 0.0, 0.0);
  f_e2cab98b_ne_i32_i32(ctx, 0, 0);
  f_e2cab98b_ne_u32_u32(ctx, 0, 0);
  f_e2cab98b_add_i32_i32(ctx, 0, 0);
  f_e2cab98b_sub_i32_i32(ctx, 0, 0);
  f_e2cab98b_mul_i32_i32(ctx, 0, 0);
  f_e2cab98b_div_i32_i32(ctx, 0, 0);
  f_e2cab98b_rem_i32_i32(ctx, 0, 0);
  f_e2cab98b_neg_i32(ctx, 0);
  f_e2cab98b_add_u32_u32(ctx, 0, 0);
  f_e2cab98b_sub_u32_u32(ctx, 0, 0);
  f_e2cab98b_mul_u32_u32(ctx, 0, 0);
  f_e2cab98b_div_u32_u32(ctx, 0, 0);
  f_e2cab98b_rem_u32_u32(ctx, 0, 0);
  f_e2cab98b_to_i32_f32(ctx, 0.0);
  f_e2cab98b_to_u32_f32(ctx, 0.0);
  f_e2cab98b_to_f32_i32(ctx, 0);
  f_e2cab98b_to_f32_u32(ctx, 0);
  f_e2cab98b_to_i32_u32(ctx, 0);
  f_e2cab98b_to_u32_i32(ctx, 0);
  f_e2cab98b_abs_f32(ctx, 0.0);
  f_e2cab98b_saturate_f32(ctx, 0.0);
  f_e2cab98b_sqrt_f32(ctx, 0.0);
  f_e2cab98b_inverse_sqrt_f32(ctx, 0.0);
  f_e2cab98b_exp_f32(ctx, 0.0);
  f_e2cab98b_exp2_f32(ctx, 0.0);
  f_e2cab98b_log_f32(ctx, 0.0);
  f_e2cab98b_log2_f32(ctx, 0.0);
  f_e2cab98b_sin_f32(ctx, 0.0);
  f_e2cab98b_cos_f32(ctx, 0.0);
  f_e2cab98b_tan_f32(ctx, 0.0);
  f_e2cab98b_asin_f32(ctx, 0.0);
  f_e2cab98b_acos_f32(ctx, 0.0);
  f_e2cab98b_atan_f32(ctx, 0.0);
  f_e2cab98b_floor_f32(ctx, 0.0);
  f_e2cab98b_ceil_f32(ctx, 0.0);
  f_e2cab98b_trunc_f32(ctx, 0.0);
  f_e2cab98b_fract_f32(ctx, 0.0);
  f_e2cab98b_sign_f32(ctx, 0.0);
  f_e2cab98b_round_f32(ctx, 0.0);
  f_e2cab98b_radians_f32(ctx, 0.0);
  f_e2cab98b_degrees_f32(ctx, 0.0);
  f_e2cab98b_length_f32(ctx, 0.0);
  f_e2cab98b_distance_f32_f32(ctx, 0.0, 0.0);
  f_e2cab98b_min_f32_f32(ctx, 0.0, 0.0);
  f_e2cab98b_max_f32_f32(ctx, 0.0, 0.0);
  f_e2cab98b_pow_f32_f32(ctx, 0.0, 0.0);
  f_e2cab98b_atan2_f32_f32(ctx, 0.0, 0.0);
  f_e2cab98b_step_f32_f32(ctx, 0.0, 0.0);
  f_e2cab98b_clamp_f32_f32_f32(ctx, 0.0, 0.0, 0.0);
  f_e2cab98b_mix_f32_f32_f32(ctx, 0.0, 0.0, 0.0);
  f_e2cab98b_smoothstep_f32_f32_f32(ctx, 0.0, 0.0, 0.0);
  f_e2cab98b_abs_i32(ctx, 0);
  f_e2cab98b_abs_u32(ctx, 0);
  f_e2cab98b_min_i32_i32(ctx, 0, 0);
  f_e2cab98b_max_i32_i32(ctx, 0, 0);
  f_e2cab98b_min_u32_u32(ctx, 0, 0);
  f_e2cab98b_max_u32_u32(ctx, 0, 0);
  f_e2cab98b_clamp_i32_i32_i32(ctx, 0, 0, 0);
  f_e2cab98b_clamp_u32_u32_u32(ctx, 0, 0, 0);
  f_e2cab98b_abs_vec2(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_abs_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_abs_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_saturate_vec2(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_saturate_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_saturate_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_sqrt_vec2(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_sqrt_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_sqrt_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_inverse_sqrt_vec2(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_inverse_sqrt_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_inverse_sqrt_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_exp_vec2(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_exp_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_exp_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_exp2_vec2(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_exp2_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_exp2_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_log_vec2(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_log_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_log_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_log2_vec2(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_log2_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_log2_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_sin_vec2(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_sin_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_sin_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_cos_vec2(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_cos_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_cos_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_tan_vec2(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_tan_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_tan_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_asin_vec2(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_asin_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_asin_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_acos_vec2(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_acos_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_acos_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_atan_vec2(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_atan_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_atan_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_floor_vec2(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_floor_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_floor_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_ceil_vec2(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_ceil_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_ceil_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_trunc_vec2(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_trunc_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_trunc_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_fract_vec2(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_fract_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_fract_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_sign_vec2(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_sign_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_sign_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_round_vec2(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_round_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_round_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_radians_vec2(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_radians_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_radians_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_degrees_vec2(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_degrees_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_degrees_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_min_vec2_vec2(ctx, { x: 0.0, y: 0.0 }, { x: 0.0, y: 0.0 });
  f_e2cab98b_min_vec3_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 }, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_min_vec4_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_max_vec2_vec2(ctx, { x: 0.0, y: 0.0 }, { x: 0.0, y: 0.0 });
  f_e2cab98b_max_vec3_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 }, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_max_vec4_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_pow_vec2_vec2(ctx, { x: 0.0, y: 0.0 }, { x: 0.0, y: 0.0 });
  f_e2cab98b_pow_vec3_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 }, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_pow_vec4_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_atan2_vec2_vec2(ctx, { x: 0.0, y: 0.0 }, { x: 0.0, y: 0.0 });
  f_e2cab98b_atan2_vec3_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 }, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_atan2_vec4_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_step_vec2_vec2(ctx, { x: 0.0, y: 0.0 }, { x: 0.0, y: 0.0 });
  f_e2cab98b_step_vec3_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 }, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_step_vec4_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_clamp_vec2_vec2_vec2(ctx, { x: 0.0, y: 0.0 }, { x: 0.0, y: 0.0 }, { x: 0.0, y: 0.0 });
  f_e2cab98b_clamp_vec3_vec3_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 }, { x: 0.0, y: 0.0, z: 0.0 }, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_clamp_vec4_vec4_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_mix_vec2_vec2_vec2(ctx, { x: 0.0, y: 0.0 }, { x: 0.0, y: 0.0 }, { x: 0.0, y: 0.0 });
  f_e2cab98b_mix_vec3_vec3_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 }, { x: 0.0, y: 0.0, z: 0.0 }, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_mix_vec4_vec4_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_smoothstep_vec2_vec2_vec2(ctx, { x: 0.0, y: 0.0 }, { x: 0.0, y: 0.0 }, { x: 0.0, y: 0.0 });
  f_e2cab98b_smoothstep_vec3_vec3_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 }, { x: 0.0, y: 0.0, z: 0.0 }, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_smoothstep_vec4_vec4_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_mix_vec2_vec2_f32(ctx, { x: 0.0, y: 0.0 }, { x: 0.0, y: 0.0 }, 0.0);
  f_e2cab98b_mix_vec3_vec3_f32(ctx, { x: 0.0, y: 0.0, z: 0.0 }, { x: 0.0, y: 0.0, z: 0.0 }, 0.0);
  f_e2cab98b_mix_vec4_vec4_f32(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }, 0.0);
  f_e2cab98b_add_vec2_vec2(ctx, { x: 0.0, y: 0.0 }, { x: 0.0, y: 0.0 });
  f_e2cab98b_sub_vec2_vec2(ctx, { x: 0.0, y: 0.0 }, { x: 0.0, y: 0.0 });
  f_e2cab98b_mul_vec2_vec2(ctx, { x: 0.0, y: 0.0 }, { x: 0.0, y: 0.0 });
  f_e2cab98b_div_vec2_vec2(ctx, { x: 0.0, y: 0.0 }, { x: 0.0, y: 0.0 });
  f_e2cab98b_mul_vec2_f32(ctx, { x: 0.0, y: 0.0 }, 0.0);
  f_e2cab98b_mul_f32_vec2(ctx, 0.0, { x: 0.0, y: 0.0 });
  f_e2cab98b_div_vec2_f32(ctx, { x: 0.0, y: 0.0 }, 0.0);
  f_e2cab98b_neg_vec2(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_dot_vec2_vec2(ctx, { x: 0.0, y: 0.0 }, { x: 0.0, y: 0.0 });
  f_e2cab98b_length_vec2(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_distance_vec2_vec2(ctx, { x: 0.0, y: 0.0 }, { x: 0.0, y: 0.0 });
  f_e2cab98b_normalize_vec2(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_reflect_vec2_vec2(ctx, { x: 0.0, y: 0.0 }, { x: 0.0, y: 0.0 });
  f_e2cab98b_add_vec3_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 }, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_sub_vec3_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 }, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_mul_vec3_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 }, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_div_vec3_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 }, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_mul_vec3_f32(ctx, { x: 0.0, y: 0.0, z: 0.0 }, 0.0);
  f_e2cab98b_mul_f32_vec3(ctx, 0.0, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_div_vec3_f32(ctx, { x: 0.0, y: 0.0, z: 0.0 }, 0.0);
  f_e2cab98b_neg_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_dot_vec3_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 }, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_length_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_distance_vec3_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 }, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_normalize_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_reflect_vec3_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 }, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_add_vec4_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_sub_vec4_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_mul_vec4_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_div_vec4_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_mul_vec4_f32(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }, 0.0);
  f_e2cab98b_mul_f32_vec4(ctx, 0.0, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_div_vec4_f32(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }, 0.0);
  f_e2cab98b_neg_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_dot_vec4_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_length_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_distance_vec4_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_normalize_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_reflect_vec4_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_cross_vec3_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 }, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_make_vec2_f32_f32(ctx, 0.0, 0.0);
  f_e2cab98b_make_vec2_f32(ctx, 0.0);
  f_e2cab98b_make_vec3_f32_f32_f32(ctx, 0.0, 0.0, 0.0);
  f_e2cab98b_make_vec3_f32(ctx, 0.0);
  f_e2cab98b_make_vec3_vec2_f32(ctx, { x: 0.0, y: 0.0 }, 0.0);
  f_e2cab98b_make_vec4_f32_f32_f32_f32(ctx, 0.0, 0.0, 0.0, 0.0);
  f_e2cab98b_make_vec4_f32(ctx, 0.0);
  f_e2cab98b_make_vec4_vec3_f32(ctx, { x: 0.0, y: 0.0, z: 0.0 }, 0.0);
  f_e2cab98b_make_vec4_vec2_f32_f32(ctx, { x: 0.0, y: 0.0 }, 0.0, 0.0);
  f_e2cab98b_quat_identity(ctx);
  f_e2cab98b_quat_axis_angle_vec3_f32(ctx, { x: 0.0, y: 0.0, z: 0.0 }, 0.0);
  f_e2cab98b_quat_euler_f32_f32_f32(ctx, 0.0, 0.0, 0.0);
  f_e2cab98b_mul_quat_quat(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 1.0 }, { x: 0.0, y: 0.0, z: 0.0, w: 1.0 });
  f_e2cab98b_mul_quat_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 1.0 }, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_mat4_identity(ctx);
  f_e2cab98b_mat4_translation_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_mat4_scale_vec3(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_mat4_rotation_quat(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 1.0 });
  f_e2cab98b_mat4_columns_vec4_vec4_vec4_vec4(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 }, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_mul_mat4_mat4(ctx, new Float32Array([1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]), new Float32Array([1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]));
  f_e2cab98b_mul_mat4_vec4(ctx, new Float32Array([1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]), { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_transpose_mat4(ctx, new Float32Array([1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]));
  f_e2cab98b_color_linear_vec3_f32(ctx, { x: 0.0, y: 0.0, z: 0.0 }, 0.0);
  f_e2cab98b_color_srgb_vec3_f32(ctx, { x: 0.0, y: 0.0, z: 0.0 }, 0.0);
}

export const functions = {
  "src/main.mtek::add_f32_f32": f_e2cab98b_add_f32_f32,
  "src/main.mtek::sub_f32_f32": f_e2cab98b_sub_f32_f32,
  "src/main.mtek::mul_f32_f32": f_e2cab98b_mul_f32_f32,
  "src/main.mtek::div_f32_f32": f_e2cab98b_div_f32_f32,
  "src/main.mtek::rem_f32_f32": f_e2cab98b_rem_f32_f32,
  "src/main.mtek::neg_f32": f_e2cab98b_neg_f32,
  "src/main.mtek::lt_f32_f32": f_e2cab98b_lt_f32_f32,
  "src/main.mtek::lt_i32_i32": f_e2cab98b_lt_i32_i32,
  "src/main.mtek::lt_u32_u32": f_e2cab98b_lt_u32_u32,
  "src/main.mtek::le_f32_f32": f_e2cab98b_le_f32_f32,
  "src/main.mtek::le_i32_i32": f_e2cab98b_le_i32_i32,
  "src/main.mtek::le_u32_u32": f_e2cab98b_le_u32_u32,
  "src/main.mtek::gt_f32_f32": f_e2cab98b_gt_f32_f32,
  "src/main.mtek::gt_i32_i32": f_e2cab98b_gt_i32_i32,
  "src/main.mtek::gt_u32_u32": f_e2cab98b_gt_u32_u32,
  "src/main.mtek::ge_f32_f32": f_e2cab98b_ge_f32_f32,
  "src/main.mtek::ge_i32_i32": f_e2cab98b_ge_i32_i32,
  "src/main.mtek::ge_u32_u32": f_e2cab98b_ge_u32_u32,
  "src/main.mtek::eq_f32_f32": f_e2cab98b_eq_f32_f32,
  "src/main.mtek::eq_i32_i32": f_e2cab98b_eq_i32_i32,
  "src/main.mtek::eq_u32_u32": f_e2cab98b_eq_u32_u32,
  "src/main.mtek::ne_f32_f32": f_e2cab98b_ne_f32_f32,
  "src/main.mtek::ne_i32_i32": f_e2cab98b_ne_i32_i32,
  "src/main.mtek::ne_u32_u32": f_e2cab98b_ne_u32_u32,
  "src/main.mtek::add_i32_i32": f_e2cab98b_add_i32_i32,
  "src/main.mtek::sub_i32_i32": f_e2cab98b_sub_i32_i32,
  "src/main.mtek::mul_i32_i32": f_e2cab98b_mul_i32_i32,
  "src/main.mtek::div_i32_i32": f_e2cab98b_div_i32_i32,
  "src/main.mtek::rem_i32_i32": f_e2cab98b_rem_i32_i32,
  "src/main.mtek::neg_i32": f_e2cab98b_neg_i32,
  "src/main.mtek::add_u32_u32": f_e2cab98b_add_u32_u32,
  "src/main.mtek::sub_u32_u32": f_e2cab98b_sub_u32_u32,
  "src/main.mtek::mul_u32_u32": f_e2cab98b_mul_u32_u32,
  "src/main.mtek::div_u32_u32": f_e2cab98b_div_u32_u32,
  "src/main.mtek::rem_u32_u32": f_e2cab98b_rem_u32_u32,
  "src/main.mtek::to_i32_f32": f_e2cab98b_to_i32_f32,
  "src/main.mtek::to_u32_f32": f_e2cab98b_to_u32_f32,
  "src/main.mtek::to_f32_i32": f_e2cab98b_to_f32_i32,
  "src/main.mtek::to_f32_u32": f_e2cab98b_to_f32_u32,
  "src/main.mtek::to_i32_u32": f_e2cab98b_to_i32_u32,
  "src/main.mtek::to_u32_i32": f_e2cab98b_to_u32_i32,
  "src/main.mtek::abs_f32": f_e2cab98b_abs_f32,
  "src/main.mtek::saturate_f32": f_e2cab98b_saturate_f32,
  "src/main.mtek::sqrt_f32": f_e2cab98b_sqrt_f32,
  "src/main.mtek::inverse_sqrt_f32": f_e2cab98b_inverse_sqrt_f32,
  "src/main.mtek::exp_f32": f_e2cab98b_exp_f32,
  "src/main.mtek::exp2_f32": f_e2cab98b_exp2_f32,
  "src/main.mtek::log_f32": f_e2cab98b_log_f32,
  "src/main.mtek::log2_f32": f_e2cab98b_log2_f32,
  "src/main.mtek::sin_f32": f_e2cab98b_sin_f32,
  "src/main.mtek::cos_f32": f_e2cab98b_cos_f32,
  "src/main.mtek::tan_f32": f_e2cab98b_tan_f32,
  "src/main.mtek::asin_f32": f_e2cab98b_asin_f32,
  "src/main.mtek::acos_f32": f_e2cab98b_acos_f32,
  "src/main.mtek::atan_f32": f_e2cab98b_atan_f32,
  "src/main.mtek::floor_f32": f_e2cab98b_floor_f32,
  "src/main.mtek::ceil_f32": f_e2cab98b_ceil_f32,
  "src/main.mtek::trunc_f32": f_e2cab98b_trunc_f32,
  "src/main.mtek::fract_f32": f_e2cab98b_fract_f32,
  "src/main.mtek::sign_f32": f_e2cab98b_sign_f32,
  "src/main.mtek::round_f32": f_e2cab98b_round_f32,
  "src/main.mtek::radians_f32": f_e2cab98b_radians_f32,
  "src/main.mtek::degrees_f32": f_e2cab98b_degrees_f32,
  "src/main.mtek::length_f32": f_e2cab98b_length_f32,
  "src/main.mtek::distance_f32_f32": f_e2cab98b_distance_f32_f32,
  "src/main.mtek::min_f32_f32": f_e2cab98b_min_f32_f32,
  "src/main.mtek::max_f32_f32": f_e2cab98b_max_f32_f32,
  "src/main.mtek::pow_f32_f32": f_e2cab98b_pow_f32_f32,
  "src/main.mtek::atan2_f32_f32": f_e2cab98b_atan2_f32_f32,
  "src/main.mtek::step_f32_f32": f_e2cab98b_step_f32_f32,
  "src/main.mtek::clamp_f32_f32_f32": f_e2cab98b_clamp_f32_f32_f32,
  "src/main.mtek::mix_f32_f32_f32": f_e2cab98b_mix_f32_f32_f32,
  "src/main.mtek::smoothstep_f32_f32_f32": f_e2cab98b_smoothstep_f32_f32_f32,
  "src/main.mtek::abs_i32": f_e2cab98b_abs_i32,
  "src/main.mtek::abs_u32": f_e2cab98b_abs_u32,
  "src/main.mtek::min_i32_i32": f_e2cab98b_min_i32_i32,
  "src/main.mtek::max_i32_i32": f_e2cab98b_max_i32_i32,
  "src/main.mtek::min_u32_u32": f_e2cab98b_min_u32_u32,
  "src/main.mtek::max_u32_u32": f_e2cab98b_max_u32_u32,
  "src/main.mtek::clamp_i32_i32_i32": f_e2cab98b_clamp_i32_i32_i32,
  "src/main.mtek::clamp_u32_u32_u32": f_e2cab98b_clamp_u32_u32_u32,
  "src/main.mtek::abs_vec2": f_e2cab98b_abs_vec2,
  "src/main.mtek::abs_vec3": f_e2cab98b_abs_vec3,
  "src/main.mtek::abs_vec4": f_e2cab98b_abs_vec4,
  "src/main.mtek::saturate_vec2": f_e2cab98b_saturate_vec2,
  "src/main.mtek::saturate_vec3": f_e2cab98b_saturate_vec3,
  "src/main.mtek::saturate_vec4": f_e2cab98b_saturate_vec4,
  "src/main.mtek::sqrt_vec2": f_e2cab98b_sqrt_vec2,
  "src/main.mtek::sqrt_vec3": f_e2cab98b_sqrt_vec3,
  "src/main.mtek::sqrt_vec4": f_e2cab98b_sqrt_vec4,
  "src/main.mtek::inverse_sqrt_vec2": f_e2cab98b_inverse_sqrt_vec2,
  "src/main.mtek::inverse_sqrt_vec3": f_e2cab98b_inverse_sqrt_vec3,
  "src/main.mtek::inverse_sqrt_vec4": f_e2cab98b_inverse_sqrt_vec4,
  "src/main.mtek::exp_vec2": f_e2cab98b_exp_vec2,
  "src/main.mtek::exp_vec3": f_e2cab98b_exp_vec3,
  "src/main.mtek::exp_vec4": f_e2cab98b_exp_vec4,
  "src/main.mtek::exp2_vec2": f_e2cab98b_exp2_vec2,
  "src/main.mtek::exp2_vec3": f_e2cab98b_exp2_vec3,
  "src/main.mtek::exp2_vec4": f_e2cab98b_exp2_vec4,
  "src/main.mtek::log_vec2": f_e2cab98b_log_vec2,
  "src/main.mtek::log_vec3": f_e2cab98b_log_vec3,
  "src/main.mtek::log_vec4": f_e2cab98b_log_vec4,
  "src/main.mtek::log2_vec2": f_e2cab98b_log2_vec2,
  "src/main.mtek::log2_vec3": f_e2cab98b_log2_vec3,
  "src/main.mtek::log2_vec4": f_e2cab98b_log2_vec4,
  "src/main.mtek::sin_vec2": f_e2cab98b_sin_vec2,
  "src/main.mtek::sin_vec3": f_e2cab98b_sin_vec3,
  "src/main.mtek::sin_vec4": f_e2cab98b_sin_vec4,
  "src/main.mtek::cos_vec2": f_e2cab98b_cos_vec2,
  "src/main.mtek::cos_vec3": f_e2cab98b_cos_vec3,
  "src/main.mtek::cos_vec4": f_e2cab98b_cos_vec4,
  "src/main.mtek::tan_vec2": f_e2cab98b_tan_vec2,
  "src/main.mtek::tan_vec3": f_e2cab98b_tan_vec3,
  "src/main.mtek::tan_vec4": f_e2cab98b_tan_vec4,
  "src/main.mtek::asin_vec2": f_e2cab98b_asin_vec2,
  "src/main.mtek::asin_vec3": f_e2cab98b_asin_vec3,
  "src/main.mtek::asin_vec4": f_e2cab98b_asin_vec4,
  "src/main.mtek::acos_vec2": f_e2cab98b_acos_vec2,
  "src/main.mtek::acos_vec3": f_e2cab98b_acos_vec3,
  "src/main.mtek::acos_vec4": f_e2cab98b_acos_vec4,
  "src/main.mtek::atan_vec2": f_e2cab98b_atan_vec2,
  "src/main.mtek::atan_vec3": f_e2cab98b_atan_vec3,
  "src/main.mtek::atan_vec4": f_e2cab98b_atan_vec4,
  "src/main.mtek::floor_vec2": f_e2cab98b_floor_vec2,
  "src/main.mtek::floor_vec3": f_e2cab98b_floor_vec3,
  "src/main.mtek::floor_vec4": f_e2cab98b_floor_vec4,
  "src/main.mtek::ceil_vec2": f_e2cab98b_ceil_vec2,
  "src/main.mtek::ceil_vec3": f_e2cab98b_ceil_vec3,
  "src/main.mtek::ceil_vec4": f_e2cab98b_ceil_vec4,
  "src/main.mtek::trunc_vec2": f_e2cab98b_trunc_vec2,
  "src/main.mtek::trunc_vec3": f_e2cab98b_trunc_vec3,
  "src/main.mtek::trunc_vec4": f_e2cab98b_trunc_vec4,
  "src/main.mtek::fract_vec2": f_e2cab98b_fract_vec2,
  "src/main.mtek::fract_vec3": f_e2cab98b_fract_vec3,
  "src/main.mtek::fract_vec4": f_e2cab98b_fract_vec4,
  "src/main.mtek::sign_vec2": f_e2cab98b_sign_vec2,
  "src/main.mtek::sign_vec3": f_e2cab98b_sign_vec3,
  "src/main.mtek::sign_vec4": f_e2cab98b_sign_vec4,
  "src/main.mtek::round_vec2": f_e2cab98b_round_vec2,
  "src/main.mtek::round_vec3": f_e2cab98b_round_vec3,
  "src/main.mtek::round_vec4": f_e2cab98b_round_vec4,
  "src/main.mtek::radians_vec2": f_e2cab98b_radians_vec2,
  "src/main.mtek::radians_vec3": f_e2cab98b_radians_vec3,
  "src/main.mtek::radians_vec4": f_e2cab98b_radians_vec4,
  "src/main.mtek::degrees_vec2": f_e2cab98b_degrees_vec2,
  "src/main.mtek::degrees_vec3": f_e2cab98b_degrees_vec3,
  "src/main.mtek::degrees_vec4": f_e2cab98b_degrees_vec4,
  "src/main.mtek::min_vec2_vec2": f_e2cab98b_min_vec2_vec2,
  "src/main.mtek::min_vec3_vec3": f_e2cab98b_min_vec3_vec3,
  "src/main.mtek::min_vec4_vec4": f_e2cab98b_min_vec4_vec4,
  "src/main.mtek::max_vec2_vec2": f_e2cab98b_max_vec2_vec2,
  "src/main.mtek::max_vec3_vec3": f_e2cab98b_max_vec3_vec3,
  "src/main.mtek::max_vec4_vec4": f_e2cab98b_max_vec4_vec4,
  "src/main.mtek::pow_vec2_vec2": f_e2cab98b_pow_vec2_vec2,
  "src/main.mtek::pow_vec3_vec3": f_e2cab98b_pow_vec3_vec3,
  "src/main.mtek::pow_vec4_vec4": f_e2cab98b_pow_vec4_vec4,
  "src/main.mtek::atan2_vec2_vec2": f_e2cab98b_atan2_vec2_vec2,
  "src/main.mtek::atan2_vec3_vec3": f_e2cab98b_atan2_vec3_vec3,
  "src/main.mtek::atan2_vec4_vec4": f_e2cab98b_atan2_vec4_vec4,
  "src/main.mtek::step_vec2_vec2": f_e2cab98b_step_vec2_vec2,
  "src/main.mtek::step_vec3_vec3": f_e2cab98b_step_vec3_vec3,
  "src/main.mtek::step_vec4_vec4": f_e2cab98b_step_vec4_vec4,
  "src/main.mtek::clamp_vec2_vec2_vec2": f_e2cab98b_clamp_vec2_vec2_vec2,
  "src/main.mtek::clamp_vec3_vec3_vec3": f_e2cab98b_clamp_vec3_vec3_vec3,
  "src/main.mtek::clamp_vec4_vec4_vec4": f_e2cab98b_clamp_vec4_vec4_vec4,
  "src/main.mtek::mix_vec2_vec2_vec2": f_e2cab98b_mix_vec2_vec2_vec2,
  "src/main.mtek::mix_vec3_vec3_vec3": f_e2cab98b_mix_vec3_vec3_vec3,
  "src/main.mtek::mix_vec4_vec4_vec4": f_e2cab98b_mix_vec4_vec4_vec4,
  "src/main.mtek::smoothstep_vec2_vec2_vec2": f_e2cab98b_smoothstep_vec2_vec2_vec2,
  "src/main.mtek::smoothstep_vec3_vec3_vec3": f_e2cab98b_smoothstep_vec3_vec3_vec3,
  "src/main.mtek::smoothstep_vec4_vec4_vec4": f_e2cab98b_smoothstep_vec4_vec4_vec4,
  "src/main.mtek::mix_vec2_vec2_f32": f_e2cab98b_mix_vec2_vec2_f32,
  "src/main.mtek::mix_vec3_vec3_f32": f_e2cab98b_mix_vec3_vec3_f32,
  "src/main.mtek::mix_vec4_vec4_f32": f_e2cab98b_mix_vec4_vec4_f32,
  "src/main.mtek::add_vec2_vec2": f_e2cab98b_add_vec2_vec2,
  "src/main.mtek::sub_vec2_vec2": f_e2cab98b_sub_vec2_vec2,
  "src/main.mtek::mul_vec2_vec2": f_e2cab98b_mul_vec2_vec2,
  "src/main.mtek::div_vec2_vec2": f_e2cab98b_div_vec2_vec2,
  "src/main.mtek::mul_vec2_f32": f_e2cab98b_mul_vec2_f32,
  "src/main.mtek::mul_f32_vec2": f_e2cab98b_mul_f32_vec2,
  "src/main.mtek::div_vec2_f32": f_e2cab98b_div_vec2_f32,
  "src/main.mtek::neg_vec2": f_e2cab98b_neg_vec2,
  "src/main.mtek::dot_vec2_vec2": f_e2cab98b_dot_vec2_vec2,
  "src/main.mtek::length_vec2": f_e2cab98b_length_vec2,
  "src/main.mtek::distance_vec2_vec2": f_e2cab98b_distance_vec2_vec2,
  "src/main.mtek::normalize_vec2": f_e2cab98b_normalize_vec2,
  "src/main.mtek::reflect_vec2_vec2": f_e2cab98b_reflect_vec2_vec2,
  "src/main.mtek::add_vec3_vec3": f_e2cab98b_add_vec3_vec3,
  "src/main.mtek::sub_vec3_vec3": f_e2cab98b_sub_vec3_vec3,
  "src/main.mtek::mul_vec3_vec3": f_e2cab98b_mul_vec3_vec3,
  "src/main.mtek::div_vec3_vec3": f_e2cab98b_div_vec3_vec3,
  "src/main.mtek::mul_vec3_f32": f_e2cab98b_mul_vec3_f32,
  "src/main.mtek::mul_f32_vec3": f_e2cab98b_mul_f32_vec3,
  "src/main.mtek::div_vec3_f32": f_e2cab98b_div_vec3_f32,
  "src/main.mtek::neg_vec3": f_e2cab98b_neg_vec3,
  "src/main.mtek::dot_vec3_vec3": f_e2cab98b_dot_vec3_vec3,
  "src/main.mtek::length_vec3": f_e2cab98b_length_vec3,
  "src/main.mtek::distance_vec3_vec3": f_e2cab98b_distance_vec3_vec3,
  "src/main.mtek::normalize_vec3": f_e2cab98b_normalize_vec3,
  "src/main.mtek::reflect_vec3_vec3": f_e2cab98b_reflect_vec3_vec3,
  "src/main.mtek::add_vec4_vec4": f_e2cab98b_add_vec4_vec4,
  "src/main.mtek::sub_vec4_vec4": f_e2cab98b_sub_vec4_vec4,
  "src/main.mtek::mul_vec4_vec4": f_e2cab98b_mul_vec4_vec4,
  "src/main.mtek::div_vec4_vec4": f_e2cab98b_div_vec4_vec4,
  "src/main.mtek::mul_vec4_f32": f_e2cab98b_mul_vec4_f32,
  "src/main.mtek::mul_f32_vec4": f_e2cab98b_mul_f32_vec4,
  "src/main.mtek::div_vec4_f32": f_e2cab98b_div_vec4_f32,
  "src/main.mtek::neg_vec4": f_e2cab98b_neg_vec4,
  "src/main.mtek::dot_vec4_vec4": f_e2cab98b_dot_vec4_vec4,
  "src/main.mtek::length_vec4": f_e2cab98b_length_vec4,
  "src/main.mtek::distance_vec4_vec4": f_e2cab98b_distance_vec4_vec4,
  "src/main.mtek::normalize_vec4": f_e2cab98b_normalize_vec4,
  "src/main.mtek::reflect_vec4_vec4": f_e2cab98b_reflect_vec4_vec4,
  "src/main.mtek::cross_vec3_vec3": f_e2cab98b_cross_vec3_vec3,
  "src/main.mtek::make_vec2_f32_f32": f_e2cab98b_make_vec2_f32_f32,
  "src/main.mtek::make_vec2_f32": f_e2cab98b_make_vec2_f32,
  "src/main.mtek::make_vec3_f32_f32_f32": f_e2cab98b_make_vec3_f32_f32_f32,
  "src/main.mtek::make_vec3_f32": f_e2cab98b_make_vec3_f32,
  "src/main.mtek::make_vec3_vec2_f32": f_e2cab98b_make_vec3_vec2_f32,
  "src/main.mtek::make_vec4_f32_f32_f32_f32": f_e2cab98b_make_vec4_f32_f32_f32_f32,
  "src/main.mtek::make_vec4_f32": f_e2cab98b_make_vec4_f32,
  "src/main.mtek::make_vec4_vec3_f32": f_e2cab98b_make_vec4_vec3_f32,
  "src/main.mtek::make_vec4_vec2_f32_f32": f_e2cab98b_make_vec4_vec2_f32_f32,
  "src/main.mtek::quat_identity": f_e2cab98b_quat_identity,
  "src/main.mtek::quat_axis_angle_vec3_f32": f_e2cab98b_quat_axis_angle_vec3_f32,
  "src/main.mtek::quat_euler_f32_f32_f32": f_e2cab98b_quat_euler_f32_f32_f32,
  "src/main.mtek::mul_quat_quat": f_e2cab98b_mul_quat_quat,
  "src/main.mtek::mul_quat_vec3": f_e2cab98b_mul_quat_vec3,
  "src/main.mtek::mat4_identity": f_e2cab98b_mat4_identity,
  "src/main.mtek::mat4_translation_vec3": f_e2cab98b_mat4_translation_vec3,
  "src/main.mtek::mat4_scale_vec3": f_e2cab98b_mat4_scale_vec3,
  "src/main.mtek::mat4_rotation_quat": f_e2cab98b_mat4_rotation_quat,
  "src/main.mtek::mat4_columns_vec4_vec4_vec4_vec4": f_e2cab98b_mat4_columns_vec4_vec4_vec4_vec4,
  "src/main.mtek::mul_mat4_mat4": f_e2cab98b_mul_mat4_mat4,
  "src/main.mtek::mul_mat4_vec4": f_e2cab98b_mul_mat4_vec4,
  "src/main.mtek::transpose_mat4": f_e2cab98b_transpose_mat4,
  "src/main.mtek::color_linear_vec3_f32": f_e2cab98b_color_linear_vec3_f32,
  "src/main.mtek::color_srgb_vec3_f32": f_e2cab98b_color_srgb_vec3_f32,
  "src/main.mtek::reach_all": f_e2cab98b_reach_all,
};

// scene Table (src/main.mtek::Table): the initialisation order of spec/scenes.md section 11
function s_Table_init(ctx) {
  // camera Main (src/main.mtek::Table.Main), active
  ctx.setCamera("position", { x: 0.0, y: 0.0, z: 5.0 });
  ctx.setCamera("rotation", { x: 0.0, y: 0.0, z: 0.0, w: 1.0 });
  ctx.setCamera("projection.fov_y", 0.8999999761581421);
  ctx.setCamera("projection.near", 0.10000000149011612);
  ctx.setCamera("projection.far", 1000.0);
}

export const scenes = {
  Table: {
    init: s_Table_init,
    update: null,
    fixedUpdate: null,
    entityUpdate: [],
    entityFixedUpdate: [],
    events: {},
    bindings: [],
  },
};

export const prefabs = {};

export default { abi, baseUrl, manifestUrl, writers, functions, scenes, prefabs };
//# sourceMappingURL=app.js.map
