// Generated by mtek 0.1.0-dev for language 0.1. Do not edit.
import * as rt from "./runtime.75e25692ce38d7a0.js";
export { mountMtek } from "./runtime.75e25692ce38d7a0.js";
const fr = Math.fround;

export const abi = 1;
export const baseUrl = new URL("./", import.meta.url);
export const manifestUrl = new URL("./program.manifest.json", import.meta.url);

// Generated from layout builtin:frame (size 288). Do not edit.
function w_builtin_MtekFrame_view_proj(m, base, v) {
  const w = base >>> 2;
  m.f32[w + 0] = v[0]; m.f32[w + 1] = v[1]; m.f32[w + 2] = v[2]; m.f32[w + 3] = v[3];
  m.f32[w + 4] = v[4]; m.f32[w + 5] = v[5]; m.f32[w + 6] = v[6]; m.f32[w + 7] = v[7];
  m.f32[w + 8] = v[8]; m.f32[w + 9] = v[9]; m.f32[w + 10] = v[10]; m.f32[w + 11] = v[11];
  m.f32[w + 12] = v[12]; m.f32[w + 13] = v[13]; m.f32[w + 14] = v[14]; m.f32[w + 15] = v[15];
}
function w_builtin_MtekFrame_camera_position(m, base, v) {
  const w = base >>> 2;
  m.f32[w + 16] = v.x; m.f32[w + 17] = v.y; m.f32[w + 18] = v.z;
}
function w_builtin_MtekFrame_light_count(m, base, v) {
  m.u32[(base >>> 2) + 19] = v;
}
function w_builtin_MtekFrame_ambient(m, base, v) {
  const w = base >>> 2;
  m.f32[w + 20] = v.x; m.f32[w + 21] = v.y; m.f32[w + 22] = v.z;
}
function w_builtin_MtekFrame_reserved0(m, base, v) {
  m.f32[(base >>> 2) + 23] = v;
}
function w_builtin_MtekFrame_lights(m, base, v) {
  const w = base >>> 2;
  m.f32[w + 24] = v[0].color.x; m.f32[w + 25] = v[0].color.y; m.f32[w + 26] = v[0].color.z;
  m.u32[w + 27] = v[0].kind;
  m.f32[w + 28] = v[0].position.x; m.f32[w + 29] = v[0].position.y; m.f32[w + 30] = v[0].position.z;
  m.f32[w + 31] = v[0].range;
  m.f32[w + 32] = v[0].direction.x; m.f32[w + 33] = v[0].direction.y; m.f32[w + 34] = v[0].direction.z;
  m.f32[w + 35] = v[0].reserved;
  m.f32[w + 36] = v[1].color.x; m.f32[w + 37] = v[1].color.y; m.f32[w + 38] = v[1].color.z;
  m.u32[w + 39] = v[1].kind;
  m.f32[w + 40] = v[1].position.x; m.f32[w + 41] = v[1].position.y; m.f32[w + 42] = v[1].position.z;
  m.f32[w + 43] = v[1].range;
  m.f32[w + 44] = v[1].direction.x; m.f32[w + 45] = v[1].direction.y; m.f32[w + 46] = v[1].direction.z;
  m.f32[w + 47] = v[1].reserved;
  m.f32[w + 48] = v[2].color.x; m.f32[w + 49] = v[2].color.y; m.f32[w + 50] = v[2].color.z;
  m.u32[w + 51] = v[2].kind;
  m.f32[w + 52] = v[2].position.x; m.f32[w + 53] = v[2].position.y; m.f32[w + 54] = v[2].position.z;
  m.f32[w + 55] = v[2].range;
  m.f32[w + 56] = v[2].direction.x; m.f32[w + 57] = v[2].direction.y; m.f32[w + 58] = v[2].direction.z;
  m.f32[w + 59] = v[2].reserved;
  m.f32[w + 60] = v[3].color.x; m.f32[w + 61] = v[3].color.y; m.f32[w + 62] = v[3].color.z;
  m.u32[w + 63] = v[3].kind;
  m.f32[w + 64] = v[3].position.x; m.f32[w + 65] = v[3].position.y; m.f32[w + 66] = v[3].position.z;
  m.f32[w + 67] = v[3].range;
  m.f32[w + 68] = v[3].direction.x; m.f32[w + 69] = v[3].direction.y; m.f32[w + 70] = v[3].direction.z;
  m.f32[w + 71] = v[3].reserved;
}
function w_builtin_MtekFrame(m, base, v) {
  w_builtin_MtekFrame_view_proj(m, base, v.view_proj);
  w_builtin_MtekFrame_camera_position(m, base, v.camera_position);
  w_builtin_MtekFrame_light_count(m, base, v.light_count);
  w_builtin_MtekFrame_ambient(m, base, v.ambient);
  w_builtin_MtekFrame_reserved0(m, base, v.reserved0);
  w_builtin_MtekFrame_lights(m, base, v.lights);
}

// Generated from layout builtin:object (size 128). Do not edit.
function w_builtin_MtekObject_model(m, base, v) {
  const w = base >>> 2;
  m.f32[w + 0] = v[0]; m.f32[w + 1] = v[1]; m.f32[w + 2] = v[2]; m.f32[w + 3] = v[3];
  m.f32[w + 4] = v[4]; m.f32[w + 5] = v[5]; m.f32[w + 6] = v[6]; m.f32[w + 7] = v[7];
  m.f32[w + 8] = v[8]; m.f32[w + 9] = v[9]; m.f32[w + 10] = v[10]; m.f32[w + 11] = v[11];
  m.f32[w + 12] = v[12]; m.f32[w + 13] = v[13]; m.f32[w + 14] = v[14]; m.f32[w + 15] = v[15];
}
function w_builtin_MtekObject_normal_matrix(m, base, v) {
  const w = base >>> 2;
  m.f32[w + 16] = v[0]; m.f32[w + 17] = v[1]; m.f32[w + 18] = v[2]; m.f32[w + 19] = v[3];
  m.f32[w + 20] = v[4]; m.f32[w + 21] = v[5]; m.f32[w + 22] = v[6]; m.f32[w + 23] = v[7];
  m.f32[w + 24] = v[8]; m.f32[w + 25] = v[9]; m.f32[w + 26] = v[10]; m.f32[w + 27] = v[11];
  m.f32[w + 28] = v[12]; m.f32[w + 29] = v[13]; m.f32[w + 30] = v[14]; m.f32[w + 31] = v[15];
}
function w_builtin_MtekObject(m, base, v) {
  w_builtin_MtekObject_model(m, base, v.model);
  w_builtin_MtekObject_normal_matrix(m, base, v.normal_matrix);
}

// Generated from layout material:src/main.mtek::Pulse (size 4). Do not edit.
function w_e2cab98b_Pulse_phase(m, base, v) {
  m.f32[(base >>> 2) + 0] = v;
}
function w_e2cab98b_Pulse(m, base, v) {
  w_e2cab98b_Pulse_phase(m, base, v.phase);
}

export const writers = {
  "builtin:frame": { all: w_builtin_MtekFrame, fields: { view_proj: w_builtin_MtekFrame_view_proj, camera_position: w_builtin_MtekFrame_camera_position, light_count: w_builtin_MtekFrame_light_count, ambient: w_builtin_MtekFrame_ambient, reserved0: w_builtin_MtekFrame_reserved0, lights: w_builtin_MtekFrame_lights } },
  "builtin:object": { all: w_builtin_MtekObject, fields: { model: w_builtin_MtekObject_model, normal_matrix: w_builtin_MtekObject_normal_matrix } },
  "material:src/main.mtek::Pulse": { all: w_e2cab98b_Pulse, fields: { phase: w_e2cab98b_Pulse_phase } },
};

// cpu fn bump(x: i32) -> i32 (src/main.mtek::bump)
function f_e2cab98b_bump(ctx, a_x) {
  return (a_x + 1) | 0;
}

export const functions = {
  "src/main.mtek::bump": f_e2cab98b_bump,
};

// update (src/main.mtek::Demo.update)
function b_0_update(ctx, a_dt) {
  ctx.s.angle = fr(ctx.s.angle + fr(ctx.s.speed * a_dt));
  ctx.s.ticks = f_e2cab98b_bump(ctx, ctx.s.ticks);
  ctx.setTransform(ctx.e[0], "position", rt.v3with(ctx.e[0].position, "y", 0.5));
  ctx.setParam(ctx.e[0], "phase", ctx.s.angle);
  ctx.setCamera("position", rt.v3(0.0, fr(ctx.e[0].state.hits), 6.0));
}

// fixed_update (src/main.mtek::Demo.fixed_update)
function b_1_fixed_update(ctx, a_step) {
  ctx.s.speed = fr(ctx.s.speed - a_step);
}

// on key_down (src/main.mtek::Demo.on_key_down_Space)
function b_2_on_key_down(ctx, self) {
  ctx.s.speed = -ctx.s.speed;
  ctx.e[0].state.hits = 0;
}

// on pointer_down (src/main.mtek::Demo.on_pointer_down)
function b_3_on_pointer_down(ctx, self, a_event) {
  ctx.s.angle = a_event.position.x;
}

// update (src/main.mtek::Demo.Cube.update)
function b_4_update(ctx, self, a_dt) {
  self.state.hits = f_e2cab98b_bump(ctx, self.state.hits);
}

// on key_down (src/main.mtek::Demo.Cube.on_key_down_Enter)
function b_5_on_key_down(ctx, self) {
  self.state.hits = (self.state.hits + 1) | 0;
}

// scene Demo (src/main.mtek::Demo): the initialisation order of spec/scenes.md section 11
function s_Demo_init(ctx) {
  ctx.s.speed = 0.5;
  ctx.s.angle = 0.0;
  ctx.s.ticks = 0;
  // camera Main (src/main.mtek::Demo.Main), active
  ctx.setCamera("position", { x: 0.0, y: 0.0, z: 6.0 });
  ctx.setCamera("target", { x: 0.0, y: 0.0, z: 0.0 });
  ctx.setCamera("projection.fov_y", 0.8999999761581421);
  ctx.setCamera("projection.near", 0.10000000149011612);
  ctx.setCamera("projection.far", 1000.0);
  ctx.e[0].state.hits = f_e2cab98b_bump(ctx, 0);
  // entity #0 Cube (src/main.mtek::Demo.Cube)
  const e0 = ctx.e[0];
  ctx.setTransform(e0, "position", { x: 0.0, y: 0.0, z: 0.0 });
  ctx.setTransform(e0, "rotation", { x: 0.0, y: 0.0, z: 0.0, w: 1.0 });
  ctx.setTransform(e0, "scale", { x: 1.0, y: 1.0, z: 1.0 });
  ctx.setVisible(e0, true);
  ctx.setParam(e0, "phase", 0.25);
}

export const scenes = {
  Demo: {
    init: s_Demo_init,
    update: b_0_update,
    fixedUpdate: b_1_fixed_update,
    entityUpdate: [b_4_update],
    entityFixedUpdate: [null],
    events: { key_down: [{ key: "Space", owner: -1, fn: b_2_on_key_down }, { key: "Enter", owner: 0, fn: b_5_on_key_down }], pointer_down: [{ owner: -1, fn: b_3_on_pointer_down }] },
    bindings: [],
  },
};

export const prefabs = {};

export default { abi, baseUrl, manifestUrl, writers, functions, scenes, prefabs };
//# sourceMappingURL=app.js.map
