// Generated by mtek 0.1.0-dev for language 0.1. Do not edit.
import * as rt from "./runtime.75e25692ce38d7a0.js";
export { mountMtek } from "./runtime.75e25692ce38d7a0.js";
const fr = Math.fround;

export const abi = 1;
export const baseUrl = new URL("./", import.meta.url);
export const manifestUrl = new URL("./program.manifest.json", import.meta.url);

// Generated from layout builtin:frame (size 288). Do not edit.
function w_builtin_MtekFrame_view_proj(m, base, v) {
  const w = base >>> 2;
  m.f32[w + 0] = v[0]; m.f32[w + 1] = v[1]; m.f32[w + 2] = v[2]; m.f32[w + 3] = v[3];
  m.f32[w + 4] = v[4]; m.f32[w + 5] = v[5]; m.f32[w + 6] = v[6]; m.f32[w + 7] = v[7];
  m.f32[w + 8] = v[8]; m.f32[w + 9] = v[9]; m.f32[w + 10] = v[10]; m.f32[w + 11] = v[11];
  m.f32[w + 12] = v[12]; m.f32[w + 13] = v[13]; m.f32[w + 14] = v[14]; m.f32[w + 15] = v[15];
}
function w_builtin_MtekFrame_camera_position(m, base, v) {
  const w = base >>> 2;
  m.f32[w + 16] = v.x; m.f32[w + 17] = v.y; m.f32[w + 18] = v.z;
}
function w_builtin_MtekFrame_light_count(m, base, v) {
  m.u32[(base >>> 2) + 19] = v;
}
function w_builtin_MtekFrame_ambient(m, base, v) {
  const w = base >>> 2;
  m.f32[w + 20] = v.x; m.f32[w + 21] = v.y; m.f32[w + 22] = v.z;
}
function w_builtin_MtekFrame_reserved0(m, base, v) {
  m.f32[(base >>> 2) + 23] = v;
}
function w_builtin_MtekFrame_lights(m, base, v) {
  const w = base >>> 2;
  m.f32[w + 24] = v[0].color.x; m.f32[w + 25] = v[0].color.y; m.f32[w + 26] = v[0].color.z;
  m.u32[w + 27] = v[0].kind;
  m.f32[w + 28] = v[0].position.x; m.f32[w + 29] = v[0].position.y; m.f32[w + 30] = v[0].position.z;
  m.f32[w + 31] = v[0].range;
  m.f32[w + 32] = v[0].direction.x; m.f32[w + 33] = v[0].direction.y; m.f32[w + 34] = v[0].direction.z;
  m.f32[w + 35] = v[0].reserved;
  m.f32[w + 36] = v[1].color.x; m.f32[w + 37] = v[1].color.y; m.f32[w + 38] = v[1].color.z;
  m.u32[w + 39] = v[1].kind;
  m.f32[w + 40] = v[1].position.x; m.f32[w + 41] = v[1].position.y; m.f32[w + 42] = v[1].position.z;
  m.f32[w + 43] = v[1].range;
  m.f32[w + 44] = v[1].direction.x; m.f32[w + 45] = v[1].direction.y; m.f32[w + 46] = v[1].direction.z;
  m.f32[w + 47] = v[1].reserved;
  m.f32[w + 48] = v[2].color.x; m.f32[w + 49] = v[2].color.y; m.f32[w + 50] = v[2].color.z;
  m.u32[w + 51] = v[2].kind;
  m.f32[w + 52] = v[2].position.x; m.f32[w + 53] = v[2].position.y; m.f32[w + 54] = v[2].position.z;
  m.f32[w + 55] = v[2].range;
  m.f32[w + 56] = v[2].direction.x; m.f32[w + 57] = v[2].direction.y; m.f32[w + 58] = v[2].direction.z;
  m.f32[w + 59] = v[2].reserved;
  m.f32[w + 60] = v[3].color.x; m.f32[w + 61] = v[3].color.y; m.f32[w + 62] = v[3].color.z;
  m.u32[w + 63] = v[3].kind;
  m.f32[w + 64] = v[3].position.x; m.f32[w + 65] = v[3].position.y; m.f32[w + 66] = v[3].position.z;
  m.f32[w + 67] = v[3].range;
  m.f32[w + 68] = v[3].direction.x; m.f32[w + 69] = v[3].direction.y; m.f32[w + 70] = v[3].direction.z;
  m.f32[w + 71] = v[3].reserved;
}
function w_builtin_MtekFrame(m, base, v) {
  w_builtin_MtekFrame_view_proj(m, base, v.view_proj);
  w_builtin_MtekFrame_camera_position(m, base, v.camera_position);
  w_builtin_MtekFrame_light_count(m, base, v.light_count);
  w_builtin_MtekFrame_ambient(m, base, v.ambient);
  w_builtin_MtekFrame_reserved0(m, base, v.reserved0);
  w_builtin_MtekFrame_lights(m, base, v.lights);
}

// Generated from layout builtin:object (size 128). Do not edit.
function w_builtin_MtekObject_model(m, base, v) {
  const w = base >>> 2;
  m.f32[w + 0] = v[0]; m.f32[w + 1] = v[1]; m.f32[w + 2] = v[2]; m.f32[w + 3] = v[3];
  m.f32[w + 4] = v[4]; m.f32[w + 5] = v[5]; m.f32[w + 6] = v[6]; m.f32[w + 7] = v[7];
  m.f32[w + 8] = v[8]; m.f32[w + 9] = v[9]; m.f32[w + 10] = v[10]; m.f32[w + 11] = v[11];
  m.f32[w + 12] = v[12]; m.f32[w + 13] = v[13]; m.f32[w + 14] = v[14]; m.f32[w + 15] = v[15];
}
function w_builtin_MtekObject_normal_matrix(m, base, v) {
  const w = base >>> 2;
  m.f32[w + 16] = v[0]; m.f32[w + 17] = v[1]; m.f32[w + 18] = v[2]; m.f32[w + 19] = v[3];
  m.f32[w + 20] = v[4]; m.f32[w + 21] = v[5]; m.f32[w + 22] = v[6]; m.f32[w + 23] = v[7];
  m.f32[w + 24] = v[8]; m.f32[w + 25] = v[9]; m.f32[w + 26] = v[10]; m.f32[w + 27] = v[11];
  m.f32[w + 28] = v[12]; m.f32[w + 29] = v[13]; m.f32[w + 30] = v[14]; m.f32[w + 31] = v[15];
}
function w_builtin_MtekObject(m, base, v) {
  w_builtin_MtekObject_model(m, base, v.model);
  w_builtin_MtekObject_normal_matrix(m, base, v.normal_matrix);
}

export const writers = {
  "builtin:frame": { all: w_builtin_MtekFrame, fields: { view_proj: w_builtin_MtekFrame_view_proj, camera_position: w_builtin_MtekFrame_camera_position, light_count: w_builtin_MtekFrame_light_count, ambient: w_builtin_MtekFrame_ambient, reserved0: w_builtin_MtekFrame_reserved0, lights: w_builtin_MtekFrame_lights } },
  "builtin:object": { all: w_builtin_MtekObject, fields: { model: w_builtin_MtekObject_model, normal_matrix: w_builtin_MtekObject_normal_matrix } },
};

// fn mul_add(a: f32, b: f32, c: f32) -> f32 (src/main.mtek::mul_add)
function f_e2cab98b_mul_add(ctx, a_a, a_b, a_c) {
  return fr(fr(a_a * a_b) + a_c);
}

// fn sum3(a: f32, b: f32, c: f32) -> f32 (src/main.mtek::sum3)
function f_e2cab98b_sum3(ctx, a_a, a_b, a_c) {
  return fr(fr(a_a + a_b) + a_c);
}

// fn tenth() -> f32 (src/main.mtek::tenth)
function f_e2cab98b_tenth(ctx) {
  return 0.10000000149011612;
}

// fn add_tenth(x: f32) -> f32 (src/main.mtek::add_tenth)
function f_e2cab98b_add_tenth(ctx, a_x) {
  return fr(a_x + 0.10000000149011612);
}

// fn third(x: f32) -> f32 (src/main.mtek::third)
function f_e2cab98b_third(ctx, a_x) {
  return fr(a_x / 3.0);
}

// fn idiv(a: i32, b: i32) -> i32 (src/main.mtek::idiv)
function f_e2cab98b_idiv(ctx, a_a, a_b) {
  return rt.idiv(a_a, a_b);
}

// fn irem(a: i32, b: i32) -> i32 (src/main.mtek::irem)
function f_e2cab98b_irem(ctx, a_a, a_b) {
  return rt.irem(a_a, a_b);
}

// fn imul(a: i32, b: i32) -> i32 (src/main.mtek::imul)
function f_e2cab98b_imul(ctx, a_a, a_b) {
  return Math.imul(a_a, a_b);
}

// fn iadd(a: i32, b: i32) -> i32 (src/main.mtek::iadd)
function f_e2cab98b_iadd(ctx, a_a, a_b) {
  return (a_a + a_b) | 0;
}

// fn ineg(a: i32) -> i32 (src/main.mtek::ineg)
function f_e2cab98b_ineg(ctx, a_a) {
  return -a_a | 0;
}

// fn usub(a: u32, b: u32) -> u32 (src/main.mtek::usub)
function f_e2cab98b_usub(ctx, a_a, a_b) {
  return (a_a - a_b) >>> 0;
}

// fn udiv(a: u32, b: u32) -> u32 (src/main.mtek::udiv)
function f_e2cab98b_udiv(ctx, a_a, a_b) {
  return rt.udiv(a_a, a_b);
}

// fn urem(a: u32, b: u32) -> u32 (src/main.mtek::urem)
function f_e2cab98b_urem(ctx, a_a, a_b) {
  return rt.urem(a_a, a_b);
}

// fn umul(a: u32, b: u32) -> u32 (src/main.mtek::umul)
function f_e2cab98b_umul(ctx, a_a, a_b) {
  return Math.imul(a_a, a_b) >>> 0;
}

// fn to_i32(x: f32) -> i32 (src/main.mtek::to_i32)
function f_e2cab98b_to_i32(ctx, a_x) {
  return rt.f2i(a_x);
}

// fn to_u32(x: f32) -> u32 (src/main.mtek::to_u32)
function f_e2cab98b_to_u32(ctx, a_x) {
  return rt.f2u(a_x);
}

// fn i_to_u(x: i32) -> u32 (src/main.mtek::i_to_u)
function f_e2cab98b_i_to_u(ctx, a_x) {
  return a_x >>> 0;
}

// fn u_to_i(x: u32) -> i32 (src/main.mtek::u_to_i)
function f_e2cab98b_u_to_i(ctx, a_x) {
  return a_x | 0;
}

// fn i_to_f(x: i32) -> f32 (src/main.mtek::i_to_f)
function f_e2cab98b_i_to_f(ctx, a_x) {
  return fr(a_x);
}

// fn u_to_f(x: u32) -> f32 (src/main.mtek::u_to_f)
function f_e2cab98b_u_to_f(ctx, a_x) {
  return fr(a_x);
}

// fn pick(i: i32) -> f32 (src/main.mtek::pick)
function f_e2cab98b_pick(ctx, a_i) {
  return [1.5, 2.5, 3.5, 4.5][rt.clampIndex(a_i, 4, 61, ctx)];
}

// fn pick_u(i: u32) -> f32 (src/main.mtek::pick_u)
function f_e2cab98b_pick_u(ctx, a_i) {
  return [1.5, 2.5, 3.5, 4.5][rt.clampIndex(a_i, 4, 62, ctx)];
}

// fn second() -> f32 (src/main.mtek::second)
function f_e2cab98b_second(ctx) {
  const l_values = [10.0, 20.0, 30.0];
  return l_values[1];
}

// fn nth(values: array<i32, 3>, i: u32) -> i32 (src/main.mtek::nth)
function f_e2cab98b_nth(ctx, a_values, a_i) {
  return a_values[rt.clampIndex(a_i, 3, 63, ctx)];
}

// fn column(m: mat4, i: i32) -> vec4 (src/main.mtek::column)
function f_e2cab98b_column(ctx, a_m, a_i) {
  return rt.m4col(a_m, rt.clampIndex(a_i, 4, 64, ctx));
}

// fn last_column(m: mat4) -> vec4 (src/main.mtek::last_column)
function f_e2cab98b_last_column(ctx, a_m) {
  return rt.m4col(a_m, 3);
}

// fn lift(v: vec3, h: f32) -> vec3 (src/main.mtek::lift)
function f_e2cab98b_lift(ctx, a_v, a_h) {
  let l_p = a_v;
  l_p = rt.v3with(l_p, "y", a_h);
  l_p = rt.v3with(l_p, "x", fr(l_p.x + 1.0));
  l_p = rt.v3with(l_p, "z", fr(l_p.z - 0.10000000149011612));
  l_p = rt.v3scale(l_p, 2.0);
  return l_p;
}

// fn count_down(n: i32) -> i32 (src/main.mtek::count_down)
function f_e2cab98b_count_down(ctx, a_n) {
  let l_k = a_n;
  l_k = (l_k - 3) | 0;
  l_k = Math.imul(l_k, 2);
  l_k = rt.idiv(l_k, 0);
  return l_k;
}

// fn zyx(v: vec4) -> vec3 (src/main.mtek::zyx)
function f_e2cab98b_zyx(ctx, a_v) {
  return rt.swizzle3(a_v, "z", "y", "x");
}

// fn xxyy(v: vec2) -> vec4 (src/main.mtek::xxyy)
function f_e2cab98b_xxyy(ctx, a_v) {
  return rt.swizzle4(a_v, "x", "x", "y", "y");
}

// fn rgb(c: color) -> vec3 (src/main.mtek::rgb)
function f_e2cab98b_rgb(ctx, a_c) {
  return rt.crgb(a_c);
}

// fn alpha(c: color) -> f32 (src/main.mtek::alpha)
function f_e2cab98b_alpha(ctx, a_c) {
  return a_c.a;
}

// fn quat_w(q: quat) -> f32 (src/main.mtek::quat_w)
function f_e2cab98b_quat_w(ctx, a_q) {
  return a_q.w;
}

// fn sum_to(n: i32) -> i32 (src/main.mtek::sum_to)
function f_e2cab98b_sum_to(ctx, a_n) {
  let l_total = 0;
  for (let l_i = 0, t_0 = a_n; l_i < t_0; l_i++) {
    if (l_i === 3) {
      continue;
    }
    if (l_i === 7) {
      break;
    }
    l_total = (l_total + l_i) | 0;
  }
  return l_total;
}

// fn count_u(n: u32) -> u32 (src/main.mtek::count_u)
function f_e2cab98b_count_u(ctx, a_n) {
  let l_c = 0;
  for (let l_i = 1, t_0 = a_n; l_i < t_0; l_i++) {
    l_c = (l_c + l_i) >>> 0;
  }
  return l_c;
}

// fn sum_each(values: array<f32, 3>) -> f32 (src/main.mtek::sum_each)
function f_e2cab98b_sum_each(ctx, a_values) {
  let l_s = 0.0;
  for (const l_v of a_values) {
    l_s = fr(l_s + l_v);
  }
  return l_s;
}

// fn classify(x: f32) -> i32 (src/main.mtek::classify)
function f_e2cab98b_classify(ctx, a_x) {
  if (a_x < 0.0) {
    return -1;
  } else if (a_x === 0.0) {
    return 0;
  } else if (a_x > 0.0) {
    return 1;
  }
  return 2;
}

// fn xor(a: bool, b: bool) -> bool (src/main.mtek::xor)
function f_e2cab98b_xor(ctx, a_a, a_b) {
  return a_a && !a_b || a_b && !a_a;
}

// fn in_range(x: i32, lo: i32, hi: i32) -> bool (src/main.mtek::in_range)
function f_e2cab98b_in_range(ctx, a_x, a_lo, a_hi) {
  return a_lo <= a_x && a_x < a_hi;
}

// fn make_wave(a: f32) -> Wave (src/main.mtek::make_wave)
function f_e2cab98b_make_wave(ctx, a_a) {
  return { amplitude: fr(a_a * 2.0), offset: rt.v3(a_a, 0.0, -a_a) };
}

// fn wave_at(w: Wave, t: f32) -> vec3 (src/main.mtek::wave_at)
function f_e2cab98b_wave_at(ctx, a_w, a_t) {
  return rt.v3scale(a_w.offset, fr(a_w.amplitude * a_t));
}

// fn wave_sum(waves: array<Wave, 2>) -> f32 (src/main.mtek::wave_sum)
function f_e2cab98b_wave_sum(ctx, a_waves) {
  let l_total = 0.0;
  for (const l_w of a_waves) {
    l_total = fr(l_total + l_w.amplitude);
  }
  return l_total;
}

// fn rotate(q: quat, v: vec3) -> vec3 (src/main.mtek::rotate)
function f_e2cab98b_rotate(ctx, a_q, a_v) {
  return rt.qrotate(a_q, a_v);
}

// fn transform(m: mat4, v: vec4) -> vec4 (src/main.mtek::transform)
function f_e2cab98b_transform(ctx, a_m, a_v) {
  return rt.m4mulv(a_m, a_v);
}

// fn spin(angle: f32) -> quat (src/main.mtek::spin)
function f_e2cab98b_spin(ctx, a_angle) {
  return rt.qaxisAngle({ x: 0.0, y: 1.0, z: 0.0 }, a_angle);
}

// fn hypot(v: vec2) -> f32 (src/main.mtek::hypot)
function f_e2cab98b_hypot(ctx, a_v) {
  return rt.v2length(a_v);
}

// fn half_way(a: vec3, b: vec3) -> vec3 (src/main.mtek::half_way)
function f_e2cab98b_half_way(ctx, a_a, a_b) {
  return rt.v3mixs(a_a, a_b, 0.5);
}

// fn tinted(base: vec3) -> color (src/main.mtek::tinted)
function f_e2cab98b_tinted(ctx, a_base) {
  return rt.clinear(rt.v3scale(a_base, 0.5), 1.0);
}

// fn wave(t: f32) -> f32 (src/main.mtek::wave)
function f_e2cab98b_wave(ctx, a_t) {
  return fr(fr(rt.sin(a_t) * 0.5) + 0.5);
}

// fn decay(t: f32) -> f32 (src/main.mtek::decay)
function f_e2cab98b_decay(ctx, a_t) {
  return fr(rt.exp(-a_t) * rt.pow(2.0, a_t));
}

// fn pulse(t: f32) -> f32 (src/main.mtek::pulse)
function f_e2cab98b_pulse(ctx, a_t) {
  return fr(a_t + 1.0);
}

// cpu fn combined(t: f32) -> f32 (src/main.mtek::combined)
function f_e2cab98b_combined(ctx, a_t) {
  return fr(f_e2cab98b_pulse(ctx, a_t) + f_fb30ea10_util_pulse(ctx, a_t));
}

// fn doubled(v: vec3) -> vec3 (src/main.mtek::doubled)
function f_e2cab98b_doubled(ctx, a_v) {
  return f_fb30ea10_scale(ctx, a_v, 2.0);
}

// fn add_wrapped(a: u32) -> u32 (src/main.mtek::add_wrapped)
function f_e2cab98b_add_wrapped(ctx, a_a) {
  return f_fb30ea10_wrap_add(ctx, a_a, 4294967295);
}

// cpu fn reach_all() (src/main.mtek::reach_all)
function f_e2cab98b_reach_all(ctx) {
  f_e2cab98b_mul_add(ctx, 0.0, 0.0, 0.0);
  f_e2cab98b_sum3(ctx, 0.0, 0.0, 0.0);
  f_e2cab98b_tenth(ctx);
  f_e2cab98b_add_tenth(ctx, 0.0);
  f_e2cab98b_third(ctx, 0.0);
  f_e2cab98b_idiv(ctx, 0, 1);
  f_e2cab98b_irem(ctx, 0, 1);
  f_e2cab98b_imul(ctx, 0, 0);
  f_e2cab98b_iadd(ctx, 0, 0);
  f_e2cab98b_ineg(ctx, 0);
  f_e2cab98b_usub(ctx, 0, 0);
  f_e2cab98b_udiv(ctx, 0, 1);
  f_e2cab98b_urem(ctx, 0, 1);
  f_e2cab98b_umul(ctx, 0, 0);
  f_e2cab98b_to_i32(ctx, 0.0);
  f_e2cab98b_to_u32(ctx, 0.0);
  f_e2cab98b_i_to_u(ctx, 0);
  f_e2cab98b_u_to_i(ctx, 0);
  f_e2cab98b_i_to_f(ctx, 0);
  f_e2cab98b_u_to_f(ctx, 0);
  f_e2cab98b_pick(ctx, 0);
  f_e2cab98b_pick_u(ctx, 0);
  f_e2cab98b_second(ctx);
  f_e2cab98b_nth(ctx, [0, 0, 0], 0);
  f_e2cab98b_column(ctx, new Float32Array([1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]), 0);
  f_e2cab98b_last_column(ctx, new Float32Array([1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]));
  f_e2cab98b_lift(ctx, { x: 0.0, y: 0.0, z: 0.0 }, 0.0);
  f_e2cab98b_count_down(ctx, 0);
  f_e2cab98b_zyx(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_xxyy(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_rgb(ctx, { r: 0.0, g: 0.0, b: 0.0, a: 1.0 });
  f_e2cab98b_alpha(ctx, { r: 0.0, g: 0.0, b: 0.0, a: 1.0 });
  f_e2cab98b_quat_w(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 1.0 });
  f_e2cab98b_sum_to(ctx, 0);
  f_e2cab98b_count_u(ctx, 0);
  f_e2cab98b_sum_each(ctx, [0.0, 0.0, 0.0]);
  f_e2cab98b_classify(ctx, 0.0);
  f_e2cab98b_xor(ctx, false, false);
  f_e2cab98b_in_range(ctx, 0, 0, 1);
  f_e2cab98b_make_wave(ctx, 0.0);
  f_e2cab98b_wave_at(ctx, f_e2cab98b_make_wave(ctx, 0.0), 0.0);
  f_e2cab98b_wave_sum(ctx, [f_e2cab98b_make_wave(ctx, 0.0), f_e2cab98b_make_wave(ctx, 1.0)]);
  f_e2cab98b_rotate(ctx, { x: 0.0, y: 0.0, z: 0.0, w: 1.0 }, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_transform(ctx, new Float32Array([1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]), { x: 0.0, y: 0.0, z: 0.0, w: 0.0 });
  f_e2cab98b_spin(ctx, 0.0);
  f_e2cab98b_hypot(ctx, { x: 0.0, y: 0.0 });
  f_e2cab98b_half_way(ctx, { x: 0.0, y: 0.0, z: 0.0 }, { x: 1.0, y: 1.0, z: 1.0 });
  f_e2cab98b_tinted(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_wave(ctx, 0.0);
  f_e2cab98b_decay(ctx, 0.0);
  f_e2cab98b_combined(ctx, 0.0);
  f_e2cab98b_doubled(ctx, { x: 0.0, y: 0.0, z: 0.0 });
  f_e2cab98b_add_wrapped(ctx, 0);
}

// fn scale(v: vec3, s: f32) -> vec3 (src/util.mtek::scale)
function f_fb30ea10_scale(ctx, a_v, a_s) {
  return rt.v3smul(a_s, a_v);
}

// fn wrap_add(a: u32, b: u32) -> u32 (src/util.mtek::wrap_add)
function f_fb30ea10_wrap_add(ctx, a_a, a_b) {
  return (a_a + a_b) >>> 0;
}

// fn pulse(t: f32) -> f32 (src/util.mtek::pulse)
function f_fb30ea10_pulse(ctx, a_t) {
  return fr(a_t * 2.0);
}

// fn util_pulse(t: f32) -> f32 (src/util.mtek::util_pulse)
function f_fb30ea10_util_pulse(ctx, a_t) {
  return f_fb30ea10_pulse(ctx, a_t);
}

export const functions = {
  "src/main.mtek::mul_add": f_e2cab98b_mul_add,
  "src/main.mtek::sum3": f_e2cab98b_sum3,
  "src/main.mtek::tenth": f_e2cab98b_tenth,
  "src/main.mtek::add_tenth": f_e2cab98b_add_tenth,
  "src/main.mtek::third": f_e2cab98b_third,
  "src/main.mtek::idiv": f_e2cab98b_idiv,
  "src/main.mtek::irem": f_e2cab98b_irem,
  "src/main.mtek::imul": f_e2cab98b_imul,
  "src/main.mtek::iadd": f_e2cab98b_iadd,
  "src/main.mtek::ineg": f_e2cab98b_ineg,
  "src/main.mtek::usub": f_e2cab98b_usub,
  "src/main.mtek::udiv": f_e2cab98b_udiv,
  "src/main.mtek::urem": f_e2cab98b_urem,
  "src/main.mtek::umul": f_e2cab98b_umul,
  "src/main.mtek::to_i32": f_e2cab98b_to_i32,
  "src/main.mtek::to_u32": f_e2cab98b_to_u32,
  "src/main.mtek::i_to_u": f_e2cab98b_i_to_u,
  "src/main.mtek::u_to_i": f_e2cab98b_u_to_i,
  "src/main.mtek::i_to_f": f_e2cab98b_i_to_f,
  "src/main.mtek::u_to_f": f_e2cab98b_u_to_f,
  "src/main.mtek::pick": f_e2cab98b_pick,
  "src/main.mtek::pick_u": f_e2cab98b_pick_u,
  "src/main.mtek::second": f_e2cab98b_second,
  "src/main.mtek::nth": f_e2cab98b_nth,
  "src/main.mtek::column": f_e2cab98b_column,
  "src/main.mtek::last_column": f_e2cab98b_last_column,
  "src/main.mtek::lift": f_e2cab98b_lift,
  "src/main.mtek::count_down": f_e2cab98b_count_down,
  "src/main.mtek::zyx": f_e2cab98b_zyx,
  "src/main.mtek::xxyy": f_e2cab98b_xxyy,
  "src/main.mtek::rgb": f_e2cab98b_rgb,
  "src/main.mtek::alpha": f_e2cab98b_alpha,
  "src/main.mtek::quat_w": f_e2cab98b_quat_w,
  "src/main.mtek::sum_to": f_e2cab98b_sum_to,
  "src/main.mtek::count_u": f_e2cab98b_count_u,
  "src/main.mtek::sum_each": f_e2cab98b_sum_each,
  "src/main.mtek::classify": f_e2cab98b_classify,
  "src/main.mtek::xor": f_e2cab98b_xor,
  "src/main.mtek::in_range": f_e2cab98b_in_range,
  "src/main.mtek::make_wave": f_e2cab98b_make_wave,
  "src/main.mtek::wave_at": f_e2cab98b_wave_at,
  "src/main.mtek::wave_sum": f_e2cab98b_wave_sum,
  "src/main.mtek::rotate": f_e2cab98b_rotate,
  "src/main.mtek::transform": f_e2cab98b_transform,
  "src/main.mtek::spin": f_e2cab98b_spin,
  "src/main.mtek::hypot": f_e2cab98b_hypot,
  "src/main.mtek::half_way": f_e2cab98b_half_way,
  "src/main.mtek::tinted": f_e2cab98b_tinted,
  "src/main.mtek::wave": f_e2cab98b_wave,
  "src/main.mtek::decay": f_e2cab98b_decay,
  "src/main.mtek::pulse": f_e2cab98b_pulse,
  "src/main.mtek::combined": f_e2cab98b_combined,
  "src/main.mtek::doubled": f_e2cab98b_doubled,
  "src/main.mtek::add_wrapped": f_e2cab98b_add_wrapped,
  "src/main.mtek::reach_all": f_e2cab98b_reach_all,
  "src/util.mtek::scale": f_fb30ea10_scale,
  "src/util.mtek::wrap_add": f_fb30ea10_wrap_add,
  "src/util.mtek::pulse": f_fb30ea10_pulse,
  "src/util.mtek::util_pulse": f_fb30ea10_util_pulse,
};

// scene Functions (src/main.mtek::Functions): the initialisation order of spec/scenes.md section 11
function s_Functions_init(ctx) {
  // camera Main (src/main.mtek::Functions.Main), active
  ctx.setCamera("position", { x: 0.0, y: 0.0, z: 5.0 });
  ctx.setCamera("rotation", { x: 0.0, y: 0.0, z: 0.0, w: 1.0 });
  ctx.setCamera("projection.fov_y", 0.8999999761581421);
  ctx.setCamera("projection.near", 0.10000000149011612);
  ctx.setCamera("projection.far", 1000.0);
}

export const scenes = {
  Functions: {
    init: s_Functions_init,
    update: null,
    fixedUpdate: null,
    entityUpdate: [],
    entityFixedUpdate: [],
    events: {},
    bindings: [],
  },
};

export const prefabs = {};

export default { abi, baseUrl, manifestUrl, writers, functions, scenes, prefabs };
//# sourceMappingURL=app.js.map
