// Generated by mtek 0.1.0-dev for language 0.1. Do not edit.
import type { MtekProgram } from "./runtime.js";
export interface Inputs {}
declare const program: MtekProgram<Inputs>;
export default program;
export { mountMtek } from "./runtime.js";
