[package]
name = "mtek-cli"
description = "The `mtek` command line tool."
edition.workspace = true
rust-version.workspace = true
version.workspace = true
publish.workspace = true

[[bin]]
name = "mtek"
path = "src/main.rs"

[dependencies]
mtek-compiler = { path = "../mtek-compiler" }

[lints]
workspace = true
