//! A small JavaScript AST and its deterministic printer (`spec/compiler-architecture.md`
//! section 6): exactly the constructs the emitted program module needs, printed with two-space
//! indentation, one statement per line, `\n` line ends and a final line break.
//!
//! Strings, comments, property keys and member names go through the escaping helpers of
//! [`super::printer`], so text that originates in the program (names, paths) can never break
//! out of the construct it belongs to. Identifiers are generated by the compiler and must be
//! plain identifier names; the printer writes them as given. Operators are printed with the
//! parentheses JavaScript's precedence requires, plus one readability rule: an operator
//! operand of a bitwise operator is grouped (`(a + b) | 0`).
//!
//! The printer records, for every statement that carries a source [`Span`] and every
//! expression wrapped in [`Expr::Spanned`], the generated line and column it starts at
//! ([`Mapping`]); [`super::source_map`] turns them into `app.js.map`. The mappings are sorted
//! by position, and where several start at the same position the first one recorded (the
//! statement, or the outermost expression) is kept. Generated code is ASCII (every non-ASCII
//! character is escaped), so a column counts bytes, Unicode scalar values and UTF-16 units
//! alike.

use crate::source::Span;

use super::printer::{Printer, is_identifier_name, line_comment, property_key, string_literal};

/// A number literal.
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum Number {
    /// A binary32 value, printed as the shortest decimal that reads back as the same value
    /// **when read as a JavaScript (binary64) number** (`spec/compiler-architecture.md`
    /// section 6): the JavaScript constant is exactly the compiler's binary32 value.
    F32(f32),
    I32(i32),
    U32(u32),
}

impl Number {
    /// The literal text. Non-finite values (which no constant expression produces) print as
    /// `NaN`, `Infinity` and `-Infinity`.
    #[must_use]
    pub fn text(self) -> String {
        match self {
            Number::F32(value) => {
                let wide = f64::from(value);
                if wide.is_nan() {
                    "NaN".to_owned()
                } else if wide.is_infinite() {
                    if wide > 0.0 { "Infinity" } else { "-Infinity" }.to_owned()
                } else {
                    // `{:?}` of an `f64` is its shortest round-trip text (`1.0`,
                    // `0.10000000149011612`, `1e-7`); all are valid JavaScript literals.
                    format!("{wide:?}")
                }
            }
            Number::I32(value) => value.to_string(),
            Number::U32(value) => value.to_string(),
        }
    }

    /// Whether the literal text starts with a minus sign (it then binds like a prefix
    /// operator).
    fn is_negative(self) -> bool {
        match self {
            Number::F32(value) => value.is_sign_negative() && !value.is_nan(),
            Number::I32(value) => value < 0,
            Number::U32(_) => false,
        }
    }
}

/// An expression.
#[derive(Clone, Debug, PartialEq)]
pub enum Expr {
    /// A compiler-generated identifier (`ctx`, `w_builtin_MtekFrame`, `import`).
    Ident(String),
    /// A string literal (escaped by the printer).
    Str(String),
    Num(Number),
    Bool(bool),
    Null,
    /// `object.name`, or `object["name"]` when `name` is not an identifier name.
    Member(Box<Expr>, String),
    /// `object[index]` with a constant index.
    Index(Box<Expr>, u32),
    /// `object[index]` with a computed index.
    Subscript(Box<Expr>, Box<Expr>),
    /// `callee(arguments)`.
    Call(Box<Expr>, Vec<Expr>),
    /// `new callee(arguments)`.
    New(Box<Expr>, Vec<Expr>),
    /// An object literal; `multiline` prints one property per line (only where the
    /// expression ends a statement or a property).
    Object {
        properties: Vec<(String, Expr)>,
        multiline: bool,
    },
    /// An array literal, on one line.
    Array(Vec<Expr>),
    /// A prefix operator: `-x`, `!x`.
    Unary(&'static str, Box<Expr>),
    /// A binary operator (`+`, `|`, `>>>`, `===`, `&&`, …), left-associative.
    Binary(&'static str, Box<Expr>, Box<Expr>),
    /// The inner expression, mapped to a Mtek span in the source map where it starts.
    Spanned(Box<Expr>, Span),
}

/// The precedence of a primary expression (identifier, literal).
const PRIMARY: u8 = 20;
/// Member access, calls, `new` with arguments.
const POSTFIX: u8 = 18;
/// Prefix operators (and negative number literals).
const PREFIX: u8 = 14;

/// Whether `op` is a bitwise or shift operator.
fn is_bitwise(op: &str) -> bool {
    matches!(op, "|" | "&" | "^" | "<<" | ">>" | ">>>")
}

/// The precedence of a binary operator (higher binds tighter).
fn binary_precedence(op: &str) -> u8 {
    match op {
        "*" | "/" | "%" => 12,
        "+" | "-" => 11,
        "<<" | ">>" | ">>>" => 10,
        "<" | "<=" | ">" | ">=" => 9,
        "===" | "!==" | "==" | "!=" => 8,
        "&" => 7,
        "^" => 6,
        "|" => 5,
        "&&" => 4,
        "||" => 3,
        _ => 1,
    }
}

impl Expr {
    /// A generated identifier.
    #[must_use]
    pub fn ident(name: &str) -> Expr {
        Expr::Ident(name.to_owned())
    }

    /// A string literal.
    #[must_use]
    pub fn string(text: &str) -> Expr {
        Expr::Str(text.to_owned())
    }

    /// `self.name`.
    #[must_use]
    pub fn member(self, name: &str) -> Expr {
        Expr::Member(Box::new(self), name.to_owned())
    }

    /// `self[index]`.
    #[must_use]
    pub fn index(self, index: u32) -> Expr {
        Expr::Index(Box::new(self), index)
    }

    /// `self(arguments)`.
    #[must_use]
    pub fn call(self, arguments: Vec<Expr>) -> Expr {
        Expr::Call(Box::new(self), arguments)
    }

    /// `left op right`.
    #[must_use]
    pub fn binary(op: &'static str, left: Expr, right: Expr) -> Expr {
        Expr::Binary(op, Box::new(left), Box::new(right))
    }

    /// `op operand`.
    #[must_use]
    pub fn unary(op: &'static str, operand: Expr) -> Expr {
        Expr::Unary(op, Box::new(operand))
    }

    /// `self`, mapped to `span`.
    #[must_use]
    pub fn spanned(self, span: Span) -> Expr {
        Expr::Spanned(Box::new(self), span)
    }

    /// An object literal printed on one line.
    #[must_use]
    pub fn object(properties: Vec<(String, Expr)>) -> Expr {
        Expr::Object {
            properties,
            multiline: false,
        }
    }

    /// An object literal printed one property per line.
    #[must_use]
    pub fn object_lines(properties: Vec<(String, Expr)>) -> Expr {
        Expr::Object {
            properties,
            multiline: true,
        }
    }

    /// How tightly the printed expression binds.
    fn precedence(&self) -> u8 {
        match self {
            Expr::Num(number) if number.is_negative() => PREFIX,
            Expr::Ident(_)
            | Expr::Str(_)
            | Expr::Num(_)
            | Expr::Bool(_)
            | Expr::Null
            | Expr::Object { .. }
            | Expr::Array(_) => PRIMARY,
            Expr::Member(..)
            | Expr::Index(..)
            | Expr::Subscript(..)
            | Expr::Call(..)
            | Expr::New(..) => POSTFIX,
            Expr::Unary(..) => PREFIX,
            Expr::Binary(op, ..) => binary_precedence(op),
            Expr::Spanned(inner, _) => inner.precedence(),
        }
    }

    /// Whether the printed text starts with `-` (so `-` before it needs parentheses).
    fn starts_with_minus(&self) -> bool {
        match self {
            Expr::Num(number) => number.is_negative(),
            Expr::Unary(op, _) => *op == "-",
            Expr::Binary(_, left, _) => left.starts_with_minus(),
            Expr::Spanned(inner, _) => inner.starts_with_minus(),
            _ => false,
        }
    }

    /// Whether the expression is a binary operator.
    fn is_binary(&self) -> bool {
        match self {
            Expr::Binary(..) => true,
            Expr::Spanned(inner, _) => inner.is_binary(),
            _ => false,
        }
    }

    /// Whether the expression is a number literal (member access on `1.x` would not parse).
    fn is_number(&self) -> bool {
        match self {
            Expr::Num(_) => true,
            Expr::Spanned(inner, _) => inner.is_number(),
            _ => false,
        }
    }
}

/// A statement.
#[derive(Clone, Debug, PartialEq)]
pub enum Stmt {
    /// A `//` comment (escaped: it stays on one line).
    Comment(String),
    /// An empty line.
    Blank,
    /// `const name = value;`.
    Const {
        name: String,
        value: Expr,
        span: Option<Span>,
    },
    /// `let name = value;`.
    Let {
        name: String,
        value: Expr,
        span: Option<Span>,
    },
    /// `target = value;`.
    Assign {
        target: Expr,
        value: Expr,
        span: Option<Span>,
    },
    /// `expr;`.
    Expr { expr: Expr, span: Option<Span> },
    /// `if (c0) { … } else if (c1) { … } else { … }`.
    If {
        branches: Vec<(Expr, Vec<Stmt>)>,
        otherwise: Option<Vec<Stmt>>,
        span: Option<Span>,
    },
    /// `for (let var = start[, limit = end]; var < limit; var++) { body }`: a counted loop
    /// whose bound is evaluated once. Without `limit`, `end` (a constant) is the bound.
    ForRange {
        var: String,
        start: Expr,
        limit: Option<String>,
        end: Expr,
        body: Vec<Stmt>,
        span: Option<Span>,
    },
    /// `for (const var of iterable) { body }`.
    ForOf {
        var: String,
        iterable: Expr,
        body: Vec<Stmt>,
        span: Option<Span>,
    },
    /// `return;` or `return value;`.
    Return {
        value: Option<Expr>,
        span: Option<Span>,
    },
    /// `break;`.
    Break { span: Option<Span> },
    /// `continue;`.
    Continue { span: Option<Span> },
    /// `{ body }`.
    Block { body: Vec<Stmt> },
    /// `function name(params) { body }`.
    Function {
        name: String,
        params: Vec<String>,
        body: Vec<Stmt>,
        span: Option<Span>,
    },
    /// Pre-printed code (the block writers of `spec/gpu-layout.md` section 7, emitted by
    /// [`super::writers`]), written line by line at the current indentation.
    Verbatim(String),
}

/// A module-level item.
#[derive(Clone, Debug, PartialEq)]
pub enum Item {
    Stmt(Stmt),
    /// `import * as name from "from";`.
    ImportNamespace {
        name: String,
        from: String,
    },
    /// `export { names } from "from";`.
    ExportFrom {
        names: Vec<String>,
        from: String,
    },
    /// `export const name = value;`.
    ExportConst {
        name: String,
        value: Expr,
    },
    /// `export default value;`.
    ExportDefault(Expr),
    /// `//# sourceMappingURL=url`, the last line of a module with a source map.
    SourceMappingUrl(String),
}

/// A program module.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Module {
    pub items: Vec<Item>,
}

/// Where a statement or expression with a source origin starts in the printed text.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Mapping {
    /// 0-based generated line.
    pub line: u32,
    /// 0-based generated column.
    pub column: u32,
    /// The Mtek source the statement or expression originates from.
    pub span: Span,
}

/// A printed module and its mappings, in text order.
#[derive(Clone, Debug, PartialEq)]
pub struct JsModule {
    pub text: String,
    pub mappings: Vec<Mapping>,
}

/// Prints `module`.
#[must_use]
pub fn print(module: &Module) -> JsModule {
    let mut out = Out {
        p: Printer::new(),
        mappings: Vec::new(),
    };
    for item in &module.items {
        out.item(item);
    }
    let mut mappings = out.mappings;
    // Stable: of several mappings at one position, the first recorded stays first.
    mappings.sort_by_key(|m| (m.line, m.column));
    mappings.dedup_by_key(|m| (m.line, m.column));
    JsModule {
        text: out.p.finish(),
        mappings,
    }
}

/// The single-line text of `expr` (multiline objects are printed on one line here).
#[must_use]
pub fn inline(expr: &Expr) -> String {
    let mut text = String::new();
    write(expr, &mut text, &mut Vec::new());
    text
}

/// Appends the text of `expr` to `out`, recording where each spanned expression starts.
fn write(expr: &Expr, out: &mut String, marks: &mut Vec<(usize, Span)>) {
    match expr {
        Expr::Spanned(inner, span) => {
            marks.push((out.len(), *span));
            write(inner, out, marks);
        }
        Expr::Ident(name) => out.push_str(name),
        Expr::Str(text) => out.push_str(&string_literal(text)),
        Expr::Num(number) => out.push_str(&number.text()),
        Expr::Bool(value) => out.push_str(if *value { "true" } else { "false" }),
        Expr::Null => out.push_str("null"),
        Expr::Member(object, name) => {
            postfix_base(object, out, marks);
            if is_identifier_name(name) {
                out.push('.');
                out.push_str(name);
            } else {
                out.push('[');
                out.push_str(&string_literal(name));
                out.push(']');
            }
        }
        Expr::Index(object, index) => {
            postfix_base(object, out, marks);
            out.push('[');
            out.push_str(&index.to_string());
            out.push(']');
        }
        Expr::Subscript(object, index) => {
            postfix_base(object, out, marks);
            out.push('[');
            write(index, out, marks);
            out.push(']');
        }
        Expr::Call(callee, arguments) => {
            postfix_base(callee, out, marks);
            out.push('(');
            list(arguments, out, marks);
            out.push(')');
        }
        Expr::New(callee, arguments) => {
            out.push_str("new ");
            postfix_base(callee, out, marks);
            out.push('(');
            list(arguments, out, marks);
            out.push(')');
        }
        Expr::Object { properties, .. } if properties.is_empty() => out.push_str("{}"),
        Expr::Object { properties, .. } => {
            out.push_str("{ ");
            for (index, (key, value)) in properties.iter().enumerate() {
                if index > 0 {
                    out.push_str(", ");
                }
                if is_shorthand(key, value) {
                    out.push_str(key);
                } else {
                    out.push_str(&property_key(key));
                    out.push_str(": ");
                    write(value, out, marks);
                }
            }
            out.push_str(" }");
        }
        Expr::Array(items) => {
            out.push('[');
            list(items, out, marks);
            out.push(']');
        }
        Expr::Unary(op, operand) => {
            out.push_str(op);
            let paren =
                operand.precedence() < PREFIX || (*op == "-" && operand.starts_with_minus());
            operand_in(operand, paren, out, marks);
        }
        Expr::Binary(op, left, right) => {
            let precedence = binary_precedence(op);
            // Readability: an operator operand of a bitwise operator is always grouped,
            // `(a + b) | 0` rather than the equivalent `a + b | 0`.
            let group = is_bitwise(op);
            let left_paren = left.precedence() < precedence || (group && left.is_binary());
            let right_paren = right.precedence() <= precedence || (group && right.is_binary());
            operand_in(left, left_paren, out, marks);
            out.push(' ');
            out.push_str(op);
            out.push(' ');
            operand_in(right, right_paren, out, marks);
        }
    }
}

/// The object of a member access or the callee of a call, parenthesised when needed.
fn postfix_base(base: &Expr, out: &mut String, marks: &mut Vec<(usize, Span)>) {
    operand_in(
        base,
        base.precedence() < POSTFIX || base.is_number(),
        out,
        marks,
    );
}

fn operand_in(expr: &Expr, paren: bool, out: &mut String, marks: &mut Vec<(usize, Span)>) {
    if paren {
        out.push('(');
        write(expr, out, marks);
        out.push(')');
    } else {
        write(expr, out, marks);
    }
}

fn list(items: &[Expr], out: &mut String, marks: &mut Vec<(usize, Span)>) {
    for (index, item) in items.iter().enumerate() {
        if index > 0 {
            out.push_str(", ");
        }
        write(item, out, marks);
    }
}

/// `key` alone stands for `key: key` when the value is the identifier `key`.
fn is_shorthand(key: &str, value: &Expr) -> bool {
    matches!(value, Expr::Ident(name) if name == key && is_identifier_name(key))
}

/// One piece of a printed line: text, or an expression whose spans are mapped.
enum Part<'a> {
    Text(&'a str),
    Expr(&'a Expr),
}

struct Out {
    p: Printer,
    mappings: Vec<Mapping>,
}

impl Out {
    fn map(&mut self, span: Option<Span>) {
        if let Some(span) = span {
            self.mark(0, span);
        }
    }

    /// A mapping at `offset` columns after the indentation of the next line.
    fn mark(&mut self, offset: usize, span: Span) {
        self.mappings.push(Mapping {
            line: u32::try_from(self.p.line_count()).unwrap_or(u32::MAX),
            column: u32::try_from(self.p.indent_width() + offset).unwrap_or(u32::MAX),
            span,
        });
    }

    /// Writes one line made of `parts`, mapping every spanned expression in it.
    fn line(&mut self, parts: &[Part<'_>]) {
        let mut text = String::new();
        let mut marks = Vec::new();
        for part in parts {
            match part {
                Part::Text(piece) => text.push_str(piece),
                Part::Expr(expr) => write(expr, &mut text, &mut marks),
            }
        }
        for (offset, span) in marks {
            self.mark(offset, span);
        }
        self.p.line(&text);
    }

    fn item(&mut self, item: &Item) {
        match item {
            Item::Stmt(stmt) => self.stmt(stmt),
            Item::ImportNamespace { name, from } => self.p.line(&format!(
                "import * as {name} from {};",
                string_literal(from)
            )),
            Item::ExportFrom { names, from } => self.p.line(&format!(
                "export {{ {} }} from {};",
                names.join(", "),
                string_literal(from)
            )),
            Item::ExportConst { name, value } => {
                self.value(&format!("export const {name} = "), value, ";");
            }
            Item::ExportDefault(value) => self.value("export default ", value, ";"),
            Item::SourceMappingUrl(url) => {
                // Only URL-safe characters may follow the pragma; anything else is dropped.
                let safe: String = url
                    .chars()
                    .filter(|c| c.is_ascii_alphanumeric() || "._-/".contains(*c))
                    .collect();
                self.p.line(&format!("//# sourceMappingURL={safe}"));
            }
        }
    }

    fn body(&mut self, body: &[Stmt]) {
        self.p.indent();
        for inner in body {
            self.stmt(inner);
        }
        self.p.dedent();
    }

    fn stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Comment(text) => self.p.line(&line_comment(text)),
            Stmt::Blank => self.p.blank(),
            Stmt::Const { name, value, span } => {
                self.map(*span);
                self.value(&format!("const {name} = "), value, ";");
            }
            Stmt::Let { name, value, span } => {
                self.map(*span);
                self.value(&format!("let {name} = "), value, ";");
            }
            Stmt::Assign {
                target,
                value,
                span,
            } => {
                self.map(*span);
                self.line(&[
                    Part::Expr(target),
                    Part::Text(" = "),
                    Part::Expr(value),
                    Part::Text(";"),
                ]);
            }
            Stmt::Expr { expr, span } => {
                self.map(*span);
                self.value("", expr, ";");
            }
            Stmt::If {
                branches,
                otherwise,
                span,
            } => {
                self.map(*span);
                // An `else if` chain is a loop here, not recursion.
                for (index, (cond, body)) in branches.iter().enumerate() {
                    let head = if index == 0 { "if (" } else { "} else if (" };
                    self.line(&[Part::Text(head), Part::Expr(cond), Part::Text(") {")]);
                    self.body(body);
                }
                if let Some(body) = otherwise {
                    self.p.line("} else {");
                    self.body(body);
                }
                self.p.line("}");
            }
            Stmt::ForRange {
                var,
                start,
                limit,
                end,
                body,
                span,
            } => {
                self.map(*span);
                let head = format!("for (let {var} = ");
                match limit {
                    Some(limit) => {
                        let middle = format!(", {limit} = ");
                        let tail = format!("; {var} < {limit}; {var}++) {{");
                        self.line(&[
                            Part::Text(&head),
                            Part::Expr(start),
                            Part::Text(&middle),
                            Part::Expr(end),
                            Part::Text(&tail),
                        ]);
                    }
                    None => {
                        let middle = format!("; {var} < ");
                        let tail = format!("; {var}++) {{");
                        self.line(&[
                            Part::Text(&head),
                            Part::Expr(start),
                            Part::Text(&middle),
                            Part::Expr(end),
                            Part::Text(&tail),
                        ]);
                    }
                }
                self.body(body);
                self.p.line("}");
            }
            Stmt::ForOf {
                var,
                iterable,
                body,
                span,
            } => {
                self.map(*span);
                let head = format!("for (const {var} of ");
                self.line(&[Part::Text(&head), Part::Expr(iterable), Part::Text(") {")]);
                self.body(body);
                self.p.line("}");
            }
            Stmt::Return { value, span } => {
                self.map(*span);
                match value {
                    Some(value) => self.value("return ", value, ";"),
                    None => self.p.line("return;"),
                }
            }
            Stmt::Break { span } => {
                self.map(*span);
                self.p.line("break;");
            }
            Stmt::Continue { span } => {
                self.map(*span);
                self.p.line("continue;");
            }
            Stmt::Block { body } => {
                self.p.line("{");
                self.body(body);
                self.p.line("}");
            }
            Stmt::Function {
                name,
                params,
                body,
                span,
            } => {
                self.map(*span);
                self.p
                    .line(&format!("function {name}({}) {{", params.join(", ")));
                self.body(body);
                self.p.line("}");
            }
            Stmt::Verbatim(text) => self.p.verbatim(text),
        }
    }

    /// `prefix value suffix`, spreading a multiline object over several lines.
    fn value(&mut self, prefix: &str, value: &Expr, suffix: &str) {
        match value {
            Expr::Object {
                properties,
                multiline: true,
            } if !properties.is_empty() => {
                self.p.line(&format!("{prefix}{{"));
                self.p.indent();
                for (key, inner) in properties {
                    if is_shorthand(key, inner) {
                        self.p.line(&format!("{key},"));
                    } else {
                        self.value(&format!("{}: ", property_key(key)), inner, ",");
                    }
                }
                self.p.dedent();
                self.p.line(&format!("}}{suffix}"));
            }
            _ => self.line(&[Part::Text(prefix), Part::Expr(value), Part::Text(suffix)]),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::source::FileId;

    #[test]
    fn f32_literals_are_exactly_the_binary32_value_read_as_binary64() {
        assert_eq!(Number::F32(1.0).text(), "1.0");
        assert_eq!(Number::F32(0.5).text(), "0.5");
        assert_eq!(Number::F32(0.1).text(), "0.10000000149011612");
        assert_eq!(Number::F32(-9.81).text(), "-9.8100004196167");
        assert_eq!(Number::F32(1e-7).text(), "1.0000000116860974e-7");
        assert_eq!(Number::F32(-0.0).text(), "-0.0");
        assert_eq!(Number::F32(f32::NAN).text(), "NaN");
        assert_eq!(Number::F32(f32::NEG_INFINITY).text(), "-Infinity");
        assert_eq!(Number::I32(-7).text(), "-7");
        assert_eq!(Number::U32(4_294_967_295).text(), "4294967295");
        // The extremes: the largest finite value, the smallest normal and subnormal.
        assert_eq!(Number::F32(f32::MAX).text(), "3.4028234663852886e38");
        assert_eq!(
            Number::F32(f32::MIN_POSITIVE).text(),
            "1.1754943508222875e-38"
        );
        assert_eq!(
            Number::F32(f32::from_bits(1)).text(),
            "1.401298464324817e-45"
        );
        assert_eq!(Number::F32(16_777_217.0).text(), "16777216.0");
        for v in [
            0.1f32,
            1e-7,
            3.402_823_5e38,
            0.014_443_844,
            f32::from_bits(1),
            f32::from_bits(0x007f_ffff),
            f32::MIN_POSITIVE,
            -f32::MAX,
            1.0e10,
            123_456_790.0,
        ] {
            let back: f64 = Number::F32(v).text().parse().expect("number");
            assert_eq!(back, f64::from(v), "{v}");
        }
    }

    #[test]
    fn literals_of_every_binary32_bit_pattern_family_read_back_exactly() {
        // A deterministic sweep over exponents and mantissas: the printed text, read as a
        // binary64 number, is exactly the binary32 value (so `Math.fround` is the identity).
        let mut state = 0x9e37_79b9_u32;
        for _ in 0..20_000 {
            state ^= state << 13;
            state ^= state >> 17;
            state ^= state << 5;
            let value = f32::from_bits(state);
            if !value.is_finite() {
                continue;
            }
            let text = Number::F32(value).text();
            let back: f64 = text.parse().expect("number");
            assert_eq!(back.to_bits(), f64::from(value).to_bits(), "{text}");
            // At most 17 significant digits (binary64 never needs more).
            let mantissa = text.trim_start_matches('-').split('e').next().unwrap_or("");
            let significant = mantissa
                .chars()
                .filter(char::is_ascii_digit)
                .skip_while(|c| *c == '0')
                .collect::<String>();
            assert!(significant.trim_end_matches('0').len() <= 17, "{text}");
        }
    }

    #[test]
    fn expressions_print_on_one_line_with_escaping() {
        let call = Expr::ident("ctx").member("setParam").call(vec![
            Expr::ident("e0"),
            Expr::string("a\"b\n"),
            Expr::object(vec![
                ("r".to_owned(), Expr::Num(Number::F32(1.0))),
                ("a-b".to_owned(), Expr::Bool(true)),
            ]),
        ]);
        assert_eq!(
            inline(&call),
            r#"ctx.setParam(e0, "a\"b\n", { r: 1.0, "a-b": true })"#
        );
        assert_eq!(inline(&Expr::object(vec![])), "{}");
        assert_eq!(
            inline(&Expr::Array(vec![Expr::Null, Expr::Null])),
            "[null, null]"
        );
        assert_eq!(inline(&Expr::ident("ctx").member("e").index(3)), "ctx.e[3]");
        assert_eq!(
            inline(&Expr::New(
                Box::new(Expr::ident("URL")),
                vec![Expr::string("./")]
            )),
            r#"new URL("./")"#
        );
    }

    #[test]
    fn operators_get_exactly_the_parentheses_precedence_needs() {
        let a = || Expr::ident("a");
        let b = || Expr::ident("b");
        let c = || Expr::ident("c");
        let num = |v: i32| Expr::Num(Number::I32(v));
        // (a + b) | 0
        let wrap = Expr::binary("|", Expr::binary("+", a(), b()), num(0));
        assert_eq!(inline(&wrap), "(a + b) | 0");
        // a - (b - c) keeps its grouping, (a - b) - c needs none.
        assert_eq!(
            inline(&Expr::binary("-", a(), Expr::binary("-", b(), c()))),
            "a - (b - c)"
        );
        assert_eq!(
            inline(&Expr::binary("-", Expr::binary("-", a(), b()), c())),
            "a - b - c"
        );
        // Multiplication inside addition needs nothing, the reverse needs parentheses.
        assert_eq!(
            inline(&Expr::binary("+", a(), Expr::binary("*", b(), c()))),
            "a + b * c"
        );
        assert_eq!(
            inline(&Expr::binary("*", Expr::binary("+", a(), b()), c())),
            "(a + b) * c"
        );
        // Unary minus: -x | 0, -(-1), -(a + b), - -x never prints `--`.
        assert_eq!(
            inline(&Expr::binary("|", Expr::unary("-", a()), num(0))),
            "-a | 0"
        );
        assert_eq!(inline(&Expr::unary("-", num(-1))), "-(-1)");
        assert_eq!(inline(&Expr::unary("-", Expr::unary("-", a()))), "-(-a)");
        assert_eq!(
            inline(&Expr::unary("-", Expr::binary("+", a(), b()))),
            "-(a + b)"
        );
        assert_eq!(
            inline(&Expr::unary("!", Expr::binary("&&", a(), b()))),
            "!(a && b)"
        );
        assert_eq!(inline(&Expr::binary("-", a(), num(-1))), "a - -1");
        // Member access on an operator result or a number is parenthesised.
        assert_eq!(
            inline(&Expr::binary("+", a(), b()).member("x")),
            "(a + b).x"
        );
        assert_eq!(inline(&num(1).member("x")), "(1).x");
        assert_eq!(
            inline(&Expr::Subscript(
                Box::new(a()),
                Box::new(Expr::binary("+", b(), c()))
            )),
            "a[b + c]"
        );
        // Logical operators: && binds tighter than ||.
        assert_eq!(
            inline(&Expr::binary("&&", Expr::binary("||", a(), b()), c())),
            "(a || b) && c"
        );
        assert_eq!(
            inline(&Expr::binary("||", a(), Expr::binary("&&", b(), c()))),
            "a || b && c"
        );
        // Comparisons inside equality, shifts after additions.
        assert_eq!(
            inline(&Expr::binary(
                "===",
                Expr::binary("<", a(), b()),
                Expr::Bool(true)
            )),
            "a < b === true"
        );
        assert_eq!(
            inline(&Expr::binary(">>>", Expr::binary("-", a(), b()), num(0))),
            "(a - b) >>> 0"
        );
        // Spans do not change the text.
        let span = Span::new(FileId(0), 0, 1);
        assert_eq!(
            inline(
                &Expr::binary("|", Expr::binary("+", a(), b()).spanned(span), num(0)).spanned(span)
            ),
            "(a + b) | 0"
        );
    }

    #[test]
    fn statements_print_with_blocks_and_expression_mappings() {
        let at = |start| Span::new(FileId(0), start, start + 1);
        let module = Module {
            items: vec![Item::Stmt(Stmt::Function {
                name: "f".to_owned(),
                params: vec!["ctx".to_owned(), "a_x".to_owned()],
                body: vec![
                    Stmt::Let {
                        name: "l_t".to_owned(),
                        value: Expr::Num(Number::I32(0)).spanned(at(10)),
                        span: Some(at(1)),
                    },
                    Stmt::ForRange {
                        var: "l_i".to_owned(),
                        start: Expr::Num(Number::I32(0)).spanned(at(11)),
                        limit: Some("t_0".to_owned()),
                        end: Expr::ident("a_x").spanned(at(12)),
                        body: vec![Stmt::If {
                            branches: vec![
                                (
                                    Expr::binary(
                                        "===",
                                        Expr::ident("l_i"),
                                        Expr::Num(Number::I32(2)),
                                    )
                                    .spanned(at(13)),
                                    vec![Stmt::Continue { span: Some(at(3)) }],
                                ),
                                (
                                    Expr::unary("!", Expr::Bool(true)),
                                    vec![Stmt::Break { span: None }],
                                ),
                            ],
                            otherwise: Some(vec![Stmt::Assign {
                                target: Expr::ident("l_t"),
                                value: Expr::binary(
                                    "|",
                                    Expr::binary("+", Expr::ident("l_t"), Expr::ident("l_i")),
                                    Expr::Num(Number::I32(0)),
                                )
                                .spanned(at(14)),
                                span: Some(at(4)),
                            }]),
                            span: Some(at(2)),
                        }],
                        span: Some(at(5)),
                    },
                    Stmt::ForRange {
                        var: "l_j".to_owned(),
                        start: Expr::Num(Number::U32(0)),
                        limit: None,
                        end: Expr::Num(Number::U32(4)),
                        body: vec![],
                        span: None,
                    },
                    Stmt::ForOf {
                        var: "l_w".to_owned(),
                        iterable: Expr::Array(vec![Expr::Num(Number::F32(0.5))]),
                        body: vec![Stmt::Block { body: vec![] }],
                        span: None,
                    },
                    Stmt::Return {
                        value: Some(Expr::ident("l_t").spanned(at(15))),
                        span: Some(at(6)),
                    },
                ],
                span: Some(at(0)),
            })],
        };
        let printed = print(&module);
        assert_eq!(
            printed.text,
            "function f(ctx, a_x) {\n\
             \x20 let l_t = 0;\n\
             \x20 for (let l_i = 0, t_0 = a_x; l_i < t_0; l_i++) {\n\
             \x20   if (l_i === 2) {\n\
             \x20     continue;\n\
             \x20   } else if (!true) {\n\
             \x20     break;\n\
             \x20   } else {\n\
             \x20     l_t = (l_t + l_i) | 0;\n\
             \x20   }\n\
             \x20 }\n\
             \x20 for (let l_j = 0; l_j < 4; l_j++) {\n\
             \x20 }\n\
             \x20 for (const l_w of [0.5]) {\n\
             \x20   {\n\
             \x20   }\n\
             \x20 }\n\
             \x20 return l_t;\n\
             }\n"
        );
        let positions: Vec<(u32, u32, u32)> = printed
            .mappings
            .iter()
            .map(|m| (m.line, m.column, m.span.start))
            .collect();
        assert_eq!(
            positions,
            [
                (0, 0, 0),
                (1, 2, 1),
                (1, 12, 10),
                (2, 2, 5),
                (2, 17, 11),
                (2, 26, 12),
                (3, 4, 2),
                (3, 8, 13),
                (4, 6, 3),
                (8, 6, 4),
                (8, 12, 14),
                (17, 2, 6),
                (17, 9, 15),
            ]
        );
    }

    #[test]
    fn modules_print_deterministically_with_mappings() {
        let span = Span::new(FileId(0), 4, 9);
        let module = Module {
            items: vec![
                Item::Stmt(Stmt::Comment("header\nbreak".to_owned())),
                Item::ImportNamespace {
                    name: "rt".to_owned(),
                    from: "./runtime.js".to_owned(),
                },
                Item::ExportFrom {
                    names: vec!["mountMtek".to_owned()],
                    from: "./runtime.js".to_owned(),
                },
                Item::Stmt(Stmt::Blank),
                Item::Stmt(Stmt::Function {
                    name: "f".to_owned(),
                    params: vec!["ctx".to_owned()],
                    body: vec![
                        Stmt::Const {
                            name: "e0".to_owned(),
                            value: Expr::ident("ctx").member("e").index(0),
                            span: Some(span),
                        },
                        Stmt::Expr {
                            expr: Expr::ident("ctx").member("go").call(vec![]),
                            span: None,
                        },
                    ],
                    span: None,
                }),
                Item::ExportConst {
                    name: "scenes".to_owned(),
                    value: Expr::object_lines(vec![(
                        "Demo".to_owned(),
                        Expr::object_lines(vec![
                            ("init".to_owned(), Expr::ident("f")),
                            ("events".to_owned(), Expr::object_lines(vec![])),
                        ]),
                    )]),
                },
                Item::ExportDefault(Expr::object(vec![(
                    "scenes".to_owned(),
                    Expr::ident("scenes"),
                )])),
            ],
        };
        let printed = print(&module);
        assert_eq!(
            printed.text,
            "// header?break\n\
             import * as rt from \"./runtime.js\";\n\
             export { mountMtek } from \"./runtime.js\";\n\
             \n\
             function f(ctx) {\n  const e0 = ctx.e[0];\n  ctx.go();\n}\n\
             export const scenes = {\n  Demo: {\n    init: f,\n    events: {},\n  },\n};\n\
             export default { scenes };\n"
        );
        assert_eq!(
            printed.mappings,
            [Mapping {
                line: 5,
                column: 2,
                span
            }]
        );
        assert_eq!(print(&module), printed);
    }
}
