//! A small JavaScript AST and its deterministic printer (`spec/compiler-architecture.md`
//! section 6): exactly the constructs the emitted program module needs, printed with two-space
//! indentation, one statement per line, `\n` line ends and a final line break.
//!
//! Strings, comments, property keys and member names go through the escaping helpers of
//! [`super::printer`], so text that originates in the program (names, paths) can never break
//! out of the construct it belongs to. Identifiers are generated by the compiler and must be
//! plain identifier names; the printer writes them as given.
//!
//! The printer records, for every statement that carries a source [`Span`], the generated line
//! and column it starts at ([`Mapping`]); [`super::source_map`] turns them into `app.js.map`.
//! Generated code is ASCII (every non-ASCII character is escaped), so a column counts bytes,
//! Unicode scalar values and UTF-16 units alike.

use crate::source::Span;

use super::printer::{
    Printer, is_identifier_name, line_comment, member_access, property_key, string_literal,
};

/// A number literal.
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum Number {
    /// A binary32 value, printed as the shortest decimal that reads back as the same value
    /// **when read as a JavaScript (binary64) number** (`spec/compiler-architecture.md`
    /// section 6): the JavaScript constant is exactly the compiler's binary32 value.
    F32(f32),
    I32(i32),
    U32(u32),
}

impl Number {
    /// The literal text. Non-finite values (which no constant expression produces) print as
    /// `NaN`, `Infinity` and `-Infinity`.
    #[must_use]
    pub fn text(self) -> String {
        match self {
            Number::F32(value) => {
                let wide = f64::from(value);
                if wide.is_nan() {
                    "NaN".to_owned()
                } else if wide.is_infinite() {
                    if wide > 0.0 { "Infinity" } else { "-Infinity" }.to_owned()
                } else {
                    // `{:?}` of an `f64` is its shortest round-trip text (`1.0`,
                    // `0.10000000149011612`, `1e-7`); all are valid JavaScript literals.
                    format!("{wide:?}")
                }
            }
            Number::I32(value) => value.to_string(),
            Number::U32(value) => value.to_string(),
        }
    }
}

/// An expression.
#[derive(Clone, Debug, PartialEq)]
pub enum Expr {
    /// A compiler-generated identifier (`ctx`, `w_builtin_MtekFrame`, `import`).
    Ident(String),
    /// A string literal (escaped by the printer).
    Str(String),
    Num(Number),
    Bool(bool),
    Null,
    /// `object.name`, or `object["name"]` when `name` is not an identifier name.
    Member(Box<Expr>, String),
    /// `object[index]`.
    Index(Box<Expr>, u32),
    /// `callee(arguments)`.
    Call(Box<Expr>, Vec<Expr>),
    /// `new callee(arguments)`.
    New(Box<Expr>, Vec<Expr>),
    /// An object literal; `multiline` prints one property per line (only where the
    /// expression ends a statement or a property).
    Object {
        properties: Vec<(String, Expr)>,
        multiline: bool,
    },
    /// An array literal, on one line.
    Array(Vec<Expr>),
}

impl Expr {
    /// A generated identifier.
    #[must_use]
    pub fn ident(name: &str) -> Expr {
        Expr::Ident(name.to_owned())
    }

    /// A string literal.
    #[must_use]
    pub fn string(text: &str) -> Expr {
        Expr::Str(text.to_owned())
    }

    /// `self.name`.
    #[must_use]
    pub fn member(self, name: &str) -> Expr {
        Expr::Member(Box::new(self), name.to_owned())
    }

    /// `self[index]`.
    #[must_use]
    pub fn index(self, index: u32) -> Expr {
        Expr::Index(Box::new(self), index)
    }

    /// `self(arguments)`.
    #[must_use]
    pub fn call(self, arguments: Vec<Expr>) -> Expr {
        Expr::Call(Box::new(self), arguments)
    }

    /// An object literal printed on one line.
    #[must_use]
    pub fn object(properties: Vec<(String, Expr)>) -> Expr {
        Expr::Object {
            properties,
            multiline: false,
        }
    }

    /// An object literal printed one property per line.
    #[must_use]
    pub fn object_lines(properties: Vec<(String, Expr)>) -> Expr {
        Expr::Object {
            properties,
            multiline: true,
        }
    }
}

/// A statement.
#[derive(Clone, Debug, PartialEq)]
pub enum Stmt {
    /// A `//` comment (escaped: it stays on one line).
    Comment(String),
    /// An empty line.
    Blank,
    /// `const name = value;`.
    Const {
        name: String,
        value: Expr,
        span: Option<Span>,
    },
    /// `expr;`.
    Expr { expr: Expr, span: Option<Span> },
    /// `function name(params) { body }`.
    Function {
        name: String,
        params: Vec<String>,
        body: Vec<Stmt>,
        span: Option<Span>,
    },
    /// Pre-printed code (the block writers of `spec/gpu-layout.md` section 7, emitted by
    /// [`super::writers`]), written line by line at the current indentation.
    Verbatim(String),
}

/// A module-level item.
#[derive(Clone, Debug, PartialEq)]
pub enum Item {
    Stmt(Stmt),
    /// `import * as name from "from";`.
    ImportNamespace {
        name: String,
        from: String,
    },
    /// `export { names } from "from";`.
    ExportFrom {
        names: Vec<String>,
        from: String,
    },
    /// `export const name = value;`.
    ExportConst {
        name: String,
        value: Expr,
    },
    /// `export default value;`.
    ExportDefault(Expr),
    /// `//# sourceMappingURL=url`, the last line of a module with a source map.
    SourceMappingUrl(String),
}

/// A program module.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Module {
    pub items: Vec<Item>,
}

/// Where a statement with a source origin starts in the printed text.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Mapping {
    /// 0-based generated line.
    pub line: u32,
    /// 0-based generated column.
    pub column: u32,
    /// The Mtek source the statement originates from.
    pub span: Span,
}

/// A printed module and its mappings, in text order.
#[derive(Clone, Debug, PartialEq)]
pub struct JsModule {
    pub text: String,
    pub mappings: Vec<Mapping>,
}

/// Prints `module`.
#[must_use]
pub fn print(module: &Module) -> JsModule {
    let mut out = Out {
        p: Printer::new(),
        mappings: Vec::new(),
    };
    for item in &module.items {
        out.item(item);
    }
    JsModule {
        text: out.p.finish(),
        mappings: out.mappings,
    }
}

/// The single-line text of `expr` (multiline objects are printed on one line here).
#[must_use]
pub fn inline(expr: &Expr) -> String {
    match expr {
        Expr::Ident(name) => name.clone(),
        Expr::Str(text) => string_literal(text),
        Expr::Num(number) => number.text(),
        Expr::Bool(value) => value.to_string(),
        Expr::Null => "null".to_owned(),
        Expr::Member(object, name) => member_access(&inline(object), name),
        Expr::Index(object, index) => format!("{}[{index}]", inline(object)),
        Expr::Call(callee, arguments) => format!("{}({})", inline(callee), list(arguments)),
        Expr::New(callee, arguments) => format!("new {}({})", inline(callee), list(arguments)),
        Expr::Object { properties, .. } if properties.is_empty() => "{}".to_owned(),
        Expr::Object { properties, .. } => {
            let items: Vec<String> = properties
                .iter()
                .map(|(key, value)| property(key, &inline(value), value))
                .collect();
            format!("{{ {} }}", items.join(", "))
        }
        Expr::Array(items) => format!("[{}]", list(items)),
    }
}

/// `key: value`, or the shorthand `key` when the value is the identifier `key`.
fn property(key: &str, text: &str, value: &Expr) -> String {
    match value {
        Expr::Ident(name) if name == key && is_identifier_name(key) => key.to_owned(),
        _ => format!("{}: {text}", property_key(key)),
    }
}

fn list(items: &[Expr]) -> String {
    items.iter().map(inline).collect::<Vec<_>>().join(", ")
}

struct Out {
    p: Printer,
    mappings: Vec<Mapping>,
}

impl Out {
    fn map(&mut self, span: Option<Span>) {
        if let Some(span) = span {
            self.mappings.push(Mapping {
                line: u32::try_from(self.p.line_count()).unwrap_or(u32::MAX),
                column: u32::try_from(self.p.indent_width()).unwrap_or(u32::MAX),
                span,
            });
        }
    }

    fn item(&mut self, item: &Item) {
        match item {
            Item::Stmt(stmt) => self.stmt(stmt),
            Item::ImportNamespace { name, from } => self.p.line(&format!(
                "import * as {name} from {};",
                string_literal(from)
            )),
            Item::ExportFrom { names, from } => self.p.line(&format!(
                "export {{ {} }} from {};",
                names.join(", "),
                string_literal(from)
            )),
            Item::ExportConst { name, value } => {
                self.value(&format!("export const {name} = "), value, ";");
            }
            Item::ExportDefault(value) => self.value("export default ", value, ";"),
            Item::SourceMappingUrl(url) => {
                // Only URL-safe characters may follow the pragma; anything else is dropped.
                let safe: String = url
                    .chars()
                    .filter(|c| c.is_ascii_alphanumeric() || "._-/".contains(*c))
                    .collect();
                self.p.line(&format!("//# sourceMappingURL={safe}"));
            }
        }
    }

    fn stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Comment(text) => self.p.line(&line_comment(text)),
            Stmt::Blank => self.p.blank(),
            Stmt::Const { name, value, span } => {
                self.map(*span);
                self.value(&format!("const {name} = "), value, ";");
            }
            Stmt::Expr { expr, span } => {
                self.map(*span);
                self.value("", expr, ";");
            }
            Stmt::Function {
                name,
                params,
                body,
                span,
            } => {
                self.map(*span);
                self.p
                    .line(&format!("function {name}({}) {{", params.join(", ")));
                self.p.indent();
                for inner in body {
                    self.stmt(inner);
                }
                self.p.dedent();
                self.p.line("}");
            }
            Stmt::Verbatim(text) => self.p.verbatim(text),
        }
    }

    /// `prefix value suffix`, spreading a multiline object over several lines.
    fn value(&mut self, prefix: &str, value: &Expr, suffix: &str) {
        match value {
            Expr::Object {
                properties,
                multiline: true,
            } if !properties.is_empty() => {
                self.p.line(&format!("{prefix}{{"));
                self.p.indent();
                for (key, inner) in properties {
                    match inner {
                        Expr::Ident(name) if name == key && is_identifier_name(key) => {
                            self.p.line(&format!("{key},"));
                        }
                        _ => self.value(&format!("{}: ", property_key(key)), inner, ","),
                    }
                }
                self.p.dedent();
                self.p.line(&format!("}}{suffix}"));
            }
            _ => self.p.line(&format!("{prefix}{}{suffix}", inline(value))),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::source::FileId;

    #[test]
    fn f32_literals_are_exactly_the_binary32_value_read_as_binary64() {
        assert_eq!(Number::F32(1.0).text(), "1.0");
        assert_eq!(Number::F32(0.5).text(), "0.5");
        assert_eq!(Number::F32(0.1).text(), "0.10000000149011612");
        assert_eq!(Number::F32(-9.81).text(), "-9.8100004196167");
        assert_eq!(Number::F32(1e-7).text(), "1.0000000116860974e-7");
        assert_eq!(Number::F32(-0.0).text(), "-0.0");
        assert_eq!(Number::F32(f32::NAN).text(), "NaN");
        assert_eq!(Number::F32(f32::NEG_INFINITY).text(), "-Infinity");
        assert_eq!(Number::I32(-7).text(), "-7");
        assert_eq!(Number::U32(4_294_967_295).text(), "4294967295");
        for v in [0.1f32, 1e-7, 3.402_823_5e38, 0.014_443_844] {
            let back: f64 = Number::F32(v).text().parse().expect("number");
            assert_eq!(back, f64::from(v), "{v}");
        }
    }

    #[test]
    fn expressions_print_on_one_line_with_escaping() {
        let call = Expr::ident("ctx").member("setParam").call(vec![
            Expr::ident("e0"),
            Expr::string("a\"b\n"),
            Expr::object(vec![
                ("r".to_owned(), Expr::Num(Number::F32(1.0))),
                ("a-b".to_owned(), Expr::Bool(true)),
            ]),
        ]);
        assert_eq!(
            inline(&call),
            r#"ctx.setParam(e0, "a\"b\n", { r: 1.0, "a-b": true })"#
        );
        assert_eq!(inline(&Expr::object(vec![])), "{}");
        assert_eq!(
            inline(&Expr::Array(vec![Expr::Null, Expr::Null])),
            "[null, null]"
        );
        assert_eq!(inline(&Expr::ident("ctx").member("e").index(3)), "ctx.e[3]");
        assert_eq!(
            inline(&Expr::New(
                Box::new(Expr::ident("URL")),
                vec![Expr::string("./")]
            )),
            r#"new URL("./")"#
        );
    }

    #[test]
    fn modules_print_deterministically_with_mappings() {
        let span = Span::new(FileId(0), 4, 9);
        let module = Module {
            items: vec![
                Item::Stmt(Stmt::Comment("header\nbreak".to_owned())),
                Item::ExportFrom {
                    names: vec!["mountMtek".to_owned()],
                    from: "./runtime.js".to_owned(),
                },
                Item::Stmt(Stmt::Blank),
                Item::Stmt(Stmt::Function {
                    name: "f".to_owned(),
                    params: vec!["ctx".to_owned()],
                    body: vec![
                        Stmt::Const {
                            name: "e0".to_owned(),
                            value: Expr::ident("ctx").member("e").index(0),
                            span: Some(span),
                        },
                        Stmt::Expr {
                            expr: Expr::ident("ctx").member("go").call(vec![]),
                            span: None,
                        },
                    ],
                    span: None,
                }),
                Item::ExportConst {
                    name: "scenes".to_owned(),
                    value: Expr::object_lines(vec![(
                        "Demo".to_owned(),
                        Expr::object_lines(vec![
                            ("init".to_owned(), Expr::ident("f")),
                            ("events".to_owned(), Expr::object_lines(vec![])),
                        ]),
                    )]),
                },
                Item::ExportDefault(Expr::object(vec![(
                    "scenes".to_owned(),
                    Expr::ident("scenes"),
                )])),
            ],
        };
        let printed = print(&module);
        assert_eq!(
            printed.text,
            "// header?break\n\
             export { mountMtek } from \"./runtime.js\";\n\
             \n\
             function f(ctx) {\n  const e0 = ctx.e[0];\n  ctx.go();\n}\n\
             export const scenes = {\n  Demo: {\n    init: f,\n    events: {},\n  },\n};\n\
             export default { scenes };\n"
        );
        assert_eq!(
            printed.mappings,
            [Mapping {
                line: 4,
                column: 2,
                span
            }]
        );
        assert_eq!(print(&module), printed);
    }
}
