//! The host-facing declarations `app.d.ts` (`spec/runtime-abi.md` section 6.4).
//!
//! `app.d.ts` types the default export of `app.js` as `MtekProgram<Inputs>` and re-exports
//! `mountMtek`, both from `./runtime.js`, which TypeScript resolves to the `runtime.d.ts` the
//! build copies next to it. `Inputs` lists the host inputs of `mtek.toml` `[host.inputs]`.

use crate::project::ResolvedHostInput;

use super::printer::line_comment;
use super::program::header;

/// The text of `app.d.ts` for the given host inputs.
#[must_use]
pub fn emit_app_dts(host_inputs: &[ResolvedHostInput]) -> String {
    let mut text = line_comment(&header());
    text.push('\n');
    text.push_str("import type { MtekProgram } from \"./runtime.js\";\n");
    text.push_str("export interface Inputs {");
    if host_inputs.is_empty() {
        text.push('}');
    } else {
        text.push('\n');
        for input in host_inputs {
            text.push_str("  ");
            text.push_str(&input.name);
            text.push_str(": ");
            text.push_str(&input.ts_type);
            text.push_str(";\n");
        }
        text.push('}');
    }
    text.push('\n');
    text.push_str(
        "declare const program: MtekProgram<Inputs>;\n\
         export default program;\n\
         export { mountMtek } from \"./runtime.js\";\n",
    );
    text
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::project::ResolvedHostInput;

    #[test]
    fn empty_inputs_emit_an_empty_interface() {
        let text = emit_app_dts(&[]);
        assert!(text.starts_with("// Generated by mtek "), "{text}");
        assert!(text.contains("export interface Inputs {}\n"), "{text}");
        assert!(text.contains("declare const program: MtekProgram<Inputs>;\n"));
        assert!(text.ends_with("export { mountMtek } from \"./runtime.js\";\n"));
    }

    #[test]
    fn host_inputs_appear_in_the_interface() {
        let inputs = [ResolvedHostInput {
            name: "tint".into(),
            state_name: "tint".into(),
            ty: "color".into(),
            codec: "color-hex-opaque".into(),
            ts_type: "`#${string}`".into(),
        }];
        let text = emit_app_dts(&inputs);
        assert!(
            text.contains("export interface Inputs {\n  tint: `#${string}`;\n}\n"),
            "{text}"
        );
    }
}
