//! The host-facing declarations `app.d.ts` (`spec/runtime-abi.md` section 6.4).
//!
//! `app.d.ts` types the default export of `app.js` as `MtekProgram<Inputs>` and re-exports
//! `mountMtek`, both from `./runtime.js`, which TypeScript resolves to the `runtime.d.ts` the
//! build copies next to it. `Inputs` lists the host inputs of `mtek.toml` `[host.inputs]`;
//! host inputs are M3, so in M1 it is empty.

use super::printer::line_comment;
use super::program::header;

/// The text of `app.d.ts`.
#[must_use]
pub fn emit_app_dts() -> String {
    let mut text = line_comment(&header());
    text.push('\n');
    text.push_str(
        "import type { MtekProgram } from \"./runtime.js\";\n\
         export interface Inputs {}\n\
         declare const program: MtekProgram<Inputs>;\n\
         export default program;\n\
         export { mountMtek } from \"./runtime.js\";\n",
    );
    text
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn declarations_type_the_default_export_and_re_export_mount() {
        let text = emit_app_dts();
        assert!(text.starts_with("// Generated by mtek "), "{text}");
        assert!(text.contains("export interface Inputs {}\n"), "{text}");
        assert!(text.contains("declare const program: MtekProgram<Inputs>;\n"));
        assert!(text.ends_with("export { mountMtek } from \"./runtime.js\";\n"));
    }
}
