//! The program module `app.js` (`spec/runtime-abi.md` sections 3 and 4): [`emit_program`]
//! builds its JavaScript AST from the typed IR and the resource plan.
//!
//! The module has exactly the ABI-1 export surface: the `mountMtek` re-export from the hashed
//! runtime file, `abi`, `baseUrl`, `manifestUrl`, `writers` (keyed by layout id; the writer
//! functions themselves are module-private, `spec/gpu-layout.md` section 7), `functions`,
//! `scenes` (the entry scene only), `prefabs` and the default export of all seven.
//!
//! The entry scene's `init(ctx)` runs the initialisation order of `spec/scenes.md` section 11
//! as straight-line code through the setters of the `ctx` contract
//! (`spec/runtime-abi.md` sections 4.2 and 4.3); the manifest carries no entity or camera
//! values. Cameras and entities follow declaration order (entities in stable instance order):
//!
//! - the active camera: `ctx.setCamera("position", v)`, then `"target"` when declared,
//!   otherwise `"rotation"`, then the projection fields (`"projection.fov_y"` or
//!   `"projection.height"`, `"projection.near"`, `"projection.far"`);
//! - each entity: `ctx.setTransform(e, "position" | "rotation" | "scale", v)`,
//!   `ctx.setVisible(e, v)`, then `ctx.setParam(e, name, v)` for every parameter of its
//!   material instance, which the runtime writes through the generated field writer.
//!
//! Every value is set, defaults included: the runtime pre-creates entity records with zero
//! values, and a zero scale is not a valid transform. In M1 every value is a constant, so the
//! order of the fields inside an entity cannot be observed; they are emitted in registry
//! order. Lifecycle functions, handlers and bindings are M2/M3: `update` and `fixedUpdate` are
//! `null`, `entityUpdate`/`entityFixedUpdate` hold `null` per entity, `events` is `{}` and
//! `bindings` `[]` (the shapes of the runtime's `MtekProgramScene`).

use crate::ir::{Camera, Entity, Program, ProjectionDesc, Scene, Value};
use crate::layout::{LayoutNode, LayoutRecord};
use crate::plan::ResourcePlan;
use crate::{COMPILER_VERSION, LANGUAGE_VERSION, RUNTIME_ABI};

use super::ast::{Expr, Item, JsModule, Module, Number, Stmt, print};
use super::printer::identifier_part;
use super::writers::{emit_writer_parts, writer_qualifier};

/// The file name of the source map `app.js` points to.
pub const SOURCE_MAP_FILE: &str = "app.js.map";

/// What `app.js` needs besides the IR and the plan.
#[derive(Clone, Copy, Debug)]
pub struct ProgramParts<'a> {
    /// The hashed runtime bundle's file name, `runtime.<h16>.js`.
    pub runtime_file: &'a str,
    /// The layout records whose writers the module carries, in `writers` table order
    /// (`builtin:frame`, `builtin:object`, then the material blocks by id).
    pub layouts: &'a [LayoutRecord],
}

/// The comment on the first line of every generated file.
#[must_use]
pub fn header() -> String {
    // ASCII, like all generated code (the source map counts columns in bytes).
    format!("Generated by mtek {COMPILER_VERSION} for language {LANGUAGE_VERSION}. Do not edit.")
}

/// The name of the entry scene's initialiser: `s_<Name>_init`. The `s_` prefix is never
/// produced by user-name mangling (`f_`, `l_`, `a_`, `spec/runtime-abi.md` section 3).
#[must_use]
pub fn init_function_name(scene: &Scene) -> String {
    format!("s_{}_init", identifier_part(&scene.name))
}

/// Builds `app.js` for the entry scene of `program`.
///
/// # Errors
/// A text describing a compiler defect: no entry scene, a value the CPU representation does
/// not cover, or an entity without a plan entry.
pub fn emit_program(
    program: &Program,
    plan: &ResourcePlan,
    parts: &ProgramParts<'_>,
) -> Result<JsModule, String> {
    let scene = program
        .entry()
        .ok_or_else(|| format!("the entry scene '{}' is not in the IR", program.entry_scene))?;
    let mut items = vec![
        Item::Stmt(Stmt::Comment(header())),
        Item::ExportFrom {
            names: vec!["mountMtek".to_owned()],
            from: format!("./{}", parts.runtime_file),
        },
        Item::Stmt(Stmt::Blank),
        Item::ExportConst {
            name: "abi".to_owned(),
            value: Expr::Num(Number::U32(RUNTIME_ABI)),
        },
        Item::ExportConst {
            name: "baseUrl".to_owned(),
            value: new_url("./"),
        },
        Item::ExportConst {
            name: "manifestUrl".to_owned(),
            value: new_url("./program.manifest.json"),
        },
    ];

    let mut table = Vec::with_capacity(parts.layouts.len());
    for record in parts.layouts {
        let emitted = emit_writer_parts(record, &writer_qualifier(record));
        items.push(Item::Stmt(Stmt::Blank));
        items.push(Item::Stmt(Stmt::Verbatim(emitted.functions)));
        table.push((
            record.id.clone(),
            writer_entry(record, &emitted.function_names),
        ));
    }
    items.push(Item::Stmt(Stmt::Blank));
    items.push(Item::ExportConst {
        name: "writers".to_owned(),
        value: Expr::object_lines(table),
    });
    items.push(Item::Stmt(Stmt::Blank));
    items.push(Item::ExportConst {
        name: "functions".to_owned(),
        value: Expr::object_lines(Vec::new()),
    });

    let init = init_function_name(scene);
    items.push(Item::Stmt(Stmt::Blank));
    items.push(Item::Stmt(Stmt::Comment(format!(
        "scene {} ({}): the initialisation order of spec/scenes.md section 11",
        scene.name, scene.symbol
    ))));
    items.push(Item::Stmt(Stmt::Function {
        name: init.clone(),
        params: vec!["ctx".to_owned()],
        body: init_body(scene, plan)?,
        span: Some(scene.span),
    }));
    let nulls = Expr::Array(vec![Expr::Null; scene.entities.len()]);
    items.push(Item::Stmt(Stmt::Blank));
    items.push(Item::ExportConst {
        name: "scenes".to_owned(),
        value: Expr::object_lines(vec![(
            scene.name.clone(),
            Expr::object_lines(vec![
                ("init".to_owned(), Expr::Ident(init)),
                ("update".to_owned(), Expr::Null),
                ("fixedUpdate".to_owned(), Expr::Null),
                ("entityUpdate".to_owned(), nulls.clone()),
                ("entityFixedUpdate".to_owned(), nulls),
                ("events".to_owned(), Expr::object(Vec::new())),
                ("bindings".to_owned(), Expr::Array(Vec::new())),
            ]),
        )]),
    });
    items.push(Item::Stmt(Stmt::Blank));
    items.push(Item::ExportConst {
        name: "prefabs".to_owned(),
        value: Expr::object_lines(Vec::new()),
    });
    items.push(Item::Stmt(Stmt::Blank));
    let surface = [
        "abi",
        "baseUrl",
        "manifestUrl",
        "writers",
        "functions",
        "scenes",
        "prefabs",
    ];
    items.push(Item::ExportDefault(Expr::object(
        surface
            .iter()
            .map(|name| ((*name).to_owned(), Expr::ident(name)))
            .collect(),
    )));
    items.push(Item::SourceMappingUrl(SOURCE_MAP_FILE.to_owned()));
    Ok(print(&Module { items }))
}

/// `new URL(relative, import.meta.url)`.
fn new_url(relative: &str) -> Expr {
    Expr::New(
        Box::new(Expr::ident("URL")),
        vec![
            Expr::string(relative),
            Expr::ident("import").member("meta").member("url"),
        ],
    )
}

/// `{ all: w_<qual>, fields: { <member>: w_<qual>_<member>, … } }`: the same entry
/// [`emit_writer_parts`] prints as its `table_entry`.
fn writer_entry(record: &LayoutRecord, function_names: &[String]) -> Expr {
    let members: &[crate::layout::LayoutMember] = match &record.root {
        LayoutNode::Struct { members, .. } => members,
        _ => &[],
    };
    let mut names = function_names.iter();
    let all = names.next().cloned().unwrap_or_default();
    let fields = members
        .iter()
        .zip(names)
        .map(|(member, name)| (member.name.clone(), Expr::Ident(name.clone())))
        .collect();
    Expr::object(vec![
        ("all".to_owned(), Expr::Ident(all)),
        ("fields".to_owned(), Expr::object(fields)),
    ])
}

/// A declaration of the scene body that `init` initialises.
enum Declaration<'a> {
    Camera(&'a Camera),
    Entity(&'a Entity),
}

impl Declaration<'_> {
    fn start(&self) -> u32 {
        match self {
            Declaration::Camera(camera) => camera.span.start,
            Declaration::Entity(entity) => entity.span.start,
        }
    }
}

/// The body of `init(ctx)`.
fn init_body(scene: &Scene, plan: &ResourcePlan) -> Result<Vec<Stmt>, String> {
    // The active camera and the entities, in declaration order. Entities are already in
    // pre-order (increasing start); a stable sort places the camera among them.
    let mut declarations: Vec<Declaration<'_>> = Vec::with_capacity(scene.entities.len() + 1);
    if let Some(camera) = scene.active_camera() {
        declarations.push(Declaration::Camera(camera));
    }
    declarations.extend(scene.entities.iter().map(Declaration::Entity));
    declarations.sort_by_key(Declaration::start);

    let mut body = Vec::new();
    for declaration in declarations {
        match declaration {
            Declaration::Camera(camera) => camera_statements(camera, &mut body)?,
            Declaration::Entity(entity) => entity_statements(entity, plan, &mut body)?,
        }
    }
    Ok(body)
}

fn ctx_call(method: &str, arguments: Vec<Expr>) -> Expr {
    Expr::ident("ctx").member(method).call(arguments)
}

fn constant<'a>(field: &'a crate::ir::Field, what: &str) -> Result<&'a Value, String> {
    field
        .source
        .as_const()
        .ok_or_else(|| format!("{what} has no constant value"))
}

fn camera_statements(camera: &Camera, body: &mut Vec<Stmt>) -> Result<(), String> {
    body.push(Stmt::Comment(format!(
        "camera {} ({}), active",
        camera.name, camera.symbol
    )));
    let mut set = |field: &str, value: Expr, span| {
        body.push(Stmt::Expr {
            expr: ctx_call("setCamera", vec![Expr::string(field), value]),
            span: Some(span),
        });
    };
    let position = constant(&camera.position, "the camera position")?;
    set("position", value_expr(position)?, camera.position.span);
    match &camera.target {
        Some(target) => {
            let value = constant(target, "the camera target")?;
            set("target", value_expr(value)?, target.span);
        }
        None => {
            let value = constant(&camera.rotation, "the camera rotation")?;
            set("rotation", value_expr(value)?, camera.rotation.span);
        }
    }
    let span = camera.projection.span;
    let f32 = |v: f32| Expr::Num(Number::F32(v));
    match camera.projection.desc {
        ProjectionDesc::Perspective { fov_y, near, far } => {
            set("projection.fov_y", f32(fov_y), span);
            set("projection.near", f32(near), span);
            set("projection.far", f32(far), span);
        }
        ProjectionDesc::Orthographic { height, near, far } => {
            set("projection.height", f32(height), span);
            set("projection.near", f32(near), span);
            set("projection.far", f32(far), span);
        }
    }
    Ok(())
}

fn entity_statements(
    entity: &Entity,
    plan: &ResourcePlan,
    body: &mut Vec<Stmt>,
) -> Result<(), String> {
    let record = format!("e{}", entity.index);
    body.push(Stmt::Comment(format!(
        "entity #{} {} ({})",
        entity.index, entity.name, entity.symbol
    )));
    body.push(Stmt::Const {
        name: record.clone(),
        value: Expr::ident("ctx").member("e").index(entity.index),
        span: Some(entity.span),
    });
    for (name, field) in [
        ("position", &entity.position),
        ("rotation", &entity.rotation),
        ("scale", &entity.scale),
    ] {
        let value = constant(field, &format!("the {name} of '{}'", entity.symbol))?;
        body.push(Stmt::Expr {
            expr: ctx_call(
                "setTransform",
                vec![Expr::ident(&record), Expr::string(name), value_expr(value)?],
            ),
            span: Some(field.span),
        });
    }
    let visible = constant(
        &entity.visible,
        &format!("the visibility of '{}'", entity.symbol),
    )?;
    body.push(Stmt::Expr {
        expr: ctx_call(
            "setVisible",
            vec![Expr::ident(&record), value_expr(visible)?],
        ),
        span: Some(entity.visible.span),
    });
    let instance = plan
        .entity_instances
        .get(entity.index as usize)
        .ok_or_else(|| format!("the entity '{}' is not in the plan", entity.symbol))?;
    if let (Some(index), Some(material)) = (instance, &entity.material) {
        let planned = plan
            .instances
            .get(*index as usize)
            .ok_or_else(|| format!("the material instance {index} is not in the plan"))?;
        for (param, desc) in planned.params.iter().zip(&material.params) {
            body.push(Stmt::Expr {
                expr: ctx_call(
                    "setParam",
                    vec![
                        Expr::ident(&record),
                        Expr::string(&param.name),
                        value_expr(&param.value)?,
                    ],
                ),
                span: Some(desc.span),
            });
        }
    }
    Ok(())
}

/// The CPU representation of a constant (`spec/runtime-abi.md` section 4.1).
///
/// # Errors
/// Never in M1; kept fallible so a value the representation does not cover is a reported
/// defect rather than wrong code.
pub fn value_expr(value: &Value) -> Result<Expr, String> {
    let f32 = |v: f32| Expr::Num(Number::F32(v));
    let components = |names: &[&str], values: &[f32]| {
        Expr::object(
            names
                .iter()
                .zip(values)
                .map(|(name, value)| ((*name).to_owned(), f32(*value)))
                .collect(),
        )
    };
    Ok(match value {
        Value::Bool(v) => Expr::Bool(*v),
        Value::I32(v) => Expr::Num(Number::I32(*v)),
        Value::U32(v) => Expr::Num(Number::U32(*v)),
        Value::F32(v) => f32(*v),
        Value::Vec2(v) => components(&["x", "y"], v),
        Value::Vec3(v) => components(&["x", "y", "z"], v),
        Value::Vec4(v) | Value::Quat(v) => components(&["x", "y", "z", "w"], v),
        Value::Color(v) => components(&["r", "g", "b", "a"], v),
        Value::Mat4(columns) => Expr::New(
            Box::new(Expr::ident("Float32Array")),
            vec![Expr::Array(
                columns.iter().flatten().map(|v| f32(*v)).collect(),
            )],
        ),
        Value::Struct { fields, .. } => {
            let mut properties = Vec::with_capacity(fields.len());
            for field in fields {
                properties.push((field.name.clone(), value_expr(&field.value)?));
            }
            Expr::object(properties)
        }
        Value::Array(items) => {
            let mut elements = Vec::with_capacity(items.len());
            for item in items {
                elements.push(value_expr(item)?);
            }
            Expr::Array(elements)
        }
        Value::String(text) => Expr::string(text),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::emit_js::ast::inline;
    use crate::emit_js::printer::property_key;
    use crate::ir::NamedValue;
    use crate::layout::{builtin_blocks, compute};

    #[test]
    fn values_have_the_cpu_shapes() {
        let text = |v: Value| inline(&value_expr(&v).expect("covered"));
        assert_eq!(text(Value::Bool(false)), "false");
        assert_eq!(
            text(Value::Vec3([0.0, 0.5, -1.0])),
            "{ x: 0.0, y: 0.5, z: -1.0 }"
        );
        assert_eq!(
            text(Value::Quat([0.0, 0.0, 0.0, 1.0])),
            "{ x: 0.0, y: 0.0, z: 0.0, w: 1.0 }"
        );
        assert_eq!(
            text(Value::Color([0.1, 0.0, 1.0, 1.0])),
            "{ r: 0.10000000149011612, g: 0.0, b: 1.0, a: 1.0 }"
        );
        assert_eq!(text(Value::Vec2([1.0, 2.0])), "{ x: 1.0, y: 2.0 }");
        assert_eq!(text(Value::U32(24)), "24");
        assert_eq!(text(Value::I32(-3)), "-3");
        let identity = [
            [1.0, 0.0, 0.0, 0.0],
            [0.0, 1.0, 0.0, 0.0],
            [0.0, 0.0, 1.0, 0.0],
            [0.0, 0.0, 0.0, 1.0],
        ];
        assert!(
            text(Value::Mat4(identity))
                .starts_with("new Float32Array([1.0, 0.0, 0.0, 0.0, 0.0, 1.0")
        );
        assert_eq!(
            text(Value::Struct {
                name: "S".to_owned(),
                fields: vec![NamedValue {
                    name: "a".to_owned(),
                    value: Value::Array(vec![Value::F32(1.0)]),
                }],
            }),
            "{ a: [1.0] }"
        );
    }

    #[test]
    fn writer_entries_equal_the_m0_table_entries() {
        for block in builtin_blocks() {
            let record = compute(&block.ty, block.id, block.wgsl_struct).expect("laid out");
            let emitted = emit_writer_parts(&record, &writer_qualifier(&record));
            let entry = writer_entry(&record, &emitted.function_names);
            assert_eq!(
                format!("{}: {},", property_key(&record.id), inline(&entry)),
                emitted.table_entry
            );
        }
    }

    #[test]
    fn the_header_names_the_versions() {
        assert_eq!(
            header(),
            "Generated by mtek 0.1.0-dev for language 0.1. Do not edit."
        );
    }
}
