// Generated by mtek 0.1.0-dev for language 0.1. Do not edit.
import * as rt from "./runtime.75e25692ce38d7a0.js";
export { mountMtek } from "./runtime.75e25692ce38d7a0.js";
const fr = Math.fround;

export const abi = 1;
export const baseUrl = new URL("./", import.meta.url);
export const manifestUrl = new URL("./program.manifest.json", import.meta.url);

// Generated from layout builtin:frame (size 288). Do not edit.
function w_builtin_MtekFrame_view_proj(m, base, v) {
  const w = base >>> 2;
  m.f32[w + 0] = v[0]; m.f32[w + 1] = v[1]; m.f32[w + 2] = v[2]; m.f32[w + 3] = v[3];
  m.f32[w + 4] = v[4]; m.f32[w + 5] = v[5]; m.f32[w + 6] = v[6]; m.f32[w + 7] = v[7];
  m.f32[w + 8] = v[8]; m.f32[w + 9] = v[9]; m.f32[w + 10] = v[10]; m.f32[w + 11] = v[11];
  m.f32[w + 12] = v[12]; m.f32[w + 13] = v[13]; m.f32[w + 14] = v[14]; m.f32[w + 15] = v[15];
}
function w_builtin_MtekFrame_camera_position(m, base, v) {
  const w = base >>> 2;
  m.f32[w + 16] = v.x; m.f32[w + 17] = v.y; m.f32[w + 18] = v.z;
}
function w_builtin_MtekFrame_light_count(m, base, v) {
  m.u32[(base >>> 2) + 19] = v;
}
function w_builtin_MtekFrame_ambient(m, base, v) {
  const w = base >>> 2;
  m.f32[w + 20] = v.x; m.f32[w + 21] = v.y; m.f32[w + 22] = v.z;
}
function w_builtin_MtekFrame_reserved0(m, base, v) {
  m.f32[(base >>> 2) + 23] = v;
}
function w_builtin_MtekFrame_lights(m, base, v) {
  const w = base >>> 2;
  m.f32[w + 24] = v[0].color.x; m.f32[w + 25] = v[0].color.y; m.f32[w + 26] = v[0].color.z;
  m.u32[w + 27] = v[0].kind;
  m.f32[w + 28] = v[0].position.x; m.f32[w + 29] = v[0].position.y; m.f32[w + 30] = v[0].position.z;
  m.f32[w + 31] = v[0].range;
  m.f32[w + 32] = v[0].direction.x; m.f32[w + 33] = v[0].direction.y; m.f32[w + 34] = v[0].direction.z;
  m.f32[w + 35] = v[0].reserved;
  m.f32[w + 36] = v[1].color.x; m.f32[w + 37] = v[1].color.y; m.f32[w + 38] = v[1].color.z;
  m.u32[w + 39] = v[1].kind;
  m.f32[w + 40] = v[1].position.x; m.f32[w + 41] = v[1].position.y; m.f32[w + 42] = v[1].position.z;
  m.f32[w + 43] = v[1].range;
  m.f32[w + 44] = v[1].direction.x; m.f32[w + 45] = v[1].direction.y; m.f32[w + 46] = v[1].direction.z;
  m.f32[w + 47] = v[1].reserved;
  m.f32[w + 48] = v[2].color.x; m.f32[w + 49] = v[2].color.y; m.f32[w + 50] = v[2].color.z;
  m.u32[w + 51] = v[2].kind;
  m.f32[w + 52] = v[2].position.x; m.f32[w + 53] = v[2].position.y; m.f32[w + 54] = v[2].position.z;
  m.f32[w + 55] = v[2].range;
  m.f32[w + 56] = v[2].direction.x; m.f32[w + 57] = v[2].direction.y; m.f32[w + 58] = v[2].direction.z;
  m.f32[w + 59] = v[2].reserved;
  m.f32[w + 60] = v[3].color.x; m.f32[w + 61] = v[3].color.y; m.f32[w + 62] = v[3].color.z;
  m.u32[w + 63] = v[3].kind;
  m.f32[w + 64] = v[3].position.x; m.f32[w + 65] = v[3].position.y; m.f32[w + 66] = v[3].position.z;
  m.f32[w + 67] = v[3].range;
  m.f32[w + 68] = v[3].direction.x; m.f32[w + 69] = v[3].direction.y; m.f32[w + 70] = v[3].direction.z;
  m.f32[w + 71] = v[3].reserved;
}
function w_builtin_MtekFrame(m, base, v) {
  w_builtin_MtekFrame_view_proj(m, base, v.view_proj);
  w_builtin_MtekFrame_camera_position(m, base, v.camera_position);
  w_builtin_MtekFrame_light_count(m, base, v.light_count);
  w_builtin_MtekFrame_ambient(m, base, v.ambient);
  w_builtin_MtekFrame_reserved0(m, base, v.reserved0);
  w_builtin_MtekFrame_lights(m, base, v.lights);
}

// Generated from layout builtin:object (size 128). Do not edit.
function w_builtin_MtekObject_model(m, base, v) {
  const w = base >>> 2;
  m.f32[w + 0] = v[0]; m.f32[w + 1] = v[1]; m.f32[w + 2] = v[2]; m.f32[w + 3] = v[3];
  m.f32[w + 4] = v[4]; m.f32[w + 5] = v[5]; m.f32[w + 6] = v[6]; m.f32[w + 7] = v[7];
  m.f32[w + 8] = v[8]; m.f32[w + 9] = v[9]; m.f32[w + 10] = v[10]; m.f32[w + 11] = v[11];
  m.f32[w + 12] = v[12]; m.f32[w + 13] = v[13]; m.f32[w + 14] = v[14]; m.f32[w + 15] = v[15];
}
function w_builtin_MtekObject_normal_matrix(m, base, v) {
  const w = base >>> 2;
  m.f32[w + 16] = v[0]; m.f32[w + 17] = v[1]; m.f32[w + 18] = v[2]; m.f32[w + 19] = v[3];
  m.f32[w + 20] = v[4]; m.f32[w + 21] = v[5]; m.f32[w + 22] = v[6]; m.f32[w + 23] = v[7];
  m.f32[w + 24] = v[8]; m.f32[w + 25] = v[9]; m.f32[w + 26] = v[10]; m.f32[w + 27] = v[11];
  m.f32[w + 28] = v[12]; m.f32[w + 29] = v[13]; m.f32[w + 30] = v[14]; m.f32[w + 31] = v[15];
}
function w_builtin_MtekObject(m, base, v) {
  w_builtin_MtekObject_model(m, base, v.model);
  w_builtin_MtekObject_normal_matrix(m, base, v.normal_matrix);
}

export const writers = {
  "builtin:frame": { all: w_builtin_MtekFrame, fields: { view_proj: w_builtin_MtekFrame_view_proj, camera_position: w_builtin_MtekFrame_camera_position, light_count: w_builtin_MtekFrame_light_count, ambient: w_builtin_MtekFrame_ambient, reserved0: w_builtin_MtekFrame_reserved0, lights: w_builtin_MtekFrame_lights } },
  "builtin:object": { all: w_builtin_MtekObject, fields: { model: w_builtin_MtekObject_model, normal_matrix: w_builtin_MtekObject_normal_matrix } },
};

// fn field_writes(p: src/main.mtek::Probe, w: f32) -> src/main.mtek::Probe (src/main.mtek::field_writes)
function f_e2cab98b_field_writes(ctx, a_p, a_w) {
  let l_q = rt.copy(a_p);
  l_q.weight = a_w;
  l_q.offset = rt.v3with(l_q.offset, "y", 5.0);
  l_q.enabled = !l_q.enabled;
  l_q.samples[2] = a_w;
  l_q.weight = fr(l_q.weight + 1.0);
  return l_q;
}

// fn set_at(i: i32, v: f32) -> array<f32, 4> (src/main.mtek::set_at)
function f_e2cab98b_set_at(ctx, a_i, a_v) {
  let l_xs = [1.0, 2.0, 3.0, 4.0];
  l_xs[rt.clampIndex(a_i, 4, 20, ctx)] = a_v;
  return l_xs;
}

// fn set_at_u(i: u32, v: f32) -> array<f32, 4> (src/main.mtek::set_at_u)
function f_e2cab98b_set_at_u(ctx, a_i, a_v) {
  let l_xs = [1.0, 2.0, 3.0, 4.0];
  l_xs[rt.clampIndex(a_i, 4, 21, ctx)] = a_v;
  return l_xs;
}

// fn flags(i: i32) -> array<bool, 3> (src/main.mtek::flags)
function f_e2cab98b_flags(ctx, a_i) {
  let l_f = [false, false, false];
  l_f[rt.clampIndex(a_i, 3, 22, ctx)] = true;
  return l_f;
}

// fn nested(i: i32, j: u32) -> src/main.mtek::Rig (src/main.mtek::nested)
function f_e2cab98b_nested(ctx, a_i, a_j) {
  let l_rig = { probes: [{ offset: { x: 1.0, y: 2.0, z: 3.0 }, weight: 0.5, enabled: true, samples: [0.0, 0.25, 0.5, 0.75] }, { offset: { x: -1.0, y: 0.0, z: 1.0 }, weight: 2.0, enabled: false, samples: [1.0, 2.0, 3.0, 4.0] }], grid: [[1, 2], [3, 4]] };
  {
    const t_0 = rt.clampIndex(a_i, 2, 23, ctx);
    l_rig.probes[t_0].offset = rt.v3with(l_rig.probes[t_0].offset, "x", fr(l_rig.probes[t_0].offset.x + 1.0));
  }
  l_rig.probes[1].samples[rt.clampIndex(a_j, 4, 24, ctx)] = 7.0;
  {
    const t_1 = rt.clampIndex(a_i, 2, 25, ctx);
    const t_2 = rt.clampIndex(a_j, 2, 26, ctx);
    l_rig.grid[t_1][t_2] = (l_rig.grid[t_1][t_2] + 10) | 0;
  }
  return l_rig;
}

// fn compound(i: i32) -> array<vec3, 3> (src/main.mtek::compound)
function f_e2cab98b_compound(ctx, a_i) {
  let l_vs = [{ x: 1.0, y: 1.0, z: 1.0 }, { x: 2.0, y: 2.0, z: 2.0 }, { x: 3.0, y: 3.0, z: 3.0 }];
  {
    const t_0 = rt.clampIndex(a_i, 3, 27, ctx);
    l_vs[t_0] = rt.v3with(l_vs[t_0], "z", fr(l_vs[t_0].z + 0.5));
  }
  {
    const t_1 = rt.clampIndex(a_i, 3, 28, ctx);
    l_vs[t_1] = rt.v3scale(l_vs[t_1], 2.0);
  }
  l_vs[0] = rt.v3with(l_vs[0], "x", fr(l_vs[0].x - 1.0));
  l_vs[2] = rt.v3divs(l_vs[2], 4.0);
  return l_vs;
}

// fn fill(n: i32) -> array<i32, 5> (src/main.mtek::fill)
function f_e2cab98b_fill(ctx, a_n) {
  let l_out = [0, 0, 0, 0, 0];
  for (let l_k = 0, t_0 = a_n; l_k < t_0; l_k++) {
    {
      const t_1 = rt.clampIndex(l_k, 5, 29, ctx);
      l_out[t_1] = (l_out[t_1] + Math.imul(l_k, l_k)) | 0;
    }
  }
  return l_out;
}

// fn alias_var() -> array<f32, 4> (src/main.mtek::alias_var)
function f_e2cab98b_alias_var(ctx) {
  let l_b = [1.0, 2.0, 3.0, 4.0];
  let l_a = rt.copy(l_b);
  l_a[0] = 100.0;
  return l_b;
}

// fn alias_both() -> f32 (src/main.mtek::alias_both)
function f_e2cab98b_alias_both(ctx) {
  let l_b = [1.0, 2.0, 3.0, 4.0];
  let l_a = rt.copy(l_b);
  l_a[0] = 100.0;
  l_b[1] = 50.0;
  return fr(fr(fr(l_a[0] + l_a[1]) + l_b[0]) + l_b[1]);
}

// fn alias_let(i: i32) -> f32 (src/main.mtek::alias_let)
function f_e2cab98b_alias_let(ctx, a_i) {
  let l_a = [1.0, 2.0, 3.0, 4.0];
  const l_snapshot = rt.copy(l_a);
  l_a[rt.clampIndex(a_i, 4, 30, ctx)] = 0.0;
  return fr(l_snapshot[rt.clampIndex(a_i, 4, 31, ctx)] + l_a[rt.clampIndex(a_i, 4, 32, ctx)]);
}

// fn alias_nested() -> f32 (src/main.mtek::alias_nested)
function f_e2cab98b_alias_nested(ctx) {
  let l_rig = { probes: [{ offset: { x: 1.0, y: 2.0, z: 3.0 }, weight: 0.5, enabled: true, samples: [0.0, 0.25, 0.5, 0.75] }, { offset: { x: -1.0, y: 0.0, z: 1.0 }, weight: 2.0, enabled: false, samples: [1.0, 2.0, 3.0, 4.0] }], grid: [[1, 2], [3, 4]] };
  let l_p = rt.copy(l_rig.probes[0]);
  l_p.weight = 9.0;
  l_rig.probes[1] = rt.copy(l_p);
  l_p.samples[0] = 5.0;
  return fr(fr(fr(l_rig.probes[0].weight + l_rig.probes[1].weight) + l_rig.probes[1].samples[0]) + l_p.samples[0]);
}

// fn alias_param(xs: array<f32, 4>) -> array<f32, 4> (src/main.mtek::alias_param)
function f_e2cab98b_alias_param(ctx, a_xs) {
  let l_ys = rt.copy(a_xs);
  l_ys[3] = -1.0;
  return l_ys;
}

// fn alias_for(i: i32) -> f32 (src/main.mtek::alias_for)
function f_e2cab98b_alias_for(ctx, a_i) {
  let l_xs = [1.0, 2.0, 3.0, 4.0];
  let l_sum = 0.0;
  for (const l_x of rt.copy(l_xs)) {
    l_xs[rt.clampIndex(a_i, 4, 33, ctx)] = 100.0;
    l_sum = fr(l_sum + l_x);
  }
  return fr(l_sum + l_xs[rt.clampIndex(a_i, 4, 34, ctx)]);
}

// fn keep(xs: array<f32, 2>) -> array<f32, 2> (src/main.mtek::keep)
function f_e2cab98b_keep(ctx, a_xs) {
  return a_xs;
}

// fn alias_through_call() -> f32 (src/main.mtek::alias_through_call)
function f_e2cab98b_alias_through_call(ctx) {
  const l_b = [1.0, 2.0];
  let l_a = rt.copy(f_e2cab98b_keep(ctx, l_b));
  l_a[0] = 9.0;
  return fr(l_b[0] + l_a[0]);
}

// fn constant_across_calls(i: i32) -> f32 (src/main.mtek::constant_across_calls)
function f_e2cab98b_constant_across_calls(ctx, a_i) {
  let l_a = [1.0, 2.0, 3.0, 4.0];
  {
    const t_0 = rt.clampIndex(a_i, 4, 35, ctx);
    l_a[t_0] = fr(l_a[t_0] + 10.0);
  }
  return l_a[rt.clampIndex(a_i, 4, 36, ctx)];
}

// fn rig_weight(w: f32) -> f32 (src/main.mtek::rig_weight)
function f_e2cab98b_rig_weight(ctx, a_w) {
  let l_r = { probes: [{ offset: { x: 1.0, y: 2.0, z: 3.0 }, weight: 0.5, enabled: true, samples: [0.0, 0.25, 0.5, 0.75] }, { offset: { x: -1.0, y: 0.0, z: 1.0 }, weight: 2.0, enabled: false, samples: [1.0, 2.0, 3.0, 4.0] }], grid: [[1, 2], [3, 4]] };
  l_r.probes[0].weight = fr(l_r.probes[0].weight + a_w);
  return l_r.probes[0].weight;
}

// cpu fn reach_all() (src/main.mtek::reach_all)
function f_e2cab98b_reach_all(ctx) {
  f_e2cab98b_field_writes(ctx, { offset: { x: 1.0, y: 2.0, z: 3.0 }, weight: 0.5, enabled: true, samples: [0.0, 0.25, 0.5, 0.75] }, 0.0);
  f_e2cab98b_set_at(ctx, 0, 0.0);
  f_e2cab98b_set_at_u(ctx, 0, 0.0);
  f_e2cab98b_flags(ctx, 0);
  f_e2cab98b_nested(ctx, 0, 0);
  f_e2cab98b_compound(ctx, 0);
  f_e2cab98b_fill(ctx, 0);
  f_e2cab98b_alias_var(ctx);
  f_e2cab98b_alias_both(ctx);
  f_e2cab98b_alias_let(ctx, 0);
  f_e2cab98b_alias_nested(ctx);
  f_e2cab98b_alias_param(ctx, [1.0, 2.0, 3.0, 4.0]);
  f_e2cab98b_alias_for(ctx, 0);
  f_e2cab98b_keep(ctx, [0.0, 0.0]);
  f_e2cab98b_alias_through_call(ctx);
  f_e2cab98b_constant_across_calls(ctx, 0);
  f_e2cab98b_rig_weight(ctx, 0.0);
}

export const functions = {
  "src/main.mtek::field_writes": f_e2cab98b_field_writes,
  "src/main.mtek::set_at": f_e2cab98b_set_at,
  "src/main.mtek::set_at_u": f_e2cab98b_set_at_u,
  "src/main.mtek::flags": f_e2cab98b_flags,
  "src/main.mtek::nested": f_e2cab98b_nested,
  "src/main.mtek::compound": f_e2cab98b_compound,
  "src/main.mtek::fill": f_e2cab98b_fill,
  "src/main.mtek::alias_var": f_e2cab98b_alias_var,
  "src/main.mtek::alias_both": f_e2cab98b_alias_both,
  "src/main.mtek::alias_let": f_e2cab98b_alias_let,
  "src/main.mtek::alias_nested": f_e2cab98b_alias_nested,
  "src/main.mtek::alias_param": f_e2cab98b_alias_param,
  "src/main.mtek::alias_for": f_e2cab98b_alias_for,
  "src/main.mtek::keep": f_e2cab98b_keep,
  "src/main.mtek::alias_through_call": f_e2cab98b_alias_through_call,
  "src/main.mtek::constant_across_calls": f_e2cab98b_constant_across_calls,
  "src/main.mtek::rig_weight": f_e2cab98b_rig_weight,
  "src/main.mtek::reach_all": f_e2cab98b_reach_all,
};

// scene Places (src/main.mtek::Places): the initialisation order of spec/scenes.md section 11
function s_Places_init(ctx) {
  // camera Main (src/main.mtek::Places.Main), active
  ctx.setCamera("position", { x: 0.0, y: 0.0, z: 5.0 });
  ctx.setCamera("rotation", { x: 0.0, y: 0.0, z: 0.0, w: 1.0 });
  ctx.setCamera("projection.fov_y", 0.8999999761581421);
  ctx.setCamera("projection.near", 0.10000000149011612);
  ctx.setCamera("projection.far", 1000.0);
}

export const scenes = {
  Places: {
    init: s_Places_init,
    update: null,
    fixedUpdate: null,
    entityUpdate: [],
    entityFixedUpdate: [],
    events: {},
    bindings: [],
  },
};

export const prefabs = {};

export default { abi, baseUrl, manifestUrl, writers, functions, scenes, prefabs };
//# sourceMappingURL=app.js.map
